### ISSUE TITLE
Parse tree/Symbols results are too degraded

### ISSUE THREAD

**Issue by OkayX6** [fsharp/FSharp.Compiler.Service#111]
In this situation, more symbols should be returned.
In particular: all symbols inside `Method1`, `Method2`, and if not too difficult, `Method3`.

![image](https://cloud.githubusercontent.com/assets/1169339/2601112/381112a8-bb0b-11e3-98dd-3c4de0d0bb32.png)

**Comment by dsyme** [comment]
Closing old discussion
