### ISSUE TITLE
AST introspection within F# Interactive

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/FSharp.Compiler.Service#13]
Let me start by saying that I am very pleased to see this project turn up, particularly since it has the potential of making my work with mbrace much easier. I am refering to the mbrace shell, which is essentially a modified fsi capable of persisting interactions to assembly files for distribution.

I would like to propose adding a custom version of F# interactive that is capable of introspecting the AST's (be they typed or untyped) of its own interactions. The api would be something along the lines of adding a static facade in the `FSharp.Compiler.Service.Shell` namespace that looks like this:

``` fsharp
type ShellIntrospection =
  class
    static member IsFsiProcess : bool
    static member GetInteractionAst : idx:int -> ParsedInput list
  end
```

Assuming that the `IsFsiProcess` property is true, calling `GetInteractionAst` with argument 1 would return the AST for interaction `FSI_0001`, assuming it has already materialized.

If you want, I could contribute the relevant code.

**Comment by dsyme** [comment]
Closing old discussion
