### ISSUE TITLE
Bad resilience against checker errors when providing declarations

### ISSUE THREAD

**Issue by rojepp** [fsharp/FSharp.Compiler.Service#139]
Originally from fsharp/fsharpbinding#541.

The local function `abc` will not show when invoking completion at the '§': 

``` fsharp
type Test() = 
    let abc a b c = a + b + c
    member x.Test = §
```

![screenshot 2014-05-06 08 33 43](https://cloud.githubusercontent.com/assets/588746/2905839/7f43858e-d609-11e3-8918-06e8e9d46e85.png)

If you type an 'a' and wait for the typechecker to complete, you will get the completion. But in most cases, you type faster than the type checker,so when you type 'a' and invoke completion, `abc` won't be there.

I'll be sending a PR with some tests.

**Comment by 7sharp9** [comment]
This one can make the editor shortcuts hard work, you have to wait for 3 seconds before a potential tooltip to show, or before pressing CTLR SPACE to complete etc.

**Comment by dsyme** [comment]
Closing old discussion
