### ISSUE TITLE
Get types available at current scope

### ISSUE THREAD

**Issue by OkayX6** [fsharp/FSharp.Compiler.Service#144]
Hi,

I don't know if it's difficult to do, but it'd be great to have something similar to ``GetDeclarationsAlternate`` https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fsi#L173 (that is used in intellisense), but that returns a list of ``FSharpSymbol`` instead.

It would make it easier to implement these code generation helpers:
* http://vfpt.uservoice.com/forums/247560-general/suggestions/5802615-generate-stubs-for-record-types
* http://vfpt.uservoice.com/forums/247560-general/suggestions/5802613-generate-all-match-cases-for-union-types

We would filter them by let say, union types, record types...

Otherwise, we have to rely on syntax tricks so that the type inference can guess the type, and sometimes its clumsy (like there where I have to give hints to the type inference: https://github.com/fsprojects/VisualFSharpPowerTools/pull/365)

Thanks!

**Comment by 7sharp9** [comment]
Recently I added ```GetDeclarationSymbols```, I think the symbol API needs to be augmented for this type of operation too.

**Comment by dungpa** [comment]
There is a lot of redundancies in results from `GetDeclarationSymbols`.How can we filter them in a sensible way?

**Comment by 7sharp9** [comment]
It uses the same filter as ```GetDeclarations``` so they should match, to get more specific I guess a better ident island.

**Comment by dsyme** [comment]
@7sharp9 implemented this in #281 and others
