### ISSUE TITLE
Return unresolved symbols for resolving missing open statements

### ISSUE THREAD

**Issue by dungpa** [fsharp/FSharp.Compiler.Service#145]
This feature is popularly requested in VS and XS. See:
- http://vfpt.uservoice.com/forums/247560-general/suggestions/5784677-resolve-unopend-namespace-or-module
- http://fsharpbinding.uservoice.com/forums/230931-general/suggestions/5004996-add-missing-open-declarations

**Comment by vasily-kirichenko** [comment]
The feature "resolve missing open statements" has been implemented in VFTP, XS and later in VFT and has worked great. Closing it.
