### ISSUE TITLE
Cannot distinguish custom numeric literals usages from ordinary modules and function invocations

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#147]
``` fsharp
module NumericLiteralZ = 
    let FromInt32 (i: int) = i
let _ = 77Z
```

FCS returns two symbols for `77Z`: 

a module

![image](https://cloud.githubusercontent.com/assets/873919/3036811/a464ec36-e0b3-11e3-9021-55e83e421c45.png)

and a function invocation

![image](https://cloud.githubusercontent.com/assets/873919/3036831/ef93ffc6-e0b3-11e3-86e1-fa6aaed7195a.png)

from which we cannot distinguish numeric literal from ordinary module / function. 
FCS behaves the same for `BitInteger`, too.

Related issue in VFPT https://github.com/fsprojects/VisualFSharpPowerTools/issues/432

**Comment by vasily-kirichenko** [comment]
It's still reproduced on current VFT master:

![image](https://cloud.githubusercontent.com/assets/873919/25556659/e37e9e90-2d08-11e7-92aa-85185463a8cb.png)

**Comment by dsyme** [comment]
Spring cleaning old feature requests and suggestions in preparation for repo unification
