### ISSUE TITLE
GetUsesOfSymbol does not return usage of default constructor

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#176]
```fsharp
type internal Class1() = class end
let _ = Class1()
```
For default constructor `checker.ParseAndCheckProject().GetUsesOfSymbol()` returns single `FSharpUse` instead of two:

![image](https://cloud.githubusercontent.com/assets/873919/3488684/dc9b67c6-04fb-11e4-845c-2869e6c25988.png)

I expect both 'Class1' symbols be considered as constructors (declaration and usage).

**Comment by dsyme** [comment]
I checked, this is fixed somewhere along the way
