### ISSUE TITLE
API suggestion for GetDeclarations, GetToolTipTextAlternate, etc.

### ISSUE THREAD

**Issue by prosconi** [fsharp/FSharp.Compiler.Service#179]
Currently the API requires that a list of identifier names be sent to the compiler services in order to get a list of declarations, tooltips, methods, etc. Example:

Code being worked on

``` fsharp
let x = ...
x.y.z.
```

Intellisense code

``` fsharp
// Get declarations (autocomplete) for a location
let decls = 
    checkFileResults.GetDeclarationsAlternate
      (Some parseFileResults, 2, 6, inputLines.[1], ["x"; "y"; "z"], "")
    |> Async.RunSynchronously
```

It would be nice if the API would just figure out the names ["x"; "y"; "z"]

**Comment by dsyme** [comment]
Closing old feature request - we don't need to track these as we will gradually improve the API
