### ISSUE TITLE
Internal exception FileNameNotResolved is thrown by FCS

### ISSUE THREAD

**Issue by petersondrew** [fsharp/FSharp.Compiler.Service#186]
When a non-existent file is passed to FCS, a FileNameNotResolved exception is thrown which is declared [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/build.fsi#L150) in the Microsoft.FSharp.Compiler.Build module which is marked internal.

**Comment by dsyme** [comment]
Closing as no repro submitted
