### ISSUE TITLE
Where did Powerpack's Metadata namespace go?

### ISSUE THREAD

**Issue by kurtschelfthout** [fsharp/FSharp.Compiler.Service#187]
It used to be in this project...right? It seems most of the types are still there, but I'm having a hard time getting my hands on an FSharpAssembly instance (it used to have a Load static method).

Or what's the story for parsing metadata in compiled assemblies? The Powerpack page refers to here.

Thanks!

**Comment by dmitry-a-morozov** [comment]
I thinking of ways to support units of measure in FSharp.Data.SqlClient. Seems like I need logic that check if a type is UoM.  Something along these lines
http://stackoverflow.com/questions/4005474/reflection-for-f-units-of-measure/4005908#4005908
Do I have to go thru all complexity shown in @7sharp9 snippet? // @fsgit @vladima

**Comment by matthid** [comment]
@dmitry-a-morozov I have come across this limitation as well and created https://github.com/matthid/Yaaf.FSharp.Scripting/ which adds the FromAssembly methods (from your stackoverflow link) as extension methods. But basically I'm doing exactly what @7sharp9 has shown above (behind the scenes).

I planned to discuss this here on FSharp.Compiler.Service once I'm happy with the API.

**Comment by dmitry-a-morozov** [comment]
Cool. I'll keep watching progress on this issue.

**Comment by 7sharp9** [comment]
It's really heavy weight to get the information that way, we could do with a direct method of doing this.  Latency of the current method can be 5 or more seconds. :-(

**Comment by matthid** [comment]
In my tests it's only slow the first time, if you re-use the checker instance the it's kind of OK. But you are right the initial delay is a pain. 

One more Note: Before starting my scripting project from above I tried to implement a more direct approach in FCS, but I failed as it seems to be a lot more difficult as one might assume, so it may take some time until we get that functionality back (if ever). I hope I'm wrong on this one though...

**Comment by dsyme** [comment]
@dmitry-a-morozov - 

For the Freebase type provider prototype, we managed to support UoM in limited forms of queries pretty reasonably - we had information of the units of columns, and propagated that up through both type system and query translation.  But it was a thorny, and relied on the specialized shapes of operations permitted in queries, would have been much easier with full reflective information.

I do wonder if it should be possible in F# to ask for normalized reflective info of UoM parameters which are "ground".  This would mean that FSharp.Core would have something like this:

    val inline unitof< [<Measure>] ^u > : System.Type

Which would allow

    unitof<kg*kg>
    unitof<m*m/m>  // same as unitof<m>

That in itself would be useful. Of course you still don't unit information in quotations for queries or attached to System.Type for, say, ``float<kg>``.  But it is a start and may be enough that you could build an entirely new set of "unitized" query builder and query operations.

This line of thinking should probably be added to http://fslang.uservoice.com (I haven't done that, but feel free to do so).

**Comment by 7sharp9** [comment]
@matthid It would be nice to get a sane way of retrieving a compiled F# dlls metadata, Im currently doing the same as we discussed about with my soothsayer tool which displays the signatures from an F# dll for tooling etc.

**Comment by dsyme** [comment]
Closing old feature request
