### ISSUE TITLE
FsiEvaluationSession.EvalExpression exception and error handling

### ISSUE THREAD

**Issue by ghost** [fsharp/FSharp.Compiler.Service#19]
EvalExpression and EvalInteraction need to have better specified exception behaviour

- Return ErrorInfo[]  for warnings and errors from parsing and typechecking
- Directly raise exceptions from execution (preferably without losing the callstack)

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/FSharp.Compiler.Service/pull/475
