### ISSUE TITLE
How to send code from host proces to FCS?

### ISSUE THREAD

**Issue by forki** [fsharp/FSharp.Compiler.Service#195]
In Paket we want to evaluate a DSL with FCS. In order to do so we want to start a session and give it some inital code (withj DSL helpers). Then we run the script which uses the DSL and in the end we retrieve a result from the session. You can see a prototype at https://github.com/fsprojects/Paket/blob/master/src/Paket/ConfigDSL.fs#L38

The initial DSL helpers are defined at https://github.com/fsprojects/Paket/blob/master/src/Paket/ConfigDSL.fs#L14. I think there should be an easier way to do this. Ideally I'd like to write "normal" F# code and pass it to the session. 

I thought about using ReflectedDefinition attribute and quotations but then I didn't found an easy way to serialize these back to F# code. I could also put the code into a new .fsx file and let the FCS session evaluate the file, but then I'd have to make sure it's deployed with the Paket.dll (maybe as a resource?)

What do you think is the best approach for this?

**Comment by dsyme** [comment]
Closing this since it's quite old

**Comment by forki** [comment]
Yes and we decided to not use FCS in paket ;-)
