### ISSUE TITLE
Do not require FSharp.Compiler.Interactive.Settings.dll

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#199]
The file is not included with the FCS, but creating `FsiEvaluationSession` requires it (sometimes), which causes issues in F# Data: https://github.com/fsharp/FSharp.Data/issues/587

We should either include the file, or not require it...

**Comment by matthid** [comment]
I did run in the same problem and it seems to disappear after setting `useFsiAuxLib` to `false` in https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L2706.
Maybe `false` should be the default when a custom object is given?

**Comment by tpetricek** [comment]
I just hit this issue again. I can workaround this by passing `false` to `useFsiAuxLib`, but then the evaluation session does not have access to the `fsi` object (even when I pass my own implementation to `GetDefaultConfiguration`). And this will break various things in FsLab. See [the F# Formatting code for this...](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Literate/Evaluator.fs#L122).

I don't see why the DLL is needed when I pass my own implementation of the `fsi` object...

**Comment by nosami** [comment]
I just encountered this issue. On mono, I can pass in `Settings.fsi` as the fsi object without referencing the dll and everything works.

On Windows, I get the error that the FSharp.Compiler.Interactive.Settings.dll can't be found.

If I pass a custom object in and pass `true` for `useFsiAuxLib`, I still get the error. 

I want the `fsi` object to be available.

**Comment by nosami** [comment]
I've referenced it like this for now, but not sure how valid this is

```
    <Reference Include="FSharp.Compiler.Interactive.Settings">
      <!-- MSBuild takes the last HintPath that exists -->
      <HintPath Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll')">$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll</HintPath>
      <HintPath Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll')">$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll</HintPath>
      <HintPath Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.0\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll')">$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\FSharp.Compiler.Interactive.Settings.dll</HintPath>
    </Reference>
```

**Comment by nosami** [comment]
```
    <Reference Include="FSharp.Compiler.Interactive.Settings"/>
```

This works too.

**Comment by dsyme** [comment]
My understanding is that this was fixed a while back
