### ISSUE TITLE
InteractiveChecker should include context of file invalidation

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#204]
When the InteractiveChecker fires the dirty notification `BeforeBackgroundFileCheck` there is no indication of the context, e.g. was this file invalidated because of a TypeProvider invalidation or a general invalidation due to a File being type checked.

This context is important because if you have asked for a file to be type checked `CheckFileInProject` you probably don't want to act on the dirty notify event as you will have already consumed the results.  We get this in the F# addin which results in each file being processed twice on each change in the editor when there is actually only one change.

**Comment by 7sharp9** [comment]
@dsyme Would you want a new function that has a context associated with it or modify BeforeBackgroundFileCheck to have one?

The context would just be whether the notification is coming from a type provider invalidation or not

**Comment by dsyme** [comment]
Spring cleaning old feature requests and suggestions in preparation for unifying this repo with visualfsharp
