### ISSUE TITLE
GetReferencedAssemblies() returns two different entries for Unquote assembly

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#224]
Minimal repro project https://github.com/vasily-kirichenko/fcs-unquote-bug

`ParseAndCheckResults.ProjectContext.GetReferencedAssemblies` returns duplicated entry for `Unquote.dll`:

![image](https://cloud.githubusercontent.com/assets/873919/4334677/1d158882-3ff2-11e4-9dda-787c35bf901b.png)

VFPT cache entities by assembly full path. As a result:

* the first referenced `Unquote` actually contains strange top-level entities:

![image](https://cloud.githubusercontent.com/assets/873919/4334835/a24fd870-3ff4-11e4-9f6c-c1b196d7dc50.png)

from which we cannot get any leaf entities, and cache this empty list.

* the second referenced `Unquote` has identical path, so we do not get entities from it, however it seems it contains proper ones:

![image](https://cloud.githubusercontent.com/assets/873919/4334877/29ab9dea-3ff5-11e4-9e20-43e0a3dd34e5.png)

As a final result, we cannot determine that open statements are not redundant https://github.com/fsprojects/VisualFSharpPowerTools/issues/712

**Comment by stephen-swensen** [comment]
FYI - as of version 3.0.0, Unquote no longer uses static linking

**Comment by dsyme** [comment]
OK, thanks. Closing this as it is a very rare case, let's reopen if we see it again in the wild.
