### ISSUE TITLE
Compilation crashes if pdb is enabled using a shimmed file-system

### ISSUE THREAD

**Issue by Alxandr** [fsharp/FSharp.Compiler.Service#270]
The writing of the PDB does not apparently go through the shimmed file system. There's a request to delete the PDB file, but after that, the process just crashes.

The exception is the following: `Unexpected error creating debug information file 'G:\GitHub\YoloDev.FSharp.AspNet\test\YoloDev.FSharp.AspNet.Test\YoloDev.FSharp.AspNet.Test.pdb'`

**Comment by Alxandr** [comment]
@dsyme this too looks like wrong issue being closed by commit.

**Comment by dungpa** [comment]
Reopening due to wrong auto-closing.
