### ISSUE TITLE
Strongly name assembly

### ISSUE THREAD

**Issue by duckmatt** [fsharp/FSharp.Compiler.Service#274]
Are there any plans to strongly name the assembly on nuget?

The problem I'm having is that MSBuild tasks and visual studio extensions appear to getting run in the same application domain, so when an extension has already loaded `FSharp.Compiler.Service.dll` my task ends up trying to use that loaded assembly regardless as to whether it's an older or more recent version. I've gotten around this by building my own strongly named `FSharp.Compiler.Service.dll`, but it would be good if I could be grabbing it off nuget instead.

**Comment by dsyme** [comment]
Hi @duckmatt  - there are no current plans to do this, we would just recommend doing as you have done and having a custom build.  If you want to add the relevant targets to build.fsx that would be useful.
