### ISSUE TITLE
EvalInteraction only returns results for the last unbound 'it' variable

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#280]
In the screenshot below you can see than unbound variables are always hidden apart from the last instance:

![screen shot 2014-12-02 at 08 44 03](https://cloud.githubusercontent.com/assets/588746/5262636/ee88c714-7a1f-11e4-9c0a-056bbf426e08.png)

Note: Eval interaction does return unit, but it drives the notification of 'it' variables via the print formatters and the  `OnEvaluation` event of the `FsiEvaluationSessionHostConfig`

**Comment by 7sharp9** [comment]
I would love all the unbound variables to be available ...

**Comment by 7sharp9** [comment]
@dsyme Is the above commit really fixing 280?  Doesn't look like it to me, for a moment I was excited to have this for an outstanding issue in F# sketches.

**Comment by dsyme** [comment]
No, it's not related (GitHub may be adding the "reference" because of the integration of a commit referencing a #280 in a different repo like fsharp/fsharp or Microsoft/visualfsharp?)

**Comment by 7sharp9** [comment]
@dsyme Previously when we talked about this you said it should be easy to add, any pointers?

**Comment by dsyme** [comment]
In ``EvalParsedDefinitions``, iterate all the ``declaredImpls`` (using code similar to that in ``Exprs.fs``) to find all the declared ValRef's.  Then use this to print the values:
```
             if not tcConfig.noFeedback then 
                 valuePrinter.InvokeExprPrinter (istate.tcState.TcEnvFromImpls.DisplayEnv, istate.emEnv, istate.ilxGenerator, vref.Deref)
``` 
or this to get the values as ``FsiValue`` objects:
```             
             let optValue = istate.ilxGenerator.LookupGeneratedValue(valuePrinter.GetEvaluationContext(istate.emEnv), vref.Deref);
             match optValue with
             | Some (res, typ) -> Some(FsiValue(res, typ))
             | _ -> None
```

**Comment by 7sharp9** [comment]
Do you not see this as useful for the future now @dsyme ?

**Comment by dsyme** [comment]
Is https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fsi#L71 sufficient functionality for this?
