### ISSUE TITLE
Is there a way to tell where a symbol used in an expression came from?

### ISSUE THREAD

**Issue by ericsink** [fsharp/FSharp.Compiler.Service#288]
Question, possibly a dumb one:

I'm investigating the idea of using FSharp.Compiler.Service to build a tool which could be used to analyze closures.

Given this code:

    let outerFunc a =
        let b = 2
        let fn c =
            let d = 3
            a + b + c + d
        fn 1

When I use a visitor on the expression "a + b + c + d", I would like to be able to distinguish, for example, that c is a parameter to fn (the function I'm in now) but b was bound outside of fn, therefore fn is a closure.

I can't find anything in FSharpMemberOrFunctionValue which would give me the information I'm looking for.  Am I looking in the wrong place?

Thanks!

**Comment by 7sharp9** [comment]
Not really, you can determine that its a closure or nested function via the following convoluted method of elimination:

*   If its **not** a constructor *(name starts with '.ctor')*
*   Its `FullType` property `Isfunctiontype` is true but **not** `IsPropertygetter` or `IsPropertysetter`
*   Its not an operator or active pattern *(Its name starts with '(')*
*   The property IsModuleValueOrMember is **false** 

Then its a closure or nested function.  

This is one area where the API really could be cleaned up, getting this info is like pulling teeth.  Both VFPT and the FSB have some active patterns around detecting these things.  A standard set of patterns to operate correctly over the symbols would be a great addition.  Alternatively additional type could be added as subclasses of symbol and then a simple type pattern match would suffice.

**Comment by dungpa** [comment]
@ericsink There is no such information from `FSharpMemberOrFunctionValue`. But there is now typed ASTs exposed via a set of active patterns, which are suitable to use in closure analysis (see e.g. http://fsharp.github.io/FSharp.Compiler.Service/typedtree.html#Walking-over-expressions).

**Comment by 7sharp9** [comment]
@dungpa Thats only available on a full project analysis isn't it?  I wanted to take advantage of that for something but at the point I wanted to use it I only had a types parsed result for a single file.

**Comment by fsgit** [comment]
Closing, see @dungpa's comment
