### ISSUE TITLE
Lexer - cannot distinguish between failure and end of line

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#291]
If you try to tokenize a line that has an error:

```
let sourceTok = SourceTokenizer([], "/some/file.fsx")
let ugly = "✘ let add I J = I+J"
let tokenizer = sourceTok.CreateLineTokenizer(ugly)
```

Then the tokenizer returns `None` on the first `ScanToken` call. This normally indicates an end of file, so there is no way to find out when there is an error and continue tokenization.

We should change the API to provide `TryScanToken` that returns a three-case discriminated union with `Token of token | Error of token | EndOfLine`. The change should probably be done here: https://github.com/fsharp/FSharp.Compiler.Service/blob/3b25143755658728e0445a90f58e750bb64a64ff/src/fsharp/vs/ServiceLexing.fs#L607

**Comment by dsyme** [comment]
Spring cleaning old suggestion issues (and I think this has been fixed)
