### ISSUE TITLE
Document that FsiEvaluationSession ignore shadowcopyreferences

### ISSUE THREAD

**Issue by xkrt** [fsharp/FSharp.Compiler.Service#292]
Hi, looks like FsiEvaluationSession ignores --shadowcopyreferences option.

```fsharp
open System
open System.IO
open Microsoft.FSharp.Compiler.Interactive.Shell

[<EntryPoint>]
let main argv =
    let config = FsiEvaluationSession.GetDefaultConfiguration()
    let commonOptions = [| "fsi.exe"; "--noninteractive"; "--shadowcopyreferences" |]

    let sbOut = Text.StringBuilder()
    let sbErr = Text.StringBuilder()
    use outStream = new StringWriter(sbOut)
    use errStream = new StringWriter(sbErr)
    use stdin = new StreamReader(Stream.Null)

    let session = FsiEvaluationSession.Create(config, commonOptions, stdin, outStream, errStream)
    session.EvalScript "script.fsx"
    0
```

script.fsx:
```fsharp
printfn "AppDomain.CurrentDomain.ShadowCopyFiles = %b" System.AppDomain.CurrentDomain.ShadowCopyFiles
```

Output:
```
AppDomain.CurrentDomain.ShadowCopyFiles = false
```

But if I run script.fsx with fsi.exe:
```
fsi.exe --shadowcopyreferences script.fsx
```

Output will be:
```
AppDomain.CurrentDomain.ShadowCopyFiles = true
```

**Comment by matthid** [comment]
I think the reason is because `FsiEvaluationSession` runs in the current AppDomain and it can't change that property (see also [this Stackoverflow quesiton](http://stackoverflow.com/questions/12513655/what-is-the-right-way-to-set-shadow-copying-for-the-default-appdomain)).

**Comment by vasily-kirichenko** [comment]
This behavior causes assembly locking by Fake.Deploy, which is a critical limitation for our team.

Is it possible to create a distinct domain, execute script in it then unload it? 

/cc @forki @sergey-tihon

**Comment by xkrt** [comment]
Actually we have that problem:
```fsharp
open System
open System.IO
open Microsoft.FSharp.Compiler.Interactive.Shell

[<EntryPoint>]
let main argv =
    let config = FsiEvaluationSession.GetDefaultConfiguration()
    let commonOptions = [| "fsi.exe"; "--shadowcopyreferences" |]

    let sbOut = Text.StringBuilder()
    let sbErr = Text.StringBuilder()
    use outStream = new StringWriter(sbOut)
    use errStream = new StringWriter(sbErr)
    use stdin = new StreamReader(Stream.Null)

    try
        using
            (FsiEvaluationSession.Create(config, commonOptions, stdin, outStream, errStream))
            (fun s -> s.EvalScript "script.fsx")
    with
    | e -> printfn "script err: %O" sbErr
    0
```

script.fsx
```fsharp
#r "Lib.dll"

printfn "Lib.dll exist = %b" (System.IO.File.Exists("Lib.dll"))

try
    System.IO.File.Delete("Lib.dll")
with
| e -> printfn "ERROR: %O" e

printfn "Lib.dll exist = %b" (System.IO.File.Exists("Lib.dll"))
```

Output:
```
Lib.dll exist = true
ERROR: System.UnauthorizedAccessException: Access to the path 'c:\temp\FCSTest\F
CSTest\bin\Debug\Lib.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at <StartupCode$FSI_0001>.$FSI_0001_Script$fsx.main@() in c:\temp\FCSTest\FCS
Test\bin\Debug\script.fsx:line 6
Lib.dll exist = true
```

But
```
fsi.exe --shadowcopyreferences script.fsx
```

Output:
```
Lib.dll exist = true
Lib.dll exist = false
```

fsi.exe executes script in different AppDomain?

**Comment by 7sharp9** [comment]
Typically its in a different process, with commands sent with a stream.

**Comment by forki** [comment]
http://fsharp.github.io/FSharp.Compiler.Service/interactive.html#Starting-the-F-interactive <- that's in-process right?

**Comment by 7sharp9** [comment]
@forki Yeah that is, I just saw fsi.exe mentioned which is typically a different one.  e.g. the interactive window in XS/VS is a different process.

**Comment by forki** [comment]
yes. since FAKE 3.0 we hosted the FSi in process. This was a good the decision for Fake.exe - not so much for Fake.Deploy.exe

**Comment by 7sharp9** [comment]
In proces can be dangerous, theres no memory limitation and it will keep allocating the dynamic assy on each iteration etc.

**Comment by 7sharp9** [comment]
In Xamarin Sketches will kill the Interactive session on each evaluation, otherwise eventually ...  OOM.

**Comment by vasily-kirichenko** [comment]
Hmm. It seems it's better to revert the implementation which calls `fsi.exe`? What do you guys think?

**Comment by forki** [comment]
yep. that sounds best. Sorry for the trouble.

But unfortunately I'm not available for two weeks. If anyone can help and send a PR, I'll merge and release.

**Comment by dsyme** [comment]
We should probably continue the discussion at the FAKE project.

**Comment by dsyme** [comment]
(and document that the shadow-copy flag is ignored by FCS)
