### ISSUE TITLE
Is there a way to get assembly references from a FSharpSymbolUse?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#295]
Is there a way to get assembly references from a FSharpSymbolUse?

If not how could this be added?  Im willing to cut the code.

**Comment by 7sharp9** [comment]
Perhaps adding `ReferencedAssemblies` property to `FSharpAssembly` ?

I think the underlying data is in tcImports.CcuTabl` or `DllTable`	`Microsoft.FSharp.Collections.FSharpMap<string,Microsoft.FSharp.Compiler.Build.ImportedAssembly>`

Along the right track?

**Comment by dsyme** [comment]
Not currently. Do you mean "all the assemblies that were referenced in the compilation/typecheck that generated the FSharpSymbol"? If so, the assembly references would have been available in the FSharpProjectContext for that compilation/typecheck, e.g. https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fsi#L95

**Comment by 7sharp9** [comment]
Problem is that info might be disjoint from the location the symbol was retrieved from.  Like when you get the symbol under the caret.  E.g I don't have access to the project context.

**Comment by dsyme** [comment]
What do you need the info for?

**Comment by 7sharp9** [comment]
Roslyn symbol construction, I no longer have access to the ProjectContent info from XS that has this information, so I need to get it from the F# compiler instead.

**Comment by dsyme** [comment]
I see, thanks. Please send a link to the relevant part of the Roslyn interface set if you can

**Comment by 7sharp9** [comment]
Essentially here:
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Symbols/IModuleSymbol.cs,41d20718fa2ae32c,references

An `ISymbol` has an `IModule`, which has a `ReferencedAssemblies` propertly

**Comment by dsyme** [comment]
It seems reasonable to add this.  Let us know if/when you find a place where this is critical.

**Comment by dsyme** [comment]
Spring cleaning old feature requests and suggestions in preparation for repo unification
