### ISSUE TITLE
How to represent Roslyn symbols from F# symbols

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#299]
Im opening this to discuss how we can represent the roslyn symbols from our F# symbols.

In FCS we have the following symbols:

``` fsharp
FSharpMemberOrFunctionOrValue
FSharpUnionCase
FSharpEntity
FSharpField
FSharpGenericParameter
FSharpActivePatternCase
FSharpParameter
FSharpStaticParameter
```

Do we want to expand these so that they more closely match what would be available in Roslyn for easier interop.  We treat module and namespaces as `FSharpEntities` which I think matches the representation elsewhere in the API.

Roslyn has a lot more symbols.

``` csharp
IAliasSymbol
IAssemblySymbol
IEventSymbol
IFieldSymbol
ILabelSymbol
ILocalSymbol
IMethodSymbol
IModuleSymbol
INamespaceOrTypeSymbol
IParameterSymbol
IPreProcessorSymbol
IPropertySymbol
IRangeVariableSymbol
```

Those are just the core interfaces that inherit from `ISymbol`, for each of those interfaces there are numerous other subclasses.  i.e. INamespaceOrType`is implemented by`AssemblySymbol`which has subclasses`MissingAssemblySymbol`and`NonMissingAssemblySymbol`, which intern also have subclasses.

From a quick glance we could make FCS return finer grained symbol which would make matching the symbols easier, but there are other things like preprocessor symbols which are not available in FCS.  

My preference would be to expand the range of symbols as Ive always found the symbol API in FCS to be too coarse.

Thoughts?

**Comment by 7sharp9** [comment]
See here for the fat interface that we will have to adhere to, you can also see the need for an `Immutable collection module` for F#:

https://github.com/fsharp/fsharpbinding/commit/3b4eadd2c48eb0be865efb6d3214cf268c2b9b23

**Comment by dsyme** [comment]
Certainly we need to make sure there is enough _information_ in the Symbols to allow the implementation of the Roslyn API

However I don't think the Roslyn bridge should be the driving function for changing the FCS symbols - for example FCS needs more things like ActivePatternCase, and in some cases there may not be a good match with Roslyn. FCS is quite coarse but that has some advantages too.

So I think we shouldn't try to match Rosyln directly but rather make sure the bridge is buildable (and actually build it, as you're doing :) )

**Comment by 7sharp9** [comment]
As I investigate more I seem to move further from a bridge as lots of Roslyn is internal.  

It might be more feasible to build some Roslyn functionality as a mirror of some of their static classes, although Im not sure what this would achieve apart from tool developers being able to move between, for example, the Roslyn `SymbolFinder` and the F# `SymbolFinder module`.

As an Example a Roslyn Location has a default constructor with no property getters and no way to set the metadata apart from the internal constructors.  Lots of areas require a full tree of roslyn symbols and semantics, thats just too big to approach without a lot of research.
