### ISSUE TITLE
No FSharpSymbolUse for single case union type

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#301]
```fsharp
type DU = Case
```
`FSharpCheckFileResult.GetAllUsesOfAllSymbolsInFile()` return a `FSharpSymbolUse` for `DU` and for the implicit module, but not for `Case`. As a result, VFPT cannot colorize `Case` as pattern. 
See https://github.com/fsprojects/VisualFSharpPowerTools/issues/934

**Comment by dsyme** [comment]
I think adding

                    writeFakeUnionCtorsToSink [ unionCase ]

here:
                | TyconCoreAbbrevThatIsReallyAUnion (hasMeasureAttr,envinner,id) (unionCaseName,_) ->
                    structLayoutAttributeCheck(false)
                    noAllowNullLiteralAttributeCheck()
                    TcRecdUnionAndEnumDeclarations.CheckUnionCaseName  cenv unionCaseName.idText unionCaseName.idRange
                    let unionCase = NewUnionCase unionCaseName unionCaseName.idText [] thisTy [] XmlDoc.Empty tycon.Accessibility
                    writeFakeUnionCtorsToSink [ unionCase ]
                    MakeUnionRepr [ unionCase ], None, NoSafeInitInfo

in tc.fs will fix this.

@vasily-kirichenko  - do you think you could you take a look and submit a PR with tests?

Thanks
don

**Comment by vasily-kirichenko** [comment]
@dsyme done https://github.com/fsharp/FSharp.Compiler.Service/pull/308 
thanks!
