### ISSUE TITLE
Can we have the equivalent of SyntaxTrivia available?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#302]
Roslyn has a concept of SyntaxTrivia
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFactory.cs,bf85e0e8cd4f2c91

Which would be things like preprocessor directive, comments, disabled code.

I know there is something similar in Fantomas for merging comments back into the AST, .aving that and the preprocessor and whether the code is disabled would make working with the Roslyn stuff more palatable, at the moment its not.

**Comment by dsyme** [comment]
In principle, yes.  But it would need to be added, I'm not sure what the forcing function would be beside the need to bridge to Roslyn?

**Comment by 7sharp9** [comment]
Semantic highlighting for instance would be able to query the symbols trivia to get an associated comment or compiler directive.

**Comment by 7sharp9** [comment]
In essence this request makes tooling easier to build not to be more roslyn like for the sake of it.

VFPT has an outstanding issue where they cant add comments back into the main AST because it is too slow to do so.

**Comment by smoothdeveloper** [comment]
Mentionning this issue which deals with processing comments in the IDE: https://github.com/fsprojects/VisualFSharpPowerTools/issues/1492

**Comment by 7sharp9** [comment]
closing old issue
