### ISSUE TITLE
Can the Range types in the compiler be updated to include the offsets in the code?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#303]
In Roslyn every symbol work with offsets rather than line,column.  This means that any form of Roslyn interop needs to convert F# Range's into offsets, this means that every symbol must go through the test to work out the offsets.  If these were available then working with Roslyn would be less painful.

See http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Text/TextSpan.cs,375a09d5e3906265

This is either an offsetStart/Length or offsetStart/offsetEnd

**Comment by dsyme** [comment]
This is tricky.  The range struct is a bit performance critical.  Did you find a workaround for this for the Roslyn bridge?

**Comment by 7sharp9** [comment]
Not really, every time I need an offset I create a readonly editor from the file, then calculate the offset:
```
let startOffset = editor.LocationToOffset(range.StartLine, range.StartColumn)
let endOffset = editor.LocationToOffset(range.EndLine, range.EndColumn)
```

I can imagine this is quite a performance hit, Roslyn seems to use offsets throughout rather than line, col.

**Comment by 7sharp9** [comment]
not important, just rossy consistency
