### ISSUE TITLE
Internal modules shown as 'not accessible' to external ones in the interactive checker

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#304]
This is referencing bugzilla issue: https://bugzilla.xamarin.com/show_bug.cgi?id=27284

reference code.

For the following library:
```fsharp
namespace SharedModule

module internal Shared =
    type Class1() = 
        member this.X = "F#"

[<assembly:System.Runtime.CompilerServices.InternalsVisibleTo("TheConsole")>]
()
```

And the following Console App named "TheConsole":
```fsharp
[<EntryPoint>]
let main argv = 
    let x = SharedModule.Shared.Class1()
    printfn "%A" x.X
    0 // return an integer exit code
```
- - - 
There are errors are coming from the
InteractiveChecker, its somehow not aware of the InternalsVisible to attribute in the referenced dll.

The attributes passed to FCS seem to be correct but the following errors are
returned from the InteractiveChecker

[0]    {/Users/dave/Projects/SharedModule/TheConsole/Program.fs (6,26)-(6,32)
typecheck error The type 'Shared' is not accessible from this code location}    

[1]    {/Users/dave/Projects/SharedModule/TheConsole/Program.fs (6,13)-(6,41)
typecheck error The member or object constructor 'Class1' is not accessible.
Private members may only be accessed from within the declaring type. Protected
members may only be accessed from an extending type and cannot be accessed from
inner lambda expressions.}    

[2]    {/Users/dave/Projects/SharedModule/TheConsole/Program.fs (7,18)-(7,21)
typecheck error Lookup on object of indeterminate type based on information
prior to this program point. A type annotation may be needed prior to this
program point to constrain the type of the object. This may allow the lookup to
be resolved.}

**Comment by 7sharp9** [comment]
Checker options for reference:
```
Files: 
/Users/dave/Projects/SharedModule/TheConsole/AssemblyInfo.fs
/Users/dave/Projects/SharedModule/TheConsole/Program.fs

Options:
--noframework 
--debug+ 
--optimize- 
--tailcalls+ 
-r:/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.0/FSharp.Core.dll 
-r:/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.0/System.Core.dll 
-r:/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.0/System.Numerics.dll 
-r:/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.0/System.dll 
-r:/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.0/mscorlib.dll 
-r:/Users/dave/Projects/SharedModule/SharedModule/bin/Debug/SharedModule.dll
```

**Comment by dsyme** [comment]
Are you passing in "-o:TheConsole.exe"?  The assembly name will need to be known

**Comment by 7sharp9** [comment]
Ill check, if its needed then Ill add it downstream and close this.  If this is the issue then this might fix other strange potential issues...

**Comment by 7sharp9** [comment]
Hmm, I dont think it is or ever was, Ill update `generateCompilerOptions` and see what happens ...

**Comment by 7sharp9** [comment]
Indeed, `-o:<pathtoshared>` works when added to the checker args.

Thanks!
