### ISSUE TITLE
Could FSharpSymbols have a method like Roslyn's ToDisplayParts

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#305]
If we have a `ToDisplayParts` method _(or similar)_ it would make for closer interaction between F#'s symbols and Roslyns.

References:
[ISymbol](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Symbols/ISymbol.cs,97f37bb405289f6d,references)
[SymbolDisplayPart](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/SymbolDisplay/SymbolDisplayPart.cs,e62b13fcfb856a0b)

**Comment by dsyme** [comment]
Yes, I suppose it could :)

**Comment by 7sharp9** [comment]
closing old question.
