### ISSUE TITLE
DeclararionLocation=SignatureLocation for symbols from outside solution

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#306]
e.g. For List:

DeclarationLocation: 
`/private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-128f3bc/src/fsharp/FSharp.Core/list.fsi`

SignatureLocation: `/private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-128f3bc/src/fsharp/FSharp.Core/list.fsi`

Actually ImplementationLocation is the same: `/private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-128f3bc/src/fsharp/FSharp.Core/list.fsi`

This makes any goto declaration (**source** not signature) impossible from the symbols.

**Comment by dsyme** [comment]
It looks like this will always be the case for symbols coming from F# assemblies outside the solution.  I don't think there's an easy fix for that.

ImplementationLocation and SignatureLocation should work correctly for symbols inside the solution.

**Comment by 7sharp9** [comment]
Maybe switch the extension as a quick hack on externals (If the file exists)

**Comment by dsyme** [comment]
Yes, but what line number?

**Comment by 7sharp9** [comment]
Ah ...

**Comment by 7sharp9** [comment]
The way Im using these two properties is for goto definition, if there is both a `fs` and `fsi` then in the goto definition context menu you would get two choices shown:

*    myfile.fsi Line: 27
*    myFile.fs Line: 678

**Comment by 7sharp9** [comment]
closing as no easy fix etc
Soothsayer view works around this for me.
