### ISSUE TITLE
FSharpMemberOrFunctionOrValue.ReturnParameter throws exception when accessed from nested function symbol

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#307]
This needs to be similar to the recent CurriedParameterGroups PR that added in the missing information.

**Comment by vasily-kirichenko** [comment]
I'll update it when that PR is merged.

**Comment by 7sharp9** [comment]
It is merged :-)

**Comment by vasily-kirichenko** [comment]
I'm not sure I see how these two related. Frankly, I don't understand what's going on on this PR, I just added the line @dsyme told me :)

**Comment by 7sharp9** [comment]
Im confused, I thought you meant my PR that added the CurriedParameterGroup information for nested functions.

I can do it when I get a moment ...

**Comment by vasily-kirichenko** [comment]
OMG, I'm writing into a wrong issue :(

**Comment by 7sharp9** [comment]
:-)  You can still have a go at this if you want to.
