### ISSUE TITLE
Is it possible to retrieve a class-scoped function parent type?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#311]
This information seems to be missing, probably on purpose because of the spec. The information would be useful for code navigation and finding functions based on parentage.

**Comment by dsyme** [comment]
What do you mean by "nested function" - a lambda expression? a function defined in a class?

**Comment by 7sharp9** [comment]
A function defined in a class, like add here:
```fsharp
type Test() =
    let add = (+)
```

**Comment by jcansdale** [comment]
It appears that it is possible to retrieve a class-scoped function that takes parameters, but not one that doesn't. In the example below, only 'b' and 'c' are visible.

type Test() =
    let a = (+)
    let b() = (+)
    let c x = (+)

The following code:

module TypePropertyNoShow

open System
open System.IO
open Microsoft.FSharp.Compiler.SourceCodeServices

// Create an interactive checker instance 
let checker = FSharpChecker.Create(keepAssemblyContents=true)

let parseAndCheckSingleFile (input) = 
    let file = Path.ChangeExtension(System.IO.Path.GetTempFileName(),"fsx")  
    File.WriteAllText(file, input)
    // Get context representing a stand-alone (script) file
    let projOptions = 
        checker.GetProjectOptionsFromScript(file, input)
        |> Async.RunSynchronously
    let checkProjectResults = checker.ParseAndCheckProject(projOptions) |> Async.RunSynchronously
    let checkedFile = checkProjectResults.AssemblyContents.ImplementationFiles.[0]
    checkedFile

let rec printDecl prefix d = 
    match d with 
    | FSharpImplementationFileDeclaration.Entity (e,subDecls) -> 
        printfn "%sEntity %s (line:%i) was declared and contains %d sub-declarations" prefix e.FullName e.DeclarationLocation.StartLine subDecls.Length
        for subDecl in subDecls do 
            printDecl (prefix+"    ") subDecl
    | FSharpImplementationFileDeclaration.MemberOrFunctionOrValue(v,vs,e) -> 
        printfn "%sMember or function or value %s (line:%i) was declared method=%b" prefix v.FullName v.DeclarationLocation.StartLine v.FullType.IsFunctionType
    | FSharpImplementationFileDeclaration.InitAction(e) -> 
        printfn "%sA top-level expression was declared (line:%i)" prefix e.Range.StartLine

let printDecls(checkedFile:FSharpImplementationFileContents) =
    for d in checkedFile.Declarations do 
        printDecl "" d

let input = """
module Mod
type Test() =
    let add1 = (+)
    let add2() = (+)
"""
printDecls(parseAndCheckSingleFile input)


... returns ..


Entity Mod (line:2) was declared and contains 3 sub-declarations
    Entity Mod.Test (line:3) was declared and contains 0 sub-declarations
    Member or function or value Mod.Test.( .ctor ) (line:3) was declared method=true
    Member or function or value Mod.Test.add2 (line:5) was declared method=true

**Comment by dsyme** [comment]
F# will optimize "a" to a local in the constructor (this important detail is buried deep in the F# Language spec).  If you look at the body of the .ctor it should be there.

**Comment by 7sharp9** [comment]
But as such there will be no visible symbol representing it though?

**Comment by dsyme** [comment]
The editor services will report a FSharpMemberOrFunctionOrValue for the value. 

It's just not reported in the declared contents of the class via .Declarations as in the code above (because F# has decided it's actually part of the implicit .ctor)

**Comment by jcansdale** [comment]
If I change it to:

```
type Test() =
    let a = (+)
    let b() = a
```
it compiles down to...
(decompiled using Reflector)

```
[Serializable, CompilationMapping(SourceConstructFlags.ObjectType)]
public class Test
{
    // Fields
    internal FSharpFunc<int, FSharpFunc<int, int>> a;

    // Methods
    public Test() : this()
    {
        this.a = new MyModule.-ctor@12();
    }

    [CompilerGenerated]
    internal FSharpFunc<int, FSharpFunc<int, int>> b()
    {
        return this.a;
    }
}
```

and the output still doesn't contain the 'a' property...

```
Entity Mod (line:2) was declared and contains 3 sub-declarations
    Entity Mod.Test (line:3) was declared and contains 0 sub-declarations
    Member or function or value Mod.Test.( .ctor ) (line:3) was declared method=true
    Member or function or value Mod.Test.b (line:5) was declared method=true
```

Is this as expected?

**Comment by 7sharp9** [comment]
What I meant by the original question, was can I get the parent of the `add` `FSharpMemberOrFunctionOrValue` e.g. the FSharpSymbol for `Test` or at least the FSharpType

**Comment by dsyme** [comment]
@jcansdale - "a" is a field of the type, and it is initialized in the .ctor.  So I think you'll see an assignment to "a" in the expression for the .ctor

It is not ideal that you see this compiled form. The compilation of F# classes into fields+ctor+methods happens in the F# type checker (relatively early in the compilation).  It would be good to eventually modify FCS so that it optionally provides the declarative form, rather than the compiled form.

**Comment by jcansdale** [comment]
@dsyme - Ah, I see now. At first glance I thought "a" was a property.

It's actually the compiled form that I'm interested in. I'm using it to find the full name of the target source element before calling the method or evaluating the property.

My current challenge is finding the "scope" a function in the source. For example, say I have the following:

```
module MyMod
type Test() =
    let hello() =
        printfn "Hello, world!"
    let a = (+)

```

I want to be able to select the 'hello' *or* 'printfn' line and find the 'MyMod.Test.hello' method. It would be easy if targeting 'hello' was enough, but I want to be able to select anywhere in the function. Do you know if this function scope information is available anywhere? (i.e. the range of lines a particular function covers)

**Comment by dsyme** [comment]
@jcansdale - The Range property of the ``e`` value bound by ``FSharpImplementationFileDeclaration.MemberOrFunctionOrValue(v,vs,e)`` should give you the range of the body of the ``hello`` function.  Combining this with the range of the ``v`` gives a pretty decent approximation (it won't include the leading ``let`` though)

**Comment by jcansdale** [comment]
@dsyme Awesome, thanks! :)

I couldn't find an equivalent range on FSharpImplementationFileDeclaration.Entity. Will I need to infer this from the last MemberOrFunctionOrValue in the Entity?

**Comment by dsyme** [comment]
@jcansdale - yes, I suppose so.  Or submit a PR to add the functionality to FCS to propagate the full syntactic range information (i.e. from the AST syntax tree node into the TAST node and thus to the FCS symbol API)

**Comment by 7sharp9** [comment]
closing old question
