### ISSUE TITLE
source index not working since version 0.0.82

### ISSUE THREAD

**Issue by ctaggart** [fsharp/FSharp.Compiler.Service#312]
Details copied here from: https://github.com/fsprojects/VisualFSharpPowerTools/issues/201#issuecomment-76907106

---
So the bug is that the new indexes end up with `%%var2%%` when it is supposed to be just `%var2%`.

`pdbstr -r -s:srcsrv -p:packages\FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.pdb`

`SRCSRVTRG=https://raw.githubusercontent.com/fsharp/FSharp.Compiler.Service/ec0293a16d1efb75a8dde78f0b495759179ee9bb/%%var2%%`

This line hasn't changed in a long time:
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/build.fsx#L124

Whose machine is doing the builds where the output ends up being `C:\GitHub\fsharp\FSharp.Compiler.Service`? Why not build it on AppVeyor? Which compiler version is being used?

**Comment by 7sharp9** [comment]
Whoever does it, I think it probably just comes down to an easy build and deploy rather than anything else.

**Comment by dsyme** [comment]
There was a bug in Visual Studio 2013 RTM FSharp.Core 4.3.1.0 where printf on %% gave %% rather than %. The bug got fixed in Visual F# Tools 3.1.1 and 3.1.2 but I'd say these fixed version are not being used here.

**Comment by ctaggart** [comment]
Please run this build script `.\FAKE.exe .\BugHunt.fsx` on the machine used to do builds. I think the build machine may be using an old `fsi.exe`.

``` fsharp
#r "FakeLib.dll"
open Fake
module FSIHelper =
    let fsiVersion = lazy (System.Diagnostics.FileVersionInfo.GetVersionInfo FSIHelper.fsiPath).FileVersion
Target "BugHunt" <| fun _ ->
    printfn "fsiPath: %s" FSIHelper.fsiPath
    printfn "fsiVersion: %s" FSIHelper.fsiVersion.Value
RunTargetOrDefault "BugHunt"
```

**Comment by fsgit** [comment]
Have you tried updated version 0.0.86?

```
Shortened DependencyGraph for Target BugHunt:
<== BugHunt

The resulting target order is:
 - BugHunt
Starting Target: BugHunt
fsiPath: C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe
fsiVersion: 4.31.30815.0
Finished Target: BugHunt
```

**Comment by ctaggart** [comment]
Perfect. Version 0.0.86 works again! Thanks.

``` ps
nuget install fsharp.compiler.service
srctool -x .\FSharp.Compiler.Service.0.0.86\lib\net40\FSharp.Compiler.Service.dll
```
