### ISSUE TITLE
Question: GAC preferred over `-I:`?

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#313]
Is it known (ie. by design) that Assemblies seem to be loaded from the GAC, even when there is a newer version available in one of the included library directories (`-I:` parameter)?
I don't know if the F# Compiler does the same thing but I noticed this here on FCS first.

This was pretty unexpected to me. This means working builds or FCS applications can fail suddenly by installing an assembly to the GAC and therefore looks like a bug to me.

*Details:*
I initially noticed this because of FSharp.Formatting failing in travis on a library referencing EntityFramework.dll.
After several hours I managed to reproduce it in my branch:
 * Branch: https://github.com/matthid/FSharp.Compiler.Service/tree/entityFramework_error 
 * Previously working: https://travis-ci.org/matthid/FSharp.Compiler.Service/builds/53121683
 * Commit to make it fail: https://github.com/matthid/FSharp.Compiler.Service/commit/3ca05bbeb21d64507d9c5ae0bbddc56e55eac70f
 * Failing build: https://travis-ci.org/matthid/FSharp.Compiler.Service/builds/53126218

The only difference I could figure out was that mono bundles an outdated EntityFramework.dll in the GAC. I could however not reproduce this on windows. I tried installing the mono EntityFramework into the GAC with
```
C:\Windows\system32>sn -Vr "C:\Program Files (x86)\Mono\lib\mono\4.5\EntityFramework.dll"
C:\Windows\system32>gacutil.exe /if "C:\Program Files (x86)\Mono\lib\mono\4.5\EntityFramework.dll"
```
But it doesn't seems to be picked up. Maybe the windows GAC is just more strict about this? Or this bug is mono/linux only? Or a bug in the mono GAC implementation?

Can somebody shed some light over this? Thank you.

**Comment by 7sharp9** [comment]
The reference resolution in F# is a bit different on mono than in Windows, it could be an issue there.

There are some ```if mono`` segments in the compiler code.  Ive mentioned that they needed reviewing a few times as mono has implemented more and more msbuild functionality over the last few years.

**Comment by 7sharp9** [comment]
For example:

https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/fsharp/ReferenceResolution.fs#L161

but this does exist in mono:

https://github.com/mono/mono/blob/e478ab8364989468dc6627387dc213b2ebbb2763/mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolLocationHelper.cs#L119

I think these need to be checked out and potentially fixed up, the similar the behaviour between win and mono the better, and also less weird bugs :-)

**Comment by 7sharp9** [comment]
In addition, with mono 4.0 there will no longer be .Net 4.0 references distributed so .Net4.5 will have to be assumed.

**Comment by matthid** [comment]
So if I understand you correctly this is a general problem in F# and should therefore reported to fsharp/fsharp? I'm first trying to reproduce this with the F# compiler as well...

**Comment by 7sharp9** [comment]
Yeah if its a general problem fsharp/fsharp would be where this would be fixed, then back ported here I guess.

**Comment by matthid** [comment]
I could reproduce this with the F# compiler so I looked up the docs again:

Apparently this seems to be by design oO. F# docs (https://msdn.microsoft.com/en-us/library/dd233171.aspx) forward to C# docs (https://msdn.microsoft.com/en-us/library/s5bac5fx.aspx) and that page says we first look into the "common language runtime system directory" (before `--lib` or `-I:`). And for some reason mono has a `EntityFramework.dll` in there (maybe a poor design decision on the mono side).

So if I'm correct `-I:` should not be used by FSharp.Formatting and replaced by a bunch of `-r:` parameters. I'm not sure why they have chosen this particular order though. It doesn't seem to be very useful.

I close this: While it looks somehow broken (and took me a long time to realize) it is at least documented.

**Comment by 7sharp9** [comment]
Commonly with mono you have to use the #I option where there are references which have dependencies, fparsec springs to mind.

**Comment by matthid** [comment]
Yep it's the same thing:

### Windows:
```
> #r "EntityFramework.dll";;

  #r "EntityFramework.dll";;
  ^^^^^^^^^^^^^^^^^^^^^^^^

stdin(1,1): error FS0082: Dieser Verweis konnte nicht aufgelöst werden. Die EntityFramework.dll-Assembly wurde nicht gefunden. Stellen Sie sicher, dass die Assembly auf dem Datenträger vorhanden ist. Falls dieser Verweis im Code erforderlich ist, können Kompilierungsfehler auftreten. (Code=MSB3245)

  #r "EntityFramework.dll";;
  ^^^^^^^^^^^^^^^^^^^^^^^^

> stdin(1,1): error FS0084: Der Assemblyverweis "EntityFramework.dll" wurde nicht gefunden oder ist ungültig.
```

```
> #I @"C:\projects\Project\packages\EntityFramework\lib\net45";;

--> Added 'C:\projects\Project\packages\EntityFramework\lib\net45' to library include path

> #r "EntityFramework.dll";;

--> Referenced 'C:\projects\Yaaf.Database\packages\EntityFramework\lib\net45\EntityFramework.dll' (file may be locked by F# Interactive process)

```

### Linux:
```
> #r "EntityFramework.dll";;

--> Referenced '/usr/lib64/mono/4.5/EntityFramework.dll' (file may be locked by F# Interactive process)
```

```
> #I "packages/EntityFramework/lib/net45";;

--> Added '/home/matthid/projects/Project/packages/EntityFramework/lib/net45' to library include path

> #r "EntityFramework.dll";;

--> Referenced '/usr/lib64/mono/4.5/EntityFramework.dll' (file may be locked by F# Interactive process)
```

I think we can only hope those folders don't diverge any further or we can change the loading ordering and prefer library folders over system specific folders.
