### ISSUE TITLE
FSharpLineTokenizer doesn't produce tokens for a #endif

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#314]
Given:

```fsharp
#if test
let add = (+)
#endif
```

I will get back the tokens

```
[HASH_IF; WHITESPACE; IDENT]
[LET; WHITESPACE; IDENT; WHITESPACE; EQUALS; WHITESPACE; LPAREN; PLUS_MINUS_OP; RPAREN]
[]
```

The empty list at the end is unexpected as theres no way to determine where the HASH_IF block ends?

How does Visual Studio determine active/inactive code, this is blocking me a on the roslyn port as I dont know how to easily colour code that is inactive due to compiler directives.

**Comment by dsyme** [comment]
Could you add a full repro? The code for #endif looks like it should be returning the token, unless the ifdefStack is not maintained (e.g. a new lexer is being created for each line) or whitespace skipping is on

```
 | anywhite* "#endif" anywhite* ("//" [^'\n''\r']*)?
   { let lexed = (lexeme lexbuf) 
     let m = lexbuf.LexemeRange 
     match !(args.ifdefStack) with
     | []->  LEX_FAILURE (FSComp.SR.lexHashEndingNoMatchingIf())
     | _ :: rest ->  
        args.ifdefStack := rest;          
        let tok = HASH_ENDIF(m,lexed,LexCont.EndLine(LexerEndlineContinuation.Token(!args.ifdefStack))) 
        let tok = shouldStartLine args lexbuf m (FSComp.SR.lexHashEndifMustBeFirst()) tok 
        if not skip then tok else endline (LexerEndlineContinuation.Token(!args.ifdefStack)) args skip lexbuf }
```

**Comment by 7sharp9** [comment]
Yep, I screwed up :-)
