### ISSUE TITLE
Functions defined as a value can't be inlined

### ISSUE THREAD

**Issue by amazingant** [fsharp/FSharp.Compiler.Service#315]
Based on the feedback to my uservoice post asking for a better type-signature format (see post [here][1]), I write out type signatures for most important functions like this:

```F#
let add : int -> int -> int =
    fun x y -> x + y
```
I know this isn't standard by far, but for the sake of optimizing how far I have to go to find the type signature when I'm not reading the code in Visual Studio, this form is much easier to work with like the `val` syntax used in `.fsi` files.

Moving on, I was trying to reduce some workload by writing out a helper function that, in order to maintain tail-call optimizations, had to be inlined. However, when the `inline` keyword is added to a function written in this format, the compiler says `Only functions may be marked 'inline'`.

Is this something that could maybe be addressed somehow in the compiler, something I need to just deal with not being compatible with that type signature format, or something else entirely?

Running into this with both F# 3.1 in Visual Studio 2013, and F# 4.0 in Visual Studio 2015 CTP 6.

[1]: https://fslang.uservoice.com/forums/245727-f-language/suggestions/6538074-add-support-for-haskell-style-type-annotations

**Comment by dsyme** [comment]
Hi @amazingant - This one belongs at http://github.com/Microsoft/visualfsharp (if you think it a bug report) and http://fslang.uservoice.com (if you think it a feature request).  Right now I think we'd consider it a feature request.  It's reasonable to fix this and a PR for it would likely be accepted (subject to when schedules etc.)

**Comment by dsyme** [comment]
Closing this because it's not the right repo, see above for links

**Comment by amazingant** [comment]
Based on how everyone advocates functions as values as a big functional programming thing, it feels like a bug to me that a function value written like this doesn't count as a "function" in special cases. On the other hand, it's also an abnormal syntax that isn't typically used, so I'm less than surprised the `inline` keyword doesn't like it.

Looks like someone already mentioned it on uservoice [here][1], so I'll link to this issue in a comment there. At some point when I have free time I'll look into how the F# compiler handles the `inline` keyword and see if I can sniff out a way to adjust; maybe it'll make it into the F# 6 or 7 release. :wink:

[1]: https://fslang.uservoice.com/forums/245727-f-language/suggestions/6237585-allow-inline-keyword-in-the-case-let-f-fun-a
