### ISSUE TITLE
Overridden types in auto open modules causes error in interactive checker

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#316]
Details from: https://bugzilla.xamarin.com/show_bug.cgi?id=27405

From @henrik
Repro:

paket install nuget EventStore.Client.FSharp

In code:

```
open EventStore.ClientAPI

let (re : ResolvedEvent) =
  let id : StreamId = re.Event.StreamId
```

The reason is that EventStore.Client.FSharp has a module Types, with
[<AutoOpen>] which contains a 'ResolvedEvent' which is intended to override
EventStore.Client.ResolvedEvent.

**Comment by 7sharp9** [comment]
![screen shot 2015-02-25 at 14 15 17](https://cloud.githubusercontent.com/assets/588746/6750376/836499a0-cef1-11e4-9a30-82d6ab09d6c3.png)

**Comment by henrik** [comment]
Wrong Henrik, unsubscribing. No worries :)

**Comment by dsyme** [comment]
I don't think this is a bug in FCS - it may be a general F# bug but we'd need an exact repro submitted to Microsoft/visualfsharp.
