### ISSUE TITLE
Unable to resolve a `FSharp.Core.dll`

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#317]
I just noticed something strange when using a clean install of http://github.com/fsharp/fsharp on linux (gentoo with mono 3.12.1 in my case).
It looks like applications using FCS will not work in this scenario and you will get quite obfuscated error messages like:

```
System.Exception: Error creating evaluation session: StopProcessing "{Exception = FileNameNotResolved;
 Phase = Interactive;}"
  at Microsoft.FSharp.Compiler.Interactive.Shell+-ctor@2442-111.Invoke (System.String message) [0x00000] in <filename unknown>:0 
```

or 
```
System.Exception : Error creating evaluation session: StopProcessing
  "{Exception =
  Error
    ((3160,
      "Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown."),
     unknown (1,0--1,80) IsSynthetic=false);
 Phase = Interactive;}"
  at Microsoft.FSharp.Compiler.Interactive.Shell+-ctor@2442-111.Invoke (System.String message) [0x00000] in <filename unknown>:0 
```

The reason seems to be the assembly resolution strategy when no explicit `FSharp.Core.dll` is specified:
 - First the runtime folder is tried (`/usr/lib/mono/4.5`) which fails
 - Then the current folder which again fails
 - Now FSC falls back to `defaultFSharpBinariesDir` which is hardcoded in https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L2358 because it is assumed we are executing an fsi.exe process (so this default is not sane for FCS)

I'm not sure what the "correct" fix for this issue is but the following things work:
 - Specifying an include path which contains a `FSharp.Core.dll` with `-I:/usr/lib/mono/4.0`(not ideal, see https://github.com/fsharp/fsharp/pull/389 and https://github.com/fsharp/fsharp/pull/388).
   Personally I'm using this because I don't have to bundle a `FSharp.Compiler.Service.dll` in this case.
 - Use https://github.com/matthid/FSharp.Compiler.Service/commit/3282b5d29f6ff2273fbef861992fd7dec2ffbde3 to change the current default to an internally used robust strategy

While hunting down this issue I noticed that the exceptions are pretty useless currently and all the important things are written to the output stream. This catches a lot of people off-guard because this is true for the `FsiEvaluationSession` constructor as well. You would not expect the constructor to write into the stream instead of throwing informative exceptions.

I have used https://github.com/matthid/FSharp.Compiler.Service/commit/f8b1e1781906bbabb5c6a2eae61f1cb1c69962fb for debugging but I'm not sure if this is something you want to merge.

Some more relevant places:
 - https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/build.fs#L2815
 - https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/build.fs#L2759

The reason why this bug doesn't happen more often (in travis for example) is because older and packaged versions have their ClrRoot hardcoded to `/usr/lib/mono/4.0` which is in fact kind of a bug as well (https://github.com/fsharp/fsharp/issues/99).
After merging the fsharp/fsharp pull requests from above the bug will probably disappear until the next version jump (because the ClrRoot wil match again). For packaged version I'm not sure but I think they probably need to update their hardcoded paths, but I see the potential for a lot of things breaking :(

Tell me what you think of this issue so I can open a pull request with the "correct" fix.

**Comment by dsyme** [comment]
It seems reasonable to add a workaround to the default FSharp.Core library location logic which looks in the runtime folder + ../4.0 as a last resort.  If you could send a PR that would be great

(Note that some fixes have recently been accepted in github.com/fsharp/fsharp to move all the binaries to lib/mono/4.5, those will eventually propagate to packages)

**Comment by matthid** [comment]
@dsyme Yes when they move to 4.5 the bug will disappear but will appear again on the next runtime folder change.

My suggested fix is https://github.com/fsharp/FSharp.Compiler.Service/pull/320, but other changes are possible as well (we could always add this path in any case in fsharp/fsharp for example in https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/build.fs#L2815)

**Comment by dsyme** [comment]
suggested fix has been integrated long ago
