### ISSUE TITLE
Open questions after reading interactive documentation

### ISSUE THREAD

**Issue by lukebuehler** [fsharp/FSharp.Compiler.Service#329]
For lack of having a better place to ask this... but I would like to help updating the documentation/samples if I get some more clarity on this.

I'd like to implement a rich F# REPL in WPF, like I did here for C#: https://github.com/lukebuehler/CShell

1) What's the difference in the API in hosting fsi in a separate process vs in the same process? I do want to host in the same process, and as far as I gathered, the example shows how to host in the same process? Is there an API to host in a separate process or would that just entail communicating with the fsi exe via a good 'ol process object?

2) I'd like to get some more clarity on the fsiConfig object. What is it for? And how is it used? All examples I've seen so far just use GetDefaultConfiguration(). Is this a bit like the Roslyn session object or the Mono.Interactive InteractiveBase class?
Why are a lot of the config option passed as arguments? Is this simply to have the same options as in the proper fsi.exe? However I cannot find any doc on what the "--noninteractive" does?

3) How to differentiate in between an expression and an interaction? I'd really like to send everything as an expression and just get "option none" if it doesn't evaluate to an expression. Because in order to implement a rich REPL I'd like to get all objects back, look if I can render them somehow interestingly, and just do nothing (except print a new line) if it's more like an interaction. I understand that you might want to differentiate "pure" expressions vs side effects. Right now I'm thinking of trying it as an expression and if it throws falling back on an interaction, but this seems ugly.

4) Any ideas how to handle partial evaluations? Like writing a multi-line function right in the REPL.

**Comment by dsyme** [comment]
Neat work on CShell

(1) - Yes, hosting as described in the tutorials is in-process.  Out-of-process would be done either by Process+stdin/atdout/stderr or by building your own host process or service, and use HTTP or some other communication mechanism to access it.

(2) There things are somewhat historical. I believe fsiConfig came from when a split was made between "fsi.exe" as a tool and the actual service underneath.  A bunch of configuration that wasn't already in command line options was just carved out.  There may be cleanup in this area eventually though you can get useful things done with the current API.  For particular things like --noninteractive it may be best to just dive into the code and see what the option does feel free to ask further questions though if you can't find the answer that way)

(3) Expressions never declare any new top-level types, modules, members, values, #r references, etc.. If you need an incremental declaration state, then you will need to use interactions.

(4) I'm not quite sure what you mean - do you mean partially-completed lines?

**Comment by lukebuehler** [comment]
@dsyme, thanks for the answer, and apologies for my delayed response.

1) All clear.

2) Makes sense to dive in the code for this stuff. Will do come back if I have concrete questions.

3) Hmm, the thing is with interactions that I don't get the object back if it's actually an expression. Don't interactions essentially ignore the result? I'd like to create a REPL that can display rich content inline, a little bit like the ipython notebooks. For this I'd like to create some simple plugin/extension system that renders results inline.
Example:
    
      >let logoUrl = "https://raw.github.com/fsharp/FSharp.Data/master/misc/logo.png"
      >Http.Request(logoUrl).Body |> img.fromBytes
        _______________________________
       |  Image Inline Here
       |
       |_______________________________
      >
Any other ideas how to do this?

4) Yes, partially completed lines, and multi-line evaluations. I could not figure out to make it behave the same way as the fsi where I can type:
```
> let foo =
    10*10;;
> foo;;
```

**Comment by dsyme** [comment]
For (3) - How about this: when you have an interaction ready to go, you should decide if it is an expression or a declaration.  You can do this either by parsing it and looking at the untyped AST, or by using an approximation ("it begins with module/type/let/exception/... so it's a declaration").  Then use either EvalExpression or EvalInteraction 

For (4) - this should work - just send all the text to EvalInteraction when you're ready.  This should be either when you get the ";;" or when the user enters some special keystroke.  You don't feed the text line-by-line but rather all at once.

**Comment by lukebuehler** [comment]
Makes sense, I think I have a good overview now on how to take the next steps. Thanks!
