### ISSUE TITLE
Find all references on record type does not find "anonymous" usages

### ISSUE THREAD

**Issue by latkin** [fsharp/FSharp.Compiler.Service#331]
Found via VFPT, but I believe this is where fix would be implemented.

``` fsharp
type MyRec =
    { Foo : string }

let x = { Foo = "test" }
```

If I do FAR on `Foo`, both the declaration and the usage are found.
If I do FAR on `MyRec`, it only finds the declaration, not the usage.

I think it's a common scenario to do FAR on a type name and expect that all instances of the type being instantiated will be found.  This is the case if one uses the more verbose syntax `{ MyRec.Foo = "test" }`

**Comment by dsyme** [comment]
Spring cleaning old suggestion issues
