### ISSUE TITLE
No XmlDocSig for MemeberFunctionOrValue types that have no parent entitty

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#333]
If you bind a non F# entity, then retrieve its symbol there is no xmldocsig present.

`let §test§ = NonFSharpEntity()`

**Comment by 7sharp9** [comment]
This should be patchable, just need to figure out how to get the `TyconRef`

**Comment by dsyme** [comment]
Strange, it looks like this should be populated, see 

* https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/Symbols.fs#L442

* https://github.com/fsharp/FSharp.Compiler.Service/blob/d9840d00a810d841901d380730b3274d36875269/src/fsharp/vs/Symbols.fs#L133

* https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/vs/ServiceDeclarations.fs#L308

**Comment by 7sharp9** [comment]
And it would if the binding was an entity, in this case its a `FSharpMemberOrFunctionOrValue` where its a value bound to a normal object constructor.

I think this needs to be added to FSharpMemberOrFunctionOrValue

```fsharp
    member __.XmlDocSig = 
        checkIsResolved()
 
        match d with 
        | E e ->
            let range = defaultArg __.DeclarationLocationOpt range0
            match ItemDescriptionsImpl.GetXmlDocSigOfEvent cenv.infoReader range e with
            | Some (_, docsig) -> docsig
            | _ -> ""
        | P p ->
            let range = defaultArg __.DeclarationLocationOpt range0
            match ItemDescriptionsImpl.GetXmlDocSigOfProp cenv.infoReader range p with
            | Some (_, docsig) -> docsig
            | _ -> ""
        | M m -> 
            let range = defaultArg __.DeclarationLocationOpt range0
            match ItemDescriptionsImpl.GetXmlDocSigOfMethInfo cenv.infoReader range m with
            | Some (_, docsig) -> docsig
            | _ -> ""
        | V v ->
            match v.ActualParent with 
            | Parent entityRef -> 
                match ItemDescriptionsImpl.GetXmlDocSigOfValRef cenv.g entityRef v with
                | Some (_, docsig) -> docsig
                | _ -> ""
            | ParentNone ->
                //If there is no parent then we try to use the full types xmldocsig
                //This happens with a let binding on a normal type constructor binding i.e let aaa = Document()
                let fullType = __.FullType
                if fullType.HasTypeDefinition then fullType.TypeDefinition.XmlDocSig
                else ""
```

**Comment by 7sharp9** [comment]
I suppose it depends on whether you think that a local binding should have an xmldocsig

**Comment by 7sharp9** [comment]
A local binding could show the xmldoc sig for its actual entity if we wanted it to.  Ill close this for now.
