### ISSUE TITLE
Questions from Kevin Ransom

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Compiler.Service#336]
@KevinRansom asked myself and @tpetricek these questions about FCS - I'm pasting them here and we can discuss them below.

1. Do you have scenarios where the compiler service needs the #if SILVERLIGHT code? It was removed from visual fsharp tools last April or May

2. All of the APIs in the compiler service that are made public are they all necessary and well thought out, if we pruned the list how many fsharp compiler service consumers would be impacted?

       module (*internal*) Microsoft.FSharp.Compiler.AbstractIL.IL

3. Is this really an ideal public API name?

       module (*internal*) Microsoft.FSharp.Compiler.AbstractIL.Internal.Library

4. CROSS_PLATFORM_COMPILER seems to be used primarily to distinguish between Windows builds and those without symbols. In ilsupp.fs it tries to use reflection to load ISymWrapper, otherwise it uses no symbol reader. Is this a hack for Silverlight or does it work on mono if the dll is present, or what, my understanding was that mono doesn’t have dotnet symbols at all.

5. IL.runningOnMono 

   * Is this: Mono.Security.StrongName a xamarin assembly?

   * Do you have test cases for each of the uses of IL.runningOnMono?  Especially the strongkey apis in ilsupp.fs, I would hate to break this stuff?

6. NO_STRONGNAME_SIGNER - What are the circumstances that this value should be defined during a build, is it necessary for visual fsharp tools moving forward?

7. Il.fs

   * memoizeNamespaceTable has changed from Dictionary<string,string,list> to Concurrent.ConcurrentDictionary<string,string list>. Was that to address a specific threading issue or some other reason? Has anyone an assessment of the performance impact of the change?

**Comment by dsyme** [comment]
> Do you have scenarios where the compiler service needs the #if SILVERLIGHT code?

Not really. I think there was a feeling that much of the code could be useful if we made FSharp.Compiler.Service a PCL component of some kind. We could archive it to a Silverlight branch that we could bring up-to-date again if needed.  

> All of the APIs in the compiler service that are made public are they all necessary and well thought out, if we pruned the list how many fsharp compiler service consumers would be impacted?

The API should be fully reviewed and trimmed down as much as possible.  In the "release early, release frequently" model used by this repo it has been OK to expose more stuff since people can sync to a constant nuget version and then migrate forward at their own pace.  AFAIK the most intrusive thing (and least designed) is the exposure of the untyped abstract syntax tree (ast.fs).  This causes the exposure of a bunch of other things too. 

> module (*internal*) Microsoft.FSharp.Compiler.AbstractIL.Internal.Library

The only thing needed from this is the FileSystem thing.  I’ll prepare a PR to FCS to expose that in a different way.

> CROSS_PLATFORM_COMPILER seems to be used primarily to distinguish between Windows builds and those without symbols. In ilsupp.fs it tries to use reflection to load ISymWrapper, otherwise it uses no symbol reader..Is this a hack for Silverlight or does it work on mono if the dll is present, or what, my understanding was that mono doesn’t have dotnet symbols at all.

Yes, apart from reference resolution this is the only use.  It means the one DLL works on Windows (and can read symbols when doing static linking), and also works on Mono (without reading symbols when doing static linking).   However TBH the Mono case is already covered by [this code](https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/absil/ilsupp.fs#L1173) so the entire #if [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/absil/ilsupp.fs#L1183) is unnecessary.

> Is this: Mono.Security.StrongName a xamarin assembly

It's a standard Mono assembly

> Do you have test cases for each of the uses of IL.runningOnMono? Especially the strongkey apis in ilsupp.fs, I would hate to break this stuff

Let's look at these one by one

* [mdb extension 1](https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/absil/ilsupp.fs#L47) and [mdb extension 2](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/build.fs#L2278).  I believe the testing produces debug symbols at some point, but the debug experience in an actual debugger is never tested.

* [don't look at registry when finding compiler](https://github.com/fsharp/FSharp.Compiler.Service/blob/9a3fc667180ab0a04ee68d341804d40b9d34a008/src/utils/CompilerLocationUtils.fs#L157).  This is a typical "trim some specific Windows behaviour" use and there is no test for that.

* [don't set two properties when using Mono XBuild API](https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/fsharp/ReferenceResolution.fs#L306).  This must have been functionality that just hadn't yet been added to the Mono implementation of the MSBuild API.  There's no test for this - ultimately the best resolution is for the Mono API to add this stuff and we don't need to make it conditional

* [disable console key processing on Mono](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/fsi/fsi.fs#L526).  Well, this is just a Windows v. Unix difference, or a Mono v. .NET, it's hard to tell.  There is no specific test for it.

* [strange hack for Reflection Emit code](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/absil/ilreflect.fs#L447).  I don't know about this.  There is no test for it.

* [access internal name of a type to detect a builder instantiation](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/absil/ilreflect.fs#L667)  This is works around a limitation of Reflection Emit where you can't tell the difference between an instantiation that supports querying and one that doesn't.  It is unfortunate but necessary.  I believe this code is already integrated back into Microsoft/visualfsharp.  Nothing works with F# Interactive on Mono without this, so it's tested.

* [disable generation of default win32 manifest](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/fsc.fs#L1242). I suppose "default.win32manifest" isn't available in the runtime directory on Mono, though I haven't checked recently.

* [add the /resident flag](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/fscopts.fs#L411).  This is not really relevant to the compiler service - the Mono release of fsharp has historically included a /resident flag to use a terminate-and-stay-resident compiler for better startup. However this is not used by xbuild so it's likely people aren't really using this.

* [use simple resolution by default](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/build.fs#L2149) and [also here](https://github.com/fsharp/FSharp.Compiler.Service/blob/f1605c071094590088382a75261d394855cd85d3/src/fsharp/vs/service.fs#L2219).  The Mono implementation of the MSBuild API has always been too flakey for our purposes, so it is not used by default.

* [set the executable bit on generated binaries](https://github.com/fsharp/FSharp.Compiler.Service/blob/7790ea2709d8b8d750957b6cd6b98bc987d02d37/src/absil/ilwrite.fs#L3448).  This is a Unix thing - we want +x on generated binaries.  There's no specific testing for this AFAIK though probably little would work without it.

* [don't generate native resources](https://github.com/fsharp/FSharp.Compiler.Service/blob/7790ea2709d8b8d750957b6cd6b98bc987d02d37/src/absil/ilwrite.fs#L4094).   It looks like native resources are never generated when running the compiler on Mono.  AFAIK there's no specific testing for this.

* [old hack for multi dimensional arrays for .NET 2.0](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/fsharp/ilxgen.fs#L2503).  This is no longer needed in any version of F# AFAIK, see the comment, it was related to an old CLR bug.   

* [disable symbol reading on Mono](https://github.com/fsharp/FSharp.Compiler.Service/blob/89d936ca760b790f7741a0bab9122002a792810c/src/absil/ilread.fs#L3832).  This is somewhat related to the unnecessary use of CROSS_MODULE_COMPILER further above.


I'll answer the other questions in a bit.

**Comment by 7sharp9** [comment]
I have a scenario where I need FCS running with multiple profiles, a bit like silverlight, I recently converted some of the silverlight flags so more modular descriptive ones.

**Comment by 7sharp9** [comment]
With MSbuild now open source mono will quite soon have a fuller implementation, so Im hoping that can be applied to the F# version running on mono also.

**Comment by dsyme** [comment]
@7sharp9 - can you submit the profile flag updates back to FCS?

**Comment by 7sharp9** [comment]
I already did for some, when I get back to getting FCS working on the simulators I can address the others.

It a bit of a strange one, as although Console is denied in the portable type profiles and reflection emit too, there are some special redirects in the simulator that allow it.

**Comment by dsyme** [comment]
Closing this as it's an older discussion
