### ISSUE TITLE
How to include MSBUILD dependencies?

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#337]
When you get the `FSharp.Compiler.Service` NuGet package and install it as part of some application on Azure VM, the application will fail, because F# Compiler Service depends on MSBUILD assemblies that are not part of .NET Framework:

 - Microsoft.Build
 - Microsoft.Build.Engine
 - Microsoft.Build.Framework
 - Microsoft.Build.Utilities.v12.0
 - Microsoft.Build.Tasks.v12.0

This is a bit unfortunate, because it measn that `FSharp.Compiler.Service` will not work on non-dev machines. I'm not sure what the best solution is?

 - Bundle the libraries with FSharp.Compiler.Service NuGet package? (but it's about 5 MB that most people won't need...)
 - Have a NuGet dependency? (if MSBUILD was on NuGet... which I don't think it is)
 - ILMERGE ALL THE THINGS! (that is, just the MSBUILD assemblies using the nice ILMerge tool that sometimes does not crash...)
 - Give up and tell people to install MSBUILD on their deployment machines?

[See also my comment in: https://github.com/fsharp/fsharp/pull/409]

**Comment by 7sharp9** [comment]
The msbuild 12 bits are for the project file cracking stuff, but msbuild is also used for reference resolution.  Why would that never be installed?

**Comment by tpetricek** [comment]
[MSBUILD is now (well, for the last 3 years) a part of Visual Studio](http://blogs.msdn.com/b/visualstudio/archive/2013/07/24/msbuild-is-now-part-of-visual-studio.aspx) and so we cannot expect it to be installed...

**Comment by 7sharp9** [comment]
These are the bits that added the v12 dependencies:  https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2336-L2454

**Comment by 7sharp9** [comment]
I have a pcl version of FCS that Im working on that has no msbuild dependencies, not yet finished I might add.

**Comment by dsyme** [comment]
I suppose the appropriate DLLs should be bundled as part of the FCS package for now, that seems reasonable, similar to here: https://github.com/fsharp/fsharp/pull/409/.  Could you send a PR to adjust?

**Comment by cognociente** [comment]
It seems that the intention here was to add the relevant MSBUILD dependencies/dlls into the FSCS nuget package - this does not seem to have been implemented though as my usage of FSCS via nuget has just downloaded fsharp.compiler.services.dll.

**Comment by simra** [comment]
Up-vote for this issue. https://github.com/simra/IfSharp/issues/7. 
I'll try the options suggested in #424.

**Comment by rneatherway** [comment]
This should be addressed by #470.
