### ISSUE TITLE
GetProjectOptionsFromProjectFile seems to retain a large portion of memory. 

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#339]
Is it possible to get this released earlier?

Even with a moderate project fileIm seeing 180MB in a ProjectStringCache which appears to be allocated on this call path.

This is also mentioned here:  https://connect.microsoft.com/VisualStudio/feedback/details/816008/memory-leak-in-projectstringcache-with-net-4-5

Heres a call stack showing creation:
![screen shot 2015-05-15 at 22 08 00](https://cloud.githubusercontent.com/assets/588746/7661934/ea0f2bb4-fb4e-11e4-8bdc-5b2f2a275342.png)

**Comment by 7sharp9** [comment]
@rneatherway @dsyme ^

**Comment by 7sharp9** [comment]
It seems to retain a substantial amount too:
![screen shot 2015-05-15 at 22 25 50](https://cloud.githubusercontent.com/assets/588746/7662212/daf7ede8-fb51-11e4-8d65-9c2a7667f150.png)

**Comment by 7sharp9** [comment]
Note I tested this on a Windows machine so this around here:  https://github.com/fsharp/FSharp.Compiler.Service/blob/f1605c071094590088382a75261d394855cd85d3/src/fsharp/vs/service.fs#L2405

**Comment by 7sharp9** [comment]
As noted in the linked connect issue, I believe `UnloadAllProjects` needs to be clled before the project collection goes out of scope:  https://msdn.microsoft.com/en-us/library/microsoft.build.evaluation.projectcollection.unloadallprojects(v=vs.121).aspx

**Comment by rneatherway** [comment]
That's a cool image Dave, is that from Xamarin Studio?

Unloading might be a good idea, as long as the callers are aware that this stuff isn't cached anymore. Do  you think there might be a similar hotspot on the Mono path?

Any news on when Xamarin might incorporate the MSBuild open source release? It would be really great to have a single code path there.

**Comment by 7sharp9** [comment]
I don't think anything is cached anyway the project creation is in a use block, it's just leaking memory.  Disposal doesn't appear the clear the cache.

**Comment by 7sharp9** [comment]
I'll investigate the mono paths next week and send a PR if I can resolve this.  At the moment I have an annoying leak, memory is already tight in 32 processes :-(

**Comment by 7sharp9** [comment]
The latest mono has msbuild14 in it.  The image was from dotMemory.   The profile in Visual Studio didn't work at all.

**Comment by 7sharp9** [comment]
Closing this, I resolved with a lock on access.
