### ISSUE TITLE
´CompiledNameAttribute´ not allowed on constructors of discriminated unions

### ISSUE THREAD

**Issue by exercitusvir** [fsharp/FSharp.Compiler.Service#341]
Constructors of discriminated unions are compiled to static methods in a static class where the class is named after the type of the discriminated union and the constructors are named `New[Case]`. 

I would to change that name with the `CompiledNameAttribute`, but it cannot be applied to constructors even though CompiledNameAttribute is allowed on methods and the constructors are compiled to static methods. 

Why is this not possible? It says:
> Attributes not allowed here

**Comment by 7sharp9** [comment]
I think this issue should over at https://github.com/Microsoft/visualfsharp/issues rather than here which just deals with compiler services for editors and tooling.

**Comment by dsyme** [comment]
I think it needs to be a suggestion at http://fslang.uservoice.com
