### ISSUE TITLE
Can we pull over some of the F# VS integration code?

### ISSUE THREAD

**Issue by rneatherway** [fsharp/FSharp.Compiler.Service#344]
I was having a look at the MS open source code, and while also thinking about getting rid of FSharp.CompilerBinding (which FSAC and MD F# support have separate copies of), I thought that perhaps we could at least push the identifier cracking code into FCS.

fsharp org version: https://github.com/fsharp/FSharp.AutoComplete/blob/master/FSharp.CompilerBinding/Parser.fs
MS open source version: https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.LanguageService/QuickParse.fs

The MS version has seen so much more use it can probably be viewed as a canonical implementation of this, and this particular module doesn't depend on any VS APIs. It would be good to consider if anything else could be pulled into FCS as well.

If we pull this in, then can we make the API (for getting tooltips and declarations etc) one that just consists of providing the source text and a location, and have FCS carry out the cracking for you?

**Comment by dsyme** [comment]
The MS version actually has some bugs I think - especially around double-tick identifiers, so may not be the best

I think one problem is that the identifier-cracking code can need an multi-line text before the current location (or at least before it). So the API will still need to receive some text, or a callback to read the text, which would be a bit unfortunate.

**Comment by rneatherway** [comment]
>The MS version actually has some bugs I think - especially around double-tick identifiers, so may not necessarily be better

That's interesting. On the other hand, what we have here (and is also used in monodevelop) never uses more than a single line, so it's hard to say which is better!
