### ISSUE TITLE
GetProjectOptionsFromScript 'source' parameter not used

### ISSUE THREAD

**Issue by jcansdale** [fsharp/FSharp.Compiler.Service#346]
The following seems to work fine:

        let checker = FSharpChecker.Create(keepAssemblyContents=true)
        let projOptions = checker.GetProjectOptionsFromScript(file, "") |> Async.RunSynchronously

I'm confused about what the 'source' parameter is used for? Is it okay to use an empty string as above?

Thanks,
Jamie,

**Comment by rneatherway** [comment]
It is used to find all the transitive dependencies required by the current script (following `#load` and `#r` directives). So, yes, it is needed if there is any `#r` anywhere in the `#load` graph.

See https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2225
