### ISSUE TITLE
Comparable errors to fsc.exe

### ISSUE THREAD

**Issue by henrid** [fsharp/FSharp.Compiler.Service#351]
Hi all,
I have a .fs file that compiles with no errors on both 3.1 and 3.0 versions of the F# compiler on a Windows 7 enterprise box. Using release 0.0.90 of compiler services, the same file fails to compile with "not structurally comparable" errors. Are there places where this compiler is more strict that fsc.exe?

**Comment by dsyme** [comment]
There shouldn't be.  Can you share the file and build options?

**Comment by henrid** [comment]
I was using warnings as errors settings. The compiler was giving extra warnings that I had not anticipated.
