### ISSUE TITLE
FsiEvaluationSession: "The option value was None Parameter name: option"

### ISSUE THREAD

**Issue by prosconi** [fsharp/FSharp.Compiler.Service#353]
When running the below code
```fsharp
let sbOut = new StringBuilder()
let sbErr = new StringBuilder()
let inStream = new StringReader("")
let outStream = new StringWriter(sbOut)
let errStream = new StringWriter(sbErr)

// Build command line arguments & start FSI session
let argv = [| "C:\\fsi.exe" |]
let allArgs = Array.append argv [|"--noninteractive"|]

let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration()
let fsiSession = FsiEvaluationSession.Create(fsiConfig, allArgs, inStream, outStream, errStream)  

fsiSession.EvalInteraction("let x = 1")
```

I get the below exception:
```
The option value was None Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at Microsoft.FSharp.Compiler.Ilxgen.LookupGeneratedValue(ImportMap amap, ExecutionContext ctxt, TcGlobals g, IlxGenEnv eenv, Val v) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\ilxgen.fs:line 6953
```

FSharp.Core: 3.1
.NET Framework: 4.5.1

Am I just doing it wrong?

**Comment by dsyme** [comment]
No, it looks like a bug related to fetching the value of "x" to report the generated values, likely related to [this commit](https://github.com/fsharp/FSharp.Compiler.Service/commit/dd7096f58f7acb889036f285ff8396417ea3ec43#diff-52a3b381c6bc6da5211d19ccdec6484dR1129) or its precursor.  

Which FCS are you using?  It looks to me like LookupGeneratedValue should always have all exceptions caught, https://github.com/fsharp/FSharp.Compiler.Service/blob/9a3fc667180ab0a04ee68d341804d40b9d34a008/src/fsharp/ilxgen.fs#L6938

**Comment by prosconi** [comment]
FSharp.Compiler.Service: 0.0.90

**Comment by prosconi** [comment]
Sorry, this was PEBKAC. The exceptions "Thrown" settings in VS were showing me caught exceptions. 

Maybe this brings up point of eliminating these exceptions from happening internally to speed things up with FSC? Closing this issue.
