### ISSUE TITLE
FSharpSymbol should return full body range

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#355]
To fix this VFPT bug https://github.com/fsprojects/VisualFSharpPowerTools/issues/957 I need `FSharpSymbol` to return declaration body range. 

For code

``` fsharp
let rec private f x =
    match x with
    | None -> None
    | Some _ -> f x
```

I'd like `FSharpSymbol.DeclBodyRange` (or whatever) for symbol `f` to be equal `(1, 1) - (4, 20)` (it covers all the code from `let` to `.. -> f x`.

It's needed because I should not consider `f` at the last line as a usage of the function. 

I understand that I can get the range from the untyped AST, but I'd like to not traverse it one more time.

**Comment by dungpa** [comment]
In order to fix this concrete issue, FCS could mark both two `FSharpSymbolUse` to be `FromDefinition`. We can then infer that the second symbol use is indeed inside the body of the defined function. It seems like easier to do than exposing `DeclBodyRange`.

**Comment by dungpa** [comment]
Reopening due to wrong auto-closing.

**Comment by vasily-kirichenko** [comment]
I cannot remember what this feature was needed for.
