### ISSUE TITLE
FSharpMemberOrFunctionOrValue.Overloads does not return overloads

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#356]
For example the following code:

``` fsharp
type JustOverloads() =
  member x.Overload(i:int) =
    i + 42
  member x.Overload(s:string) =
    int s + 42
```

The symbol `Overload` is a `MemberFunctionOrValue` but is assigned a `ValRef` type so the `Overloads` code doesnt ever return an item:

``` fsharp
    member x.Overloads matchParameterNumber =
        checkIsResolved()
        match d with
        | M m ->
            match item with
            | Item.MethodGroup (_name, methodInfos) ->
                let methods =
                    if matchParameterNumber then
                        methodInfos
                        |> List.filter (fun methodInfo -> not (methodInfo.NumArgs = m.NumArgs) )
                    else methodInfos
                methods
                |> List.map (fun mi -> FSharpMemberOrFunctionOrValue(cenv, M mi, item))
                |> makeReadOnlyCollection
                |> Some
            | _ -> None
        | _ -> None
```

Im not sure why the members are created as `ValRef` rather than `MethInfo` is it the case that only C# types with overloads are assigned that way?

**Comment by alfonsogarciacaro** [comment]
I checked this with last build and now `Overloads()` returns an item, but it's always the same method without references to other overloads.

In above example, calling `[JustOverloads Entity].MembersFunctionsAndValues.[1].Overloads(false)` will give `Some(seq [Overload(i:int)])` but you don't get information about `Overload(s:string)`.

Moreover, if you call `Overloads(false)` on a `FSharpMemberOrFunctionOrValue` taken from a typed expression you still don't get any item.
