### ISSUE TITLE
FCS accepts 1-based column indexes and returns 0-based

### ISSUE THREAD

**Issue by rneatherway** [fsharp/FSharp.Compiler.Service#358]
This seems really strange. How has this come about? For now in FsAutoComplete we are adding 1 to every column that we get back so that this interface is presented consistently to clients, but this seems like something that should be addressed here.

Comment indicating 1-based columns should be passed in: https://github.com/fsharp/FSharp.Compiler.Service/blob/251c00058cb4ec48e9fc31a7a814d8a3f4898d3f/src/fsharp/vs/service.fsi#L189

Output from FCS in an FsAutoComplete test with 0-based columns: https://github.com/rojepp/FSharp.AutoComplete/blob/67e5422a6b4a12dee5b442ed7d158be777c48813/FSharp.AutoComplete/test/integration/Test1/output.txt#L67

**Comment by dsyme** [comment]
Fixed the comment here https://github.com/fsharp/FSharp.Compiler.Service/commit/5539cad4051b2dbd080c7270d7b5aa87925772cc
