### ISSUE TITLE
FsiEvaluationSession.Create throws exception

### ISSUE THREAD

**Issue by simra** [fsharp/FSharp.Compiler.Service#364]
Hi,
My code is nearly verbatim copied from the docs [here](http://fsharp.github.io/FSharp.Compiler.Service/interactive.html), and I tried some of the suggestions noted in [this](https://github.com/fsharp/FSharp.Data/issues/587) issue, but so far the create() call continues to throw this exception:
```
An unhandled exception of type 'System.Exception' occurred in FSharp.Compiler.Service.dll
Additional information: Error creating evaluation session: StopProcessing
  "{Exception =
  Error
    ((3160,
      "Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown."),
     unknown (1,0--1,80) IsSynthetic=false);
 Phase = Interactive;}"
```

The code follows below.  The path to fsi.exe is correct and it works fine from the command line.  I'm using VS2013.  I tried adding a reference to the FSharp.Compiler.Interactive.Settings.dll, and I've tried variants of GetDefaultConfiguration to pass (), (fsi), (fsi,false) and (fsi, true).  In addition, it appears the --noninteractive argument is no longer supported, so I tried removing it, with no effect.

```
    // Intialize output and input streams
    let sbOut = new StringBuilder()
    let sbErr = new StringBuilder()
    let inStream = new StringReader("")
    let outStream = new StringWriter(sbOut)
    let errStream = new StringWriter(sbErr)

    // Build command line arguments & start FSI session
    let argv = [| @"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\fsi.exe" |]
    let allArgs = argv //Array.append argv [|"--noninteractive"|]

    let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration(fsi,false)
    
    let fsiSession = FsiEvaluationSession.Create(fsiConfig, allArgs, inStream, outStream, errStream) 

    let evalExpression text =
        match fsiSession.EvalExpression(text) with
        | Some value -> printfn "%A" value.ReflectionValue
        | None -> printfn "Got no result!"

    let result=evalExpression "42+1"
    printfn "%A" result
```

Any help would be appreciated, thanks!

**Comment by dsyme** [comment]
Hi @simra 
I'm having trouble reproducing this

1. Run ``nuget.exe install FSharp.Compiler.Service`` to get latest package (1.3.1.0)

2. Ran the code below through F# Interactive - it worked ok.

3. Compiled the code and used the binding redirects file - it worked ok.

Could you list exact repro steps based on fetching an FSharp.Compiler.Service package, and listing which OS etc. you are on?

thanks
don

```

#r @"C:\tmp\FSharp.Compiler.Service.1.3.1.0\lib\net45\FSharp.Compiler.Service.dll"
open System
open System.IO
open System.Text

open Microsoft.FSharp.Compiler
open Microsoft.FSharp.Compiler.Interactive
open Microsoft.FSharp.Compiler.Interactive.Shell

// Intialize output and input streams
let sbOut = new StringBuilder()
let sbErr = new StringBuilder()
let inStream = new StringReader("")
let outStream = new StringWriter(sbOut)
let errStream = new StringWriter(sbErr)

// Build command line arguments & start FSI session
let argv = [| @"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\fsi.exe" |]
let allArgs = argv //Array.append argv [|"--noninteractive"|]

let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration() //fsi,false)

let fsiSession = FsiEvaluationSession.Create(fsiConfig, allArgs, inStream, outStream, errStream) 

let evalExpression text =
    match fsiSession.EvalExpression(text) with
    | Some value -> printfn "%A" value.ReflectionValue
    | None -> printfn "Got no result!"

let result=evalExpression "42+1"
printfn "%A" result
```

test.exe.config for compile code:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity           name="FSharp.Core"           publicKeyToken="b03f5f7f11d50a3a"           culture="neutral"/>
        <bindingRedirect          oldVersion="2.0.0.0-4.3.1.0"           newVersion="4.4.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

```

**Comment by dsyme** [comment]
It may be possible that you have a stray FSharp.Core.dll (possibly without FSharp.Core.optdata or FSharp.Core.sigdata) in a directory?

**Comment by PoroCYon** [comment]
@dsyme I had this issue too, a few days ago. Adding those files fixed it (maybe this should be better documented?).

**Comment by dsyme** [comment]
Hi @PoroCYon, @simra - Could you review the existing docs at https://fsharp.github.io/FSharp.Compiler.Service/corelib.html and see what needs to be added?  If you could submit a PR with a clarification that would be great, the source of the docs is at https://github.com/fsharp/FSharp.Compiler.Service/blob/master/docs/content/corelib.fsx

**Comment by PoroCYon** [comment]
@dsyme I was reading the [interactive](https://fsharp.github.io/FSharp.Compiler.Service/interactive.html) docs, and it doesn't refer directly to the page you linked, so I'll add that.

**Comment by dsyme** [comment]
Thanks!

**Comment by simra** [comment]
Thanks guys, I'll try to update this thread early next week.
I was building a bare-bones console project in vs2013. Adding the missing files didn't help.

-----Original Message-----

**Comment by kerams** [comment]
I had the exact same problem. The code worked when pasted into F# Interactive, but not when run in .fs. It seems that the issue was caused by having a reference to FSharp.Core Nuget package.

If I may have an unrelated question, what's the point of `let argv = [| @"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\fsi.exe" |]`? Using an empty array works just as well for me.

**Comment by simra** [comment]
I created a fresh project, sourced the compiler service from NuGet and after dropping the sigdata and optdata files into my build directory everything worked. Not sure what went wrong with the earlier build.  @kerams seems to be correct- fsi.exe is not necessary in argv.  Maybe FSharp.Core knows where to look?
The documentation updates look good so I'll go ahead and close this.
