### ISSUE TITLE
Unable to run as a Windows service

### ISSUE THREAD

**Issue by henrid** [fsharp/FSharp.Compiler.Service#373]
Hi all,
Has anyone been able to run this library as part of a Windows service? I'm trying to run it as a Windows service but I receive a "IOException occured The handle is invalid." on line 1896 of fsc.fs.

```System.AppDomain.CurrentDomain.ProcessExit.Add(fun _ -> System.Console.OutputEncoding <- prev)```

Is this because of the lack of console when running as a Windows service? 
(my program works as a standard console application)

Thank you for your help.

**Comment by henrid** [comment]
I see the ```#if LIMITED_CONSOLE``` now. Would it be possible to a "include --define:LIMITED_CONSOLE" built dll into the releases? If not, can you specify the commit hash of the latest release so that we may build against those? Thanks!

**Comment by dsyme** [comment]
It looks like LIMITED_CONSOLE is not defined anywhere (though it may be in the Visual F# Tools)

I think we would silently disable the console-related functionality rather than build an alternative version of the DLL, or control it via a command line switch.

BTW the line above is only set if the /utf8output flag is used.  Are you defining that? (though I'd expect you will hit other console-related limitations further along the way)

**Comment by henrid** [comment]
Confirmed. Yes, we were using the utf8output flag originally. I turned it off and now it works from the Windows service.

**Comment by henrid** [comment]
grep -rni "LIMITED_CONSOLE" ../FSharp.Compiler.Service-master/

./FSharp.Compiler.Service-master/src/fsharp/build.fs:5420:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fsc.fs:1866:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fsc.fs:1885:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fscopts.fs:987:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fsi/fsi.fs:669:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fsi/fsi.fs:763:#if LIMITED_CONSOLE
./FSharp.Compiler.Service-master/src/fsharp/fsi/fsi.fs:2326:#if LIMITED_CONSOLE

**Comment by dsyme** [comment]
OK, I'll close this now.  Most of those uses appear to be protected in the sense that a failure will just result in some console feature being disabled (e.g. console coloring).  Reopen if you see specific further problems or if you have other concerns?
