### ISSUE TITLE
CrackProjectUsingNewBuildAPI problem

### ISSUE THREAD

**Issue by Thorium** [fsharp/FSharp.Compiler.Service#379]
F#-project files have this XML:

	  <Choose>
		<When Condition="'$(VisualStudioVersion)' == '11.0'">
		  <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
			<FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
		  </PropertyGroup>
		</When>
		<Otherwise>
		  <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
			<FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
		  </PropertyGroup>
		</Otherwise>
	  </Choose>
	  <Import Project="$(FSharpTargetsPath)" />

Now, if the condition, ``Exists('$(MSBuildExtensionsPath32)...``, fails for any reason, the FSharpTargetsPath will be empty, and the import is `Import Project=""` which will cause MSBuild to throw an exception "InvalidProjectFileException" and FSharp.Compiler.Service will rethrow this even if the project-file itself is not invalid at all, it is just what the default F#-Project is: Actually service.fs CrackProjectUsingNewBuildAPI could well parse the information it needs: items, project references, dll-references, etc. So at least the exception name is wrong in this case.

Well, Microsoft.FSharp.Targets would import the projects default target, "Build", so I guess that is needed at some point when the project is compiled. But now when the compiler API is open source, some projects do the API-calls without the actual compilation:

      let projectFile = SourceCodeServices.FSharpProjectFileInfo.Parse(file)

**Comment by rneatherway** [comment]
@Thorium the import is actually quite important, because the function `SourceCodeServices.FSharpProjectFileInfo.Parse` is fully resolving all the assembly references, which is what it uses MSBuild for. These are needed to give the correct compilation context back to the compiler services when requesting type information etc. If you look more at the [implementation](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2433), you will see that the "Build" target is in fact called, although with a stubbed compiler.

It's interesting to know when this fails, could you give some information on that?

**Comment by 7sharp9** [comment]
Maybe its similar to my issue where `MSBuildExtensionsPath32` is something completely different to what you expect.  Ive been scratching my head over the last few days trying to get to grips with whats going wrong...

**Comment by rneatherway** [comment]
I think @Thorium is on Windows though, because he's using the "NewBuildAPI". Hopefully MS aren't messing around with that variable too!

**Comment by Thorium** [comment]
Yes, my environment is Win 8.1 (and VS 2015 RC, so F# 4.0?), but I was opening an F#-file with SublimeText editor which called this Parse-method.

**Comment by rneatherway** [comment]
@Thorium I don't have a VS2015 machine myself, so this is rather difficult for me to test, but I don't think that this is supported by the current version of FCS (which is F# 3.1, MSBuild 12).

There is a beta F# 4.0 version at https://www.nuget.org/packages/FSharp.Compiler.Service/1.4.0-beta, but we still do not have a great story for switching MSBuild versions, so I'm not confident this would be easy for you to debug if you had the time to try.

**Comment by Thorium** [comment]
I downloaded the FsAutoComplete source codes and updated the nuget package reference of FSharp.Compiler.Service to this 1.4.0 beta and it seems not to fail. 

Also one way to test MSBuildExtensionsPath32 is just to add directly to the projectfile (before the usage) the line: 

     <MSBuildExtensionsPath32>C:\Program Files (x86)\MSBuild</MSBuildExtensionsPath32>

**Comment by rneatherway** [comment]
Thanks for testing! I will look at doing an official release with that
version if it works on Linux.

**Comment by Thorium** [comment]
Now that the FSharp.Compiler.Tools has been released, you could just add that nuget package to the solution and reference something like this in the .fsproj-file:

    <FSharpTargetsPath Condition="'$(FSharpTargetsPath)' == ''">..\Packages\FSharp.Compiler.Tools\Microsoft.FSharp.Targets</FSharpTargetsPath>

**Comment by rneatherway** [comment]
@Thorium that's a very interesting suggestion, thanks. I wasn't aware of the contents of the FSharp.Compiler.Tools package. Wouldn't this require changing every project file that you wanted to use with FSAC though?

**Comment by 7sharp9** [comment]
That API call still needs to be done in a separate process, to avoid dll loading pollution, and so that is works with all project types.

**Comment by rneatherway** [comment]
Yes, I agree that would be an improvement, but I'm interested in making sure it works with machines that only have VS2015 installed right now, which is a separate problem I think. In fact, I wonder how it works at all right now, because I'm not sure how VisualStudioVersion gets set, and therefore what value for it will be inserted in the path:

    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
