### ISSUE TITLE
Will the issue I am having with generation of extraneous JIT_TailCall be solved in the upcoming release to F# 4.0?

### ISSUE THREAD

**Issue by cognociente** [fsharp/FSharp.Compiler.Service#380]
I have posted the following on stackoverflow:

http://stackoverflow.com/questions/31433605/how-to-eliminate-time-spent-in-jit-tailcall-for-functions-that-are-genuinely-non

Summary: I am calling a .NET assembly (F# 4.0) from a dynamically generated assembly (FSCS 3.1) and it is passing a custom value type (struct) over the assembly boundary. This causes a set of unnecessary calls to JIT_TailCall that degrade performance materially.

**Comment by dsyme** [comment]
Hi @cognociente - The right place to ask this is http://github.com/Microsoft/visualfsharp.  FWIW this sounds like a CLR issue not an F# issue, so it may be redirected to http://github.com/dotnet/coreclr. I don't know of any fix to this in .NET as yet.

**Comment by cognociente** [comment]
Thanks @dsyme - I'll bump it over to http://github.com/Microsoft/visualfsharp and reference this issue.
