### ISSUE TITLE
GetAllUsesOfAllSymbolsInFile does not return info about nested types

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#381]
I have a type provider that produces a nested type, so you write e.g.:

    TopLevelType.NestedType.StaticProperty

Calling `GetAllUsesOfAllSymbolsInFile` returns only information about `TopLevelType` and `StaticProperty`, but not about `NestedType`.

Is this expected, or is it an error (I suspect the latter - nested types are not very common!)

**Comment by dungpa** [comment]
It's definitely a bug. It's probably a dup of https://github.com/fsharp/FSharp.Compiler.Service/issues/177.

I even added an ignored failing test at https://github.com/fsharp/FSharp.Compiler.Service/pull/325 but the issue slipped through the crack /cc @dsyme.

**Comment by dsyme** [comment]
Yes, we should get this fixed!

**Comment by dungpa** [comment]
Reopening due to wrong auto-closing.

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/FSharp.Compiler.Service/pull/425
