### ISSUE TITLE
Project wide ReflectedDefinition

### ISSUE THREAD

**Issue by xavierzwirtz** [fsharp/FSharp.Compiler.Service#382]
It would be nice for FunScript if you could pass in a command line argument that makes every method in the project you are compiling be marked with `[<ReflectedDefinition>]`.

**Comment by xavierzwirtz** [comment]
It doesnt look like this was affected by that commit?

**Comment by dsyme** [comment]
Closing as Fable (successor of FunScript) uses a different approach
