### ISSUE TITLE
Is it possible to get an FSharpEntities Full name that includes generic parameters?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#390]
Currently getting the FullName for a generic type like:

``` fsharp
type ted<'T> =
  class end
```

Will just yield `ted~1` rather than a typical `ted<_>`

It looks like this is possible via the `Entity` property `DisplayNameWithStaticParametersAndUnderscoreTypars` is there a reason this is not exposed?

**Comment by dsyme** [comment]
There's no reason that's not exposed

**Comment by 7sharp9** [comment]
What Im really after is `FSharpEntity.TryGetFullName` that returns

"Program.ted<_>"

Perhaps adding `FSharpEntity.TryGetFullNameWithStaticParametersAndUnderscoreTypes` is a little on the long side ...

**Comment by 7sharp9** [comment]
forget why, I think I patched externally
