### ISSUE TITLE
High CPU for SimpleSourceCodeServices.Compile(string[] argv)

### ISSUE THREAD

**Issue by henrid** [fsharp/FSharp.Compiler.Service#408]
Hi all, 

I am using the SimpleSourceCodeServices.Compile(string[] argv) method to compile our dynamically generated F# code (and outputting to a DLL on disk). After some time, my service that is hosting the library will begin to hit 100% CPU and continue until I restart it. Has anyone seen anything familiar? When you say "host" the fsc process, what is that actually doing? Any documentation I can look at? 

Thanks,
Dan

**Comment by henrid** [comment]
On a similar note, what are the thread safety guarantees for accessing that singleton?

**Comment by henrid** [comment]
Hi Dave @7sharp9,
When will this new package be released and when can I access? What will the package do to address the issues I saw?

**Comment by 7sharp9** [comment]
GitHub seems to be cross linking unrelated things.  Those commits are to my personal fork.  Completely unrelated.

**Comment by dsyme** [comment]
@henrid A few questions

- Are you using Windows (.NET) or Linux/Mac (Mono)? 

- If Windows, how much code are you generating and what is your memory usage?  If you are generating a lot of code you might consider using collectible code (see bottom of [this guide](http://fsharp.github.io/FSharp.Compiler.Service/interactive.html) )

The singleton should not be accessed concurrently from multiple threads.

Cheers
don

**Comment by henrid** [comment]
@dsyme,
* Windows .NET
* Many smaller files repeatedly. Since I am using the hosted fsc, is that option still applicable?

That would explain the weird type errors I was getting. I was using the singleton from multiple threads. Is there a way to parallel the compilation beyond running multiple processes?

**Comment by dsyme** [comment]
@henrid Ah right, collectible code is only relevant to F# Interactive code generation. Do you dynamically load the assemblies generated into the same process?  That will get expensive after enough iterations - you will ultimately need some way to reclaim resources used (GC, or new processes, or new app domains etc.)

Parallelized compilation would need either a new process or a new app domain. There are unfortunately a couple of globals (particularly the error logger) which are used by FCS. These are isolated to the compilation thread (which in this case is the calling thread, and for the FSharpChecker is a dedicated Reactor thread). But you can't currenly have multiple compilation threads in the same process.

cheers
don

**Comment by henrid** [comment]
@dsyme I'm only using it to write -- the assemblies won't be loaded in that same process. It's very weird but given my misuse of the Compile from multiple threads, maybe we can chalk it up to that. I'm okay to close this.

**Comment by dsyme** [comment]
OK - if you find a consistent repro please reopen
