### ISSUE TITLE
Possible enhancement: Smart suggestions for F# code completion lists (and parameter completion for partial functions)

### ISSUE THREAD

**Issue by mfalda** [fsharp/FSharp.Compiler.Service#409]
Since F# has a strong type system would be possible to enhance FCS completions by moving the most relevant values to the top according to the context of the current code?
To have an idea, see [Netbeans Smart Suggestions](https://netbeans.org/kb/73/java/editor-codereference.html#codecompletion).
## Example

For example, given the following definitions:

``` F#
let a = 4
let b = 5
let c = a * b
let d = 3.7
let e = "a"

let f (x: int) = // infer f :: int -> float
    float x / 2.0
```

when trying to complete the expression

``` F#
printfn "%f"
```

the list should first suggest "d" or "f", according to the desired format.

Once opted for "f", the next list should prioritize "a", "b" or "c" for the expression

``` F#
printfn "%f" f
```

In this way the programming experience in F# would acquire another flavor, a sort of tutoring for composing types.
## Previous discussions

I have proposed my idea to the [atom-fsharp project](https://github.com/fsprojects/atom-fsharp/issues/106#issuecomment-132963989), but they are not sure whether this is already feasible without acting upon FCS. In particular a user told me that "**this is parameter completion for partial functions**, [and] this is not supported anywhere at present": would it be feasible?
I also considered that this idea could weaken the F# inference engine safeness from a user point of view: For example the user could have made a mistake in the "printfn" format and this system would confirm his error; in this particular scenario a certainty degree or a flag could be added (for instance in order to render a question mark).
## A little script

I want to show you also a simple script I have tried:

``` F#
#r "FSharp.Compiler.Service.dll"

open System
open System.IO
open Microsoft.FSharp.Compiler.SourceCodeServices
open Microsoft.FSharp.Compiler


// Create an interactive checker instance
let checker = FSharpChecker.Create()

// Split the input & define file name
let filename = "smart_compl.fsx" // my example script
let inputLines = File.ReadAllText filename

let projOptions =
    checker.GetProjectOptionsFromScript(filename, inputLines)
    |> Async.RunSynchronously

// Perform parsing and checking
let parseResults, checkFileAnswer =
    checker.ParseAndCheckFileInProject (filename, 0, inputLines, projOptions)
    |> Async.RunSynchronously

let checkFileResults =
    match checkFileAnswer with
    | FSharpCheckFileAnswer.Succeeded(res) -> res
    | res -> failwithf "Parsing did not finish... (%A)" res

let partialAssemblySignature = checkFileResults.PartialAssemblySignature

let moduleEntity = partialAssemblySignature.Entities.[0]
for fnVal in moduleEntity.MembersFunctionsAndValues do
    printfn "%A (%A)" fnVal fnVal.FullType // (or  fnVal.FullType.TypeDefinition.DisplayName to match with the tooltips signatures)

// Get tool tip at the specified location (??)
let tip = checkFileResults.GetToolTipTextAlternate(10, 18, inputLines, ["f"], 0)
printfn "%A" tip
```

whose output is

```
val a (type Microsoft.FSharp.Core.int)
val b (type Microsoft.FSharp.Core.int)
val c (type Microsoft.FSharp.Core.int)
val d (type Microsoft.FSharp.Core.float)
val e (type Microsoft.FSharp.Core.string)
val f (type Microsoft.FSharp.Core.int -> Microsoft.FSharp.Core.float)
Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Compiler.SourceCodeServices.FSharpToolTipText]
```

I am not able to get the tooltip value, however in this script I have obtained a list of typed declarations that could be filtered according to the signature of the function near the cursor ("f" in the example, that is "val f: x:int ->float", easily parseable). It would be easier if there was a way to obtain that particular context information used by the syntax checker to signal a parameter type mismatch.

**Comment by dsyme** [comment]
Closing old feature request as part of spring cleaning - we are moving the mainline of development of FCS to the unified repo (currently Micrsosoft/visualfsharp though may be renamed to Microsoft/fsharp or fsharp/fsharp) -  some aspects of this feature are available through recent work done in improving FCS in the unified repo.
