### ISSUE TITLE
Improve type tooltips for types emitted from type providers

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Compiler.Service#41]
The tooltips usually show something like `JsonProvider<...>.TypeA`. When you're trying to refactor code and need to put type annotation, this is not every useful, because you can't put this type there. It would be better if it shown a type alias if there is one (there usually is in type provider usage), otherwise it's very confusing for new users.

Background: http://stackoverflow.com/questions/21402829/type-annotation-for-using-a-f-typeprovider-type-e-g-fsharp-data-jsonprovider/21406103

This also affects VS, but if we could fix it here (which would then propagate to XS), we could later try the VS team to get it also

**Comment by dsyme** [comment]
Closing old discussion
