### ISSUE TITLE
The initial binding of identifiers beginning with an underscore (let _bla = ...) does not appear in GetAllUsesOfAllSymbolsInFile()

### ISSUE THREAD

**Issue by yever** [fsharp/FSharp.Compiler.Service#422]
I got here while trying to look into a bug in [Visual F# Power Tools](https://github.com/fsprojects/VisualFSharpPowerTools) (see: [#1032](https://github.com/fsprojects/VisualFSharpPowerTools/issues/1032) there). It fails to highlight an identifier named `_`, or any other beginning with an underscore.

I tried to debug it and found out that FSharp.Compiler.Service isn't returning an instance of the symbol pointing to its initial binding (the 'let' statement) in GetUsesOfSymbolInFile() if it begins with an underscore, but otherwise it does.

I made a gist reproducing this behavior with an FSI script: [here](https://gist.github.com/yever/b1555bc58212e1b44850). The script follows the [tutorial](https://fsharp.github.io/FSharp.Compiler.Service/project.html) and uses GetAllUsesOfAllSymbolsInFile() which fails the same way.

EDIT: Unlike my first impression, it seems that backticks are irrelevant.

**Comment by dsyme** [comment]
I think this has been fixed. Spring cleaning old feature requests and suggestions in preparation for repo unification
