### ISSUE TITLE
FCS chokes on C# events

### ISSUE THREAD

**Issue by Vidarls** [fsharp/FSharp.Compiler.Service#423]
This is basically me wining cause I can't get Fsharp formatting to do my API docs if I use normal C# events. 

This FSF issue has quite a bit of details: tpetricek/FSharp.Formatting#271 and it loks from the discussion there that the underlying cause is FCS not handling the event types of C#.

Now it might be that it is outside the scope of FCS to handle this, but I'm trying my luck none the less.

**Comment by dsyme** [comment]
Fixed in FCS 1.4.0.6
