### ISSUE TITLE
Event don't seem to have properties that indicate them as events

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#427]
Given the following:

```fsharp
type MyType() =
  let event1 = new Event<_>()
  [<CLIEvent>]
  member x.MyEvent1 = event1.Publish
```

None of the symbols returned from this snipped indicate that it is an event, this is not specific to the latest version.

In the case of `x.MyEvent1` these are the event related properties:
![screen shot 2015-10-01 at 08 43 47](https://cloud.githubusercontent.com/assets/588746/10215385/fd085d9e-6818-11e5-8bce-cc74220d121d.png)

In fact none of the symbols returned have event related properties set, i.e. the add/remove handlers etc all have properties like above.

**Comment by dsyme** [comment]
Fixed by #439
