### ISSUE TITLE
StackOverflowException generating doc with ref to Paket.Core

### ISSUE THREAD

**Issue by dedale** [fsharp/FSharp.Compiler.Service#429]
Steps to reproduce:
- ProjectScaffold
- Add a csproj in src
- Reference Paket.Core in csproj (with paket add)
- build
- fsi fails with SOE

```
...
Copying styles and scripts: D:\prog\git\hub\dedale\Foo\docs\output\content\img\github.png
Creating D:\prog\git\hub\dedale\Foo\docs\output\reference

Process is terminated due to StackOverflowException.
Running build failed.
Error:
System.Exception: generating reference documentation failed
   at FSI_0001.Build.clo@185-19.Invoke(Unit _arg11)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
```

cc @forki @tpetricek

**Comment by dsyme** [comment]
#473 is a possible fix. Could you perhaps add a link to a github project that has the problem (rather than the repro steps above)

**Comment by dsyme** [comment]
I'm closing this as a possible fix has been submitted  - please try it out and re-open if needed

**Comment by dedale** [comment]
Sorry I did not have time to check your fix. I'll re-open if needed. Thx
