### ISSUE TITLE
Exposing XML doc positions in parser AST

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#449]
We in VFPT need this info https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/ast.fs#L44 to implement XML doc comments outlining feature. What's the best way to expose it? Ideally we need ranges for all kinds of comments (`//`, `///`, `(* *)`).

/cc @dsyme

**Comment by cloudRoutine** [comment]
This would be a significant benefit for lots of F# tooling

**Comment by dkinitiate** [comment]
+1!
Trying to implement the outlining feature I first looked into trying to get xmldocs to work first. Unfortunately it looked like there wasn't enough region/range/position information publicly available.

**Comment by 7sharp9** [comment]
Having comments and ranges in the AST would be nice, the Roslyn AST is a lot more flexible and informative.  I think I raised an issue to add them.

**Comment by dsyme** [comment]
Yes, good idea....

If someone wants to take a crack at this I can walk you through it via a skype screen share session or IM

**Comment by cloudRoutine** [comment]
I can do it next week. How should we coordinate?

**Comment by dsyme** [comment]
What timezone are you on? Suggest Tue 5pm BST on skype. Send me your ID via my github email

**Comment by cloudRoutine** [comment]
I put the time down on my calendar but forgot to message you to confirm. Sorry about that. If that time is unavailable there another time you prefer?
Your github email isn't shown on your profile page so here's my info -
I don't use skype so I'm not sure if it's `jared.hester` or `jared.hester@gmail.com`

**Comment by dsyme** [comment]
Email is donsyme attt fastmail dottt fm

**Comment by dsyme** [comment]
Let's aim to do this at 5pm GMT on Thursday?

**Comment by vasily-kirichenko** [comment]
We have working Structure Service in VFT repo, this issue is obsolete.
