### ISSUE TITLE
Should EnclosingEntity throw, why not use options here?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#451]
RE: https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/Symbols.fs#L1259

Ive fallen down this pitfall trap several times, seems a shame to have to handle FCS properties with unilateral try/catch blocks...

**Comment by 7sharp9** [comment]
This is used elsewhere:
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/Symbols.fs#L842-L847

**Comment by 7sharp9** [comment]
@dsyme A PR to wrap an enclosing Entity with an option?

**Comment by dsyme** [comment]
@7sharp9 That would be great

**Comment by dsyme** [comment]
This now uses an option
