### ISSUE TITLE
FSharpField.IsMutable = true for BCL enum cases

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#452]
For `InvariantCultureIgnoreCase` in
```fsharp
let _ = System.StringComparison.InvariantCultureIgnoreCase
```
FCS returns `FSharpField` with `IsMutable` property set to `true`:
![image](https://cloud.githubusercontent.com/assets/873919/10606715/6fa9c116-773d-11e5-8d57-441dbd99232a.png)

`StringComparison` is defined in BCL:
```csharp
namespace System{
    
    [Serializable]
    [System.Runtime.InteropServices.ComVisible(true)]
    public enum StringComparison {
        CurrentCulture = 0,
        CurrentCultureIgnoreCase = 1,
        InvariantCulture = 2,
        InvariantCultureIgnoreCase = 3,
        Ordinal = 4,
        OrdinalIgnoreCase = 5,
    }
}
```
For enums defined in F# `IsMutable` = `false`. 
It results with coloring problems in VFPT:
![image](https://cloud.githubusercontent.com/assets/873919/10606855/5008b53c-773e-11e5-9cfd-2f1c27e729a5.png)

**Comment by vasily-kirichenko** [comment]
I found a workaround for this, so no hurry to fix it in FCS.

**Comment by 7sharp9** [comment]
I recently got stung by this too :-(

**Comment by dsyme** [comment]
Fix submitted here, was quite easy https://github.com/fsharp/FSharp.Compiler.Service/pull/491
