### ISSUE TITLE
fsi.PrintLength has no effect with sequences

### ISSUE THREAD

**Issue by Korporal** [fsharp/FSharp.Compiler.Service#454]
Setting the print length in an interactive session works as expected when printing a list but seems to have no effect when printing a sequence.

e.g. executing these elicits very different results:

```
   fsi.PrintLength <- 50;;

   [1..50];;

   seq {1..50};;
```
It's not obvious to me why this would be so I'm considering it to be a bug.

**Comment by dsyme** [comment]
This is by design - sequences are drastically reduced in size since they are on-demand and sometimes slow to compute.   You should install a custom pretty printer (fsi.AddPrinter of fsi.AddPrintTransformer) if you want to change their printing.
