### ISSUE TITLE
FCS makes calls to kernel32.dll when running on OSX

### ISSUE THREAD

**Issue by nosami** [fsharp/FSharp.Compiler.Service#456]
https://github.com/fsharp/FSharp.Compiler.Service/blob/c1ca06144d8194000cf6b86f5f26bdc433ccaa7d/src/absil/ilread.fs#L169

<img width="1556" alt="screen shot 2015-11-03 at 15 08 51" src="https://cloud.githubusercontent.com/assets/667194/10911474/e61beab8-823c-11e5-9437-4dbd3457060f.png">

**Comment by 7sharp9** [comment]
Ive notices this a lot too, Its detrimental to performance on the x-plat compiler and tools.

**Comment by dsyme** [comment]
If possible please submit a PR to change this throw-and-catch to a conditional that detects whether we are running on Windows: https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/absil/ilread.fs#L3977
