### ISSUE TITLE
Failure getting expression for a provided method call

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#460]
I you have an erased type provider that generates a call to a method of an F# type, then try to get the expression from a checked project which uses this, there is an error `"A call to '...' could not be resolved`.

This is thrown by `Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrim`. It seems that coming from the TP, the call is represented as a `Tast.Expr.Op(TOp.ILCall ...)` but the type containing the method has F# metadata, so it will not represented by a `TILObjModelRepr` case when imported.

I have a minimal test project at https://github.com/Jand42/FCS-TP-error
Failing using `FSharp.Compiler.Service 1.4.2.1` and `FSharp.TypeProviders.StarterPack 1.1.3.76`

**Comment by dsyme** [comment]
Thank you for putting together such a clear repro for this.
