### ISSUE TITLE
Move to paket for nupgk creation

### ISSUE THREAD

**Issue by forki** [fsharp/FSharp.Compiler.Service#461]
In https://github.com/fsprojects/Paket/issues/1188#issuecomment-154372813 @7sharp9 describes that he can't create nuget packages for FCS on mono. If people are interested I can try to convert the package creation process to Paket, this would have a good chance to fix most mono issues.

**Comment by dsyme** [comment]
Yes please!

**Comment by forki** [comment]
do we also want to publish intermediate packages to appveyor like @dungpa suggested?

   "You can use FCS AppVeyor CI as NuGet source; the infrastructure has been in place. Just send a PR with changes to FCS repo and swap out NuGet feed. You can use your changes without any issue (see http://blog.ctaggart.com/2015/07/open-source-net-with-appveyor-nuget.html)."

**Comment by forki** [comment]
done in #462
