### ISSUE TITLE
Meaningful exception message needed from failed expression evaluation

### ISSUE THREAD

**Issue by andrew-vandenbrink** [fsharp/FSharp.Compiler.Service#469]
```
var session = Create(fsiExePath);
var option = session.EvalExpression(script);
```
An exception of type 'System.Exception' occurred in FSharp.Compiler.Service.dll but was not handled in user code

{"Evaluation failed"}

This exception message is meaningless and we need to be able to diagnose what is wrong with the script instead of receiving message "Evaluation failed"

**Comment by 7sharp9** [comment]
Errors would be sent to the output writer.

**Comment by andrew-vandenbrink** [comment]
That should be the case if my script write the error manually to the output

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/FSharp.Compiler.Service/pull/475.  When the new nuget is published please use ``session.EvalExpressionNonThrowing(script)``
