### ISSUE TITLE
Slow performance calling FsiEvaluationSession.Create

### ISSUE THREAD

**Issue by andrew-vandenbrink** [fsharp/FSharp.Compiler.Service#471]
```
FsiEvaluationSession.Create(config, arguments, inStream, outStream, errStream, option);
```

I need to create more than one fsi session, calling that method each time took 500ms, sometimes more than 1s

For comparison,
It is much faster to call powershell invoke where the script querying database than creating fsi session.

**Comment by andrew-vandenbrink** [comment]
```
let x = 10
let y = 5
(x*y).ToString()
```
That script take seconds to run and uses 25% cpu of 4 core

**Comment by dsyme** [comment]
Did you NGEN your application (e.g. ngen install FSharp.Compiler.Service.dll).  If you do that, invocations should be faster.

**Comment by andrew-vandenbrink** [comment]
The workaround at this moment is to call this during application initialization
```
//Create dummy evaluation
var x=FsiEvaluationSession.Create(config, arguments, inStream, outStream, errStream, option)
.EvalExpression(@"let x=1+1
x").ReflectionValue;
```

This will somehow cache (basically ngen on the fly) and make the execution much more smooth

**Comment by dsyme** [comment]
OK. This is expected behaviour if you don't NGEN your application - FSharp.Compiler.Service needs to be either jitted (which is the normal mode of use for most purpoess, but will occur an overhead on first invocation) or install-time-compiled (better startup performance, more like ``fsc.exe`` on Windows)
