### ISSUE TITLE
Failures on Mac (Mono master) and Max/Linux (Mono 4.05)

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Compiler.Service#477]
I've enabled a build matrix in #476 but there are failures

    https://travis-ci.org/fsharp/FSharp.Compiler.Service/jobs/94301490

@rneatherway If you get a chance to look that would be awesome.  The Mac+mono master  failure is in a recently adjusted part of the code

**Comment by rneatherway** [comment]
I think this is because the Mac version and old Mono are still populating the ChildProjectReferences correctly, so they now get duplicated. I can easily filter those out.
