### ISSUE TITLE
Tokenizer misses some input

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#481]
The following code (tokenizing **`#help;;`** ):

```
#r "FSharp.Compiler.Service.dll"

open Microsoft.FSharp.Compiler.SourceCodeServices
let sourceTok = FSharpSourceTokenizer([], "C:\\test.fsx")
let tokenizer = sourceTok.CreateLineTokenizer("#help;;")

let rec tokenizeLine (tokenizer:FSharpLineTokenizer) state =
  match tokenizer.ScanToken(state) with
  | Some tok, state ->
      // Print token name
      printf "%s " tok.TokenName
      // Tokenize the rest, in the new state
      tokenizeLine tokenizer state
  | None, state -> state

tokenizeLine tokenizer 0L
```

Will produce:

```
HASH SEMICOLON_SEMICOLON val it : FSharpTokenizerLexState = 32769L
```

The text after the # is missing completely!!

**Comment by 7sharp9** [comment]
Note `#time;;` is the same as is `#q;;`

For reference `#r "test.dll";;` works and has the following output:
```
> HASH WHITESPACE STRING_TEXT STRING_TEXT STRING_TEXT STRING_TEXT STRING SEMICOLON_SEMICOLON val it : FSharpTokenizerLexState = 32769L
```

**Comment by dsyme** [comment]
For better or worse the range of the ``HASH`` token in this situation is from 0 to 4, i.e. it includes the ``help``.  This is just how it is.

**Comment by 7sharp9** [comment]
?  I don't get tokenisation for #help or #time, anything after the # seems to be dropped unless #r

**Comment by dsyme** [comment]
In all those cases you get one token called HASH, and its range covers the range of the ``help`` token as well. It should all be considered one token covering all of ``#help``, just like ``HASH_IF`` covers ``#`` and ``if``

That's not exactly ideal though and the code that does the relevant transformations around ``#`` and ``#if`` [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/ServiceLexing.fs#L495) and [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/ServiceLexing.fs#L683) is an abomination - I have no idea who wrote this but it's seriously not happy.

**Comment by 7sharp9** [comment]
Ill check next week, but Im sure `#qu` would just project a HASH token of length 1, its not until you have the whole `#quit` typed in that the correct tokenisation would occur.  

It means that when you tokenise a line that currently looks like `#qu` if you look at the returned tokens it looks like the `qu` part does not exist, theres no semblance of an error of any remaining characters left in the line.

**Comment by dsyme** [comment]
Ah, yes, you didn't mention that case :)
