### ISSUE TITLE
Why do I need to reference FSCS in every downstream .NET project?

### ISSUE THREAD

**Issue by origfla** [fsharp/FSharp.Compiler.Service#487]
Diagram showing the dependencies between projects:
**Client application -> Internal Library -> External Library -> FSCS**

The external library
===============
I am using an external library in my project that uses FSCS. I then need to reference both the external library (no surprise) and FSCS (a little surprising) in my library.

My internal library
=============
A client application then re-uses my internal library and it turns out that I need to reference FSCS as a dependency (very very surprising) even though I didn't need to reference the external library as a dependency.

Other Info
========
- My client application does not fail to compile - instead the missing reference causes issues at runtime.
- Using version 1.3.1.2 (if relevant)

**Comment by dsyme** [comment]
What's the external library?  Does it's nuget package correctly list a dependency on the FCS package?  (The most common cause of a dependency is for documentation generation)

In any case this seems to be a bug in the configuration of the external library.  If it's using FCS then your code will certainly end up needing the DLL, but the external library package should list that dependency correctly.

**Comment by origfla** [comment]
The external project being used is:
https://github.com/eiriktsarpalis/QuotationCompiler

**Comment by dsyme** [comment]
It seems to be configured properly on nuget http://www.nuget.org/packages/QuotationCompiler/0.0.7-alpha

What package manager do you use to reference the package?  Nuget.exe or Paket.exe?  Or Visual Studio nuget?   The package manager tooling should add the dependencies automatically.  If it doesn't I'd say that's a limitation of the package manager - I'm pretty sure Paket would add the reference to the dependency correctly.

In any case this isn't an F# COmpiler Service bug

**Comment by dsyme** [comment]
(closing as it's not an FCS bug AFAIK)

**Comment by origfla** [comment]
@dsyme  thanks for taking a look. It doesn't sound like a bug but perhaps I didn't ask my question clearly enough:

I can understand why my internal library needs a reference to FCS - FCS gets downloaded automatically with nuget.

**What I don't understand** is (irrespective of package manager) why does my client application then need its own reference to FCS if it already references the internal library (which has the FCS reference)?

Flag as question and not bug.

**Comment by dsyme** [comment]
Hi @origfla That's a good question.  It's probably because some references to FCS types or other metadata escape as part of the public API of the QuotationCompiler library you are using.

**Comment by eiriktsarpalis** [comment]
@dsyme The public QuotationCompiler API indeed exposes F# Untyped ASTs
