### ISSUE TITLE
Big performance problems in 1.4.2.1

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#488]
See https://github.com/fsprojects/VisualFSharpPowerTools/issues/1280 

VFPT has been rolled back to 1.4.2

**Comment by nosami** [comment]
I was curious about this, so I tried both 1.4.2 and 1.4.2.1 with Xamarin Studio. I couldn't perceive any difference between the two versions.

I did however notice something odd though that both versions exhibited. The initial parse for a file in a project can be slow (but understandable). Subsequent parses for files within the same project are fast. _But_ - if you parse a file in a different project, and then parse again a file in the first project, the next parse is slow. It behaves as though the cache for the project has been dropped.

- Project 1, File 1 (slow)
- Project 1, File 2 (fast)
- Project 1, File 3 (fast)
- Project 2, File 1 (slow)
- Project 2, File 2 (fast)
- Project 2, File 3 (fast)
- Project 1, File 4 (slow)
- Project 1, File 5 (fast)
- Project 2, File 4 (slow)

Is this expected? Should we be using a separate FCS instance for each project to mitigate this?

**Comment by nosami** [comment]
A simpler way of putting this -  _every_ time I parse a file in a project that is in a different project to the last parsed file, it is slow,

**Comment by nosami** [comment]
I tried versions 1.4.0.8 and 1.4.0.2 to see if this is a recent regression, but they behave the same way.

The cache only appears to be working for one project at a time.

**Comment by dsyme** [comment]
OK, thanks for the info. I will try to confirm it, and, even more importantly, pin down the expected behaviour in a unit test.

**Comment by dsyme** [comment]
@nosami Which commit id of the VFPT code were you using when you did those checks?  The head of master?

**Comment by nosami** [comment]
I wasn't using VFPT... I was testing FCS versions with Xamarin Studio

**Comment by dsyme** [comment]
Ah yes, thanks.  I think this must be a separate issue to the one reported by @vasily-kirichenko - (possibly it's an issue in XS not FCS)

**Comment by dsyme** [comment]
BTW assuming the issue is conformed (between 1.4.2 and 1.4.2.1), the one reported by @vasily-kirichenko could only really be due to this: https://github.com/fsharp/FSharp.Compiler.Service/commit/add00eaf0789cde563ffd26163037071bae8ab97

**Comment by nosami** [comment]
I suspect FCS because I can parse the same file twice with the same parameters and get completely different parse times depending on whether or not the last parsed file was in the same project.

**Comment by dsyme** [comment]
FCS 1.4.2.2 is now available.

**Comment by dsyme** [comment]
@nosami Your issue sounds like a different one, and I suspect that there is some problem with the options being passed by Xamarin Studio to FCS.

Could you open a new issue on this, and include links showing the FSharpProjectOptions being passed in the requests?
