### ISSUE TITLE
Parsing is slow when alternating between projects

### ISSUE THREAD

**Issue by nosami** [fsharp/FSharp.Compiler.Service#493]
As discussed here https://github.com/fsharp/FSharp.Compiler.Service/issues/488. I've tried 1.4.2.2 and the same problem is there. 

I [recorded a screencast](http://screencast.com/t/Dt4usYG6JAk) highlighting the issue. You can see that when I switch projects to a previously parsed project that the parse step is slower than expected. I think it could related to the project options too, but not sure exactly what. We cache the project options, so that GetProjectOptionsFromProjectFile is only called once per project.

The project options are here https://gist.github.com/nosami/c15cc73f41bde56b1240 These are the project options for the Xamarin Studio F# plugin and test project.

**Comment by dsyme** [comment]
Any chance you could redo the screencast so that you switch back and forth between the same files in the two projects (in the screencast you switch back to a different file - one further down the list of files). thanks

BTW this table needs updating in the xamarin addin: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/bfdf8253776fd299b6d878970417a1d9334c1fa3/MonoDevelop.FSharpBinding/FSharpProject.fs#L24

**Comment by dsyme** [comment]
Also it might be good to double check that InvalidateConfiguration is not being called: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/bfdf8253776fd299b6d878970417a1d9334c1fa3/MonoDevelop.FSharpBinding/FSharpProject.fs#L35, though it doesn't look like it would be.

**Comment by dsyme** [comment]
Hmmm... It looks like the "ProjectFileName" field is inconsistently populated in that data, see

**Comment by nosami** [comment]
I checked that InvalidateConfiguration isn't being called - it isn't. [Here](http://screencast.com/t/X5jKghT7N) is a screencast with me alternating between the same 2 files each time. 
It's not as obvious because the files are already highlighted, but you can see the parse time by looking at the log.

The ProjectFileName does look wrong. I'll take a look at that.

**Comment by nosami** [comment]
It was the wrong ProjectFileName that was causing the slow parses. I'm a little annoyed with myself for not spotting that earlier :)

Thanks!

**Comment by dsyme** [comment]
Great to know!

**Comment by rneatherway** [comment]
Just to double-check, that isn't a problem with the project cracking I need to fix?

**Comment by nosami** [comment]
@rneatherway No, it was a bug that I introduced in Xamarin Studio. You might want to [normalise the paths](https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/master/CompilerService/Program.fs#L29-L41) everywhere though.

**Comment by 7sharp9** [comment]
At the moment we are using our own cracking, so that we can have a quick turn around on issues.
