### ISSUE TITLE
Why is there no GetBackgroundCheckResultsForProject ?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#496]
There are methods for single file check and parse results but no project results.
GetBackgroundCheckResultsForFileInProject
GetBackgroundParseResultsForFileInProject

Im might be missing something but having an event on the checker `ProjectChecked : IEvent<string>` would imply that I might want to get the completed check results now I know they are available.  

This is particularly important for the global search feature where I need to rely on full project check results as soon as they become available. 

//cc @dsyme

**Comment by dsyme** [comment]
There is - it's called [``ParseAndCheckProject``](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fsi#L508).  This drives the background build forward.

There's also a ``ProjectChecked`` event here: https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fsi#L659.  Calling ``ParseAndCheckProject`` should be fast in the handler for that event.

**Comment by 7sharp9** [comment]
Thats actually what Im doing, the other GetBackground... calls make it a little unclear on usage

**Comment by 7sharp9** [comment]
Interestingly, if I call `ParseAndCheckProject` in the `ProjectChecked` event handler it seems to causes the checker to not complete any further `ParseAndCheckFileInProject` which is a pretty terminal condition :-(

**Comment by dsyme** [comment]
Yes, I think that could happen

**Comment by dsyme** [comment]
If you think the API could be improved here please reopen.  It feels like it can be, especially to support incremental update of search results.  But also allow re-rentrancy

**Comment by 7sharp9** [comment]
I was going to prepare some kind of unit test failure tomorrow to illustrate the issue, I couldn't see thread specific issues, although Ive not spent too long looking, I guess I was looking in the wrong place ...

**Comment by 7sharp9** [comment]
@dsyme Ok so its definitely an issue, I ran `ParseAndCheckProject` inside the UI thread and theres no no deadlock.

**Comment by 7sharp9** [comment]
Im assuming that this issue will be present in all the events in the checker as they will be being notified from the thread in the reactor mailbox processor?
