### ISSUE TITLE
SimpleSourceCodeServices.Compile performance

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#505]
Using `SimpleSourceCodeServices().Compile` for building a project from command line args can be much slower than running `fsc.exe` with the same arguments. I have seen three times as much.

I know that this probably caches some parse/type check results, because calling `checker.GetProjectOptionsFromCommandLineArgs` on the same args then `checker.ParseAndCheckProject` after is relatively faster then calling it without the `Compile` first.

Still, I would like some investigation. I will later post here some measurements, a test project and observations from profiling.

**Comment by rneatherway** [comment]
Are you running on windows? If so then fsc.exe is likely ngenned, and FCS is not. This means that you experience the jit overhead of the bulk of the compiler on each invocation. It is possible to ngen FCS as well if this performance is important to you.

**Comment by Jand42** [comment]
I have tested on Windows with this script now. https://gist.github.com/Jand42/4766d0b68eecd29ed3bb
It runs the FscExe.exe that is provided as a sample for FCS and compares it to fsc.exe performance.

Results from a single run, which are typical, even though I tried FCS at multiple branches, and using locally built FCS.dll or switching to one from NuGet.

Building with original fsc
Running time: 00:00:03.9624926, Exit code: 0
Total processor time: 00:00:05.6406250
Building with FCS 4.0
Running time: 00:00:10.8078210, Exit code: 0
Total processor time: 00:00:10.6562500
Building with FCS 4.5
Running time: 00:00:10.7244343, Exit code: 0
Total processor time: 00:00:10.5937500

@rneatherway Thanks for the suggestion, I already tried ngen before, it maybe causes a small improvement, but not really noticable. I have to collect more measurements, single ones can fluctuate.

**Comment by Jand42** [comment]
I will also test with a variety of projects and warning level settings and other configurations to see if I can find what has a big impact on compilation time.

**Comment by dsyme** [comment]
@Jand42 That looks like an NGEN issue.  Make sure you NGEN 32-bit and 64-bit

**Comment by Jand42** [comment]
Thanks, I did use the wrong ngen (assumed that the VS15 Developer Command Prompt resolves "ngen" to the .NET 4.0 version, but I was wrong).

Tests with correct ngen and version 2.0.0.2 are indeed much better:

Building with original fsc
Running time: 00:00:03.9728593, Exit code: 0
Total processor time: 00:00:05.8125000
Building with FCS
Running time: 00:00:04.8491650, Exit code: 0
Total processor time: 00:00:04.6250000
