### ISSUE TITLE
Double tick bindings have a range that represents the full ticked name

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#507]
e.g
```
let ``thing``() = ()
```
Has a range of:

RangeAlternate	(1,4-1,16) /doublequotebug/Program.fs IsSynthetic=False	Microsoft.FSharp.Compiler.Range.range

Yet the compiled name is just `thing`.  

The means thats theres no way to know that the range is not representative of the symbols name.  Which in tern means we get issues like this:

![screen shot 2016-01-06 at 11 00 10](https://cloud.githubusercontent.com/assets/588746/12141116/b80a277a-b464-11e5-8b78-019cbae9159e.png)

Where ranges cannot be transformed back into screen coordinates.

For reference heres some of the symbol properties:

![screen shot 2016-01-06 at 11 02 21](https://cloud.githubusercontent.com/assets/588746/12141159/196bb31c-b465-11e5-9d87-68312648394b.png)

**Comment by dsyme** [comment]
I think this is by design.  The symbol range should include the ticks - it would somehow be odd if it didn't.
