### ISSUE TITLE
[Feature Request] Add Compile* methods from SimpleSourceCodeServices to SourceCodeServices to unify API

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#516]
#362 Discusses this

Essentially Compile and CompileToDynamicAssembly methods should be brought over from SimpleSourceCodeService to SourceCodeServices.

@dsyme In #362 you mention arguments should be textual to conform with the rest of the API, which methods were you referring to?

Also to provision a PR to add this feature would you be happy with adding the compile helpers to a module within Services.fs so that SimpleSourceCodeServices and SourceCodeServices share the common implementation?

**Comment by dsyme** [comment]
Closing as we don't need to track this with an issue.  We just need to do it :)
