### ISSUE TITLE
ProjectChecked event raised from FSharpChecker will return an invalid filename after a script file is checked.

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#517]
If a script file `myscript.fsx` for example is checked via `FSharpChecker.ParseAndCheckProject` then an event is raised where the name of the project that has been checked in the event is `myscript.fsx.fsproj`

**Comment by dsyme** [comment]
Could you add a repro? Thanks

**Comment by dsyme** [comment]
Closing since no repro provided...
