### ISSUE TITLE
Arrays not getting caught by BasicPatterns.NewArray

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#526]
It seems some array types are not getting caught by `BasicPatterns.NewArray` but `BasicPatterns.Const`. I've found that's the case at least for `ushort[]` and `byte[]`.

**Comment by dsyme** [comment]
That's actually by-design I think.  These are special cases in the F# compiler to propagate very large constant arrays like the tables used in FsLexYacc parsers and lexers.  Matching NewArray would explode a 1MB array into 1 million FSharpExpr values.

So can you use BasicPatterns.Const ok?

thanks!
don

**Comment by alfonsogarciacaro** [comment]
Yes, that's not a problem :+1: I just wanted to notify it in case it was not known. Thanks for reply, Don! I'll close the issue then.
