### ISSUE TITLE
I want to get fields defined in C# from FSharpEntity.

### ISSUE THREAD

**Issue by hafuu** [fsharp/FSharp.Compiler.Service#532]
There is no way to get fields defined in C# (ex. System.Int32.MaxValue).
On the other hand, It is able to get F# fields (like struct defined in F#, record) by `FSharpEntity.FSharpFields`.

There is also a way to use reflection, but it can not get the F# type name of field signature.
For example, option is compiled as FSharpOption by CompiledNameAttribute.

**Comment by dsyme** [comment]
Closing as duplicate of https://github.com/fsharp/FSharp.Compiler.Service/issues/235
