### ISSUE TITLE
Necessary references to retrieve AST from script files (fsx)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#535]
According to the [docs](https://fsharp.github.io/FSharp.Compiler.Service/typedtree.html), in order to get the AST from a F# script file, we must use `FSharpChecker.GetProjectOptionsFromScript` first. This method adds many references by default to the project options (see image) and there's been reports that these references fail in some machines (see https://github.com/fsprojects/Fable/issues/35). I've tried removing these "core" references and the AST can still be retrieved. So te question is: is it safe to remove these references when we only want to retrieve the AST? And also, is there an easy way to distinguish core references from custom ones? (those set explicitly by the user with `#r "..."`)

<img width="867" alt="screen shot 2016-02-25 at 14 50 13" src="https://cloud.githubusercontent.com/assets/8275461/13321789/725b4814-dbd1-11e5-9175-d93219dd91a5.png">

**Comment by alfonsogarciacaro** [comment]
I have closed the issue in Fable as it's probably better to update F# in the failing machines that messing around with the script references, so this is not necessary any longer.

**Comment by davidpodhola** [comment]
Note unfortunately this applies to the final application too see https://github.com/fsprojects/Fable/issues/58. I think the final application should work without F# installed.

**Comment by alfonsogarciacaro** [comment]
That would be ideal, yes. But probably we need to wait unit there's a CoreCLR version of the compiler services.
