### ISSUE TITLE
Class constructor's FSharpSymbol is not the same on definition and calling sites

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#536]
For this example:

``` fsharp
type private PrivateClass() = class end
let _ = PrivateClass()
```

The following code:

``` fsharp
let symbolsComparer =
        { new IEqualityComparer<FSharpSymbol> with
              member __.Equals (x, y) = x.IsEffectivelySameAs y
              member __.GetHashCode x = x.GetHashCode() }

let dic = Dictionary symbolsComparer

for su in symbolsUses do
    let symbol = su.SymbolUse.Symbol
    match dic.TryGetValue symbol with
    | true, uses -> dic.[symbol] <- su :: uses
    | _ -> dic.[symbol] <- [su]
```

Produces the following results in debugger:
![image](https://cloud.githubusercontent.com/assets/873919/13522727/4e003786-e202-11e5-8f88-c22c3685923d.png)

According to `IsEffectivelySameAs` xml doc, all three symbols (the type itself, the default ctor definition and the ctor call) should be considered as same: https://github.com/fsharp/FSharp.Compiler.Service/blob/81b834ca6b699c6d057dedfb7152264323c40da0/src/fsharp/vs/Symbols.fsi#L71-L73

**Comment by dsyme** [comment]
I'm not sure this is a bug - GetHashCode is not documented to be a suitable hash code for IsEffectivelySameAs, i.e. we don't say that ``IsEffectivelySameAs(x1,x2) implies GetHashCode(x1) = GetHashCode(x2)``

**Comment by vasily-kirichenko** [comment]
I don't even remember what it all about.
