### ISSUE TITLE
BasicPatterns.NewDelegate shows same value for different arguments

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#539]
Please find below a sample method and the generated AST for its body:

```
let makeDelegate f = System.Func<int,int,int> f

NewDelegate
  (type System.Func<Microsoft.FSharp.Core.int,Microsoft.FSharp.Core.int,Microsoft.FSharp.Core.int>,
   Lambda
  (val delegateArg,
   Lambda
  (val delegateArg,
   Application (Value val f,[],[Value val delegateArg; Value val delegateArg]))))
```

The problem here is that the two automatically generated arguments use the same value `delegateArg`. In other cases of automatically generated closures, arguments are created correctly with different names. 

Now it's time to cry for a little help: whenever I try to compile somewhat complex code I'm finding cases like this one which makes the AST not 100% reliable to compile F# to other platforms. This is a pity because having access to the typed AST it's otherwise a great feature. I would really appreciate if I could get some feedback on these issues: what to expect about the difficulty to fix them, some guidance on how to identify them myself...

Thanks a lot in advance!

**Comment by dsyme** [comment]
Yes, we totally need to get these fixed :)  TBH I think you're flushing out the last few problems with the typed AST - but we need to nail all these corner cases
