### ISSUE TITLE
Results of multiple calls to active pattern are always bound to variable with same name

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#541]
This is somehow similar to #539, if I have the following code:
```fsharp
type Comment = { author: string; text: string }
    
let (|NonEmpty|_|) (s: string) =
    match s.Trim() with "" -> None | s -> Some s  

let test x =
    match x with
    | {author=(NonEmpty author); text = (NonEmpty text)} ->
        {author=author; text=text}
    | _ -> failwith "TODO"
```

The generated AST for the body of method `test` is:
```
DecisionTree
  (Let
  ((val activePatternResult,
    Call
  (null,val |NonEmpty|_|,[],[],
   [FSharpFieldGet (Some Value val x,type Test.Comment,field author)])),
   IfThenElse
  (UnionCaseTest
  (Value val activePatternResult,
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.string>,Some),
   Let
  ((val activePatternResult,
    Call
  (null,val |NonEmpty|_|,[],[],
   [FSharpFieldGet (Some Value val x,type Test.Comment,field text)])),
   IfThenElse
  (UnionCaseTest
  (Value val activePatternResult,
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.string>,Some),
   DecisionTreeSuccess
  (0,
   [UnionCaseGet
  (Value val activePatternResult,
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.string>,Some,
   field Value);
    UnionCaseGet
  (Value val activePatternResult,
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.string>,Some,
   field Value)]),
   DecisionTreeSuccess (1,[]))),
   DecisionTreeSuccess (1,[]))),
   [([val author; val text],
     NewRecord (type Test.Comment,[Value val author; Value val text]));
    ([],
     Call
  (null,val failwith,[],[type Test.Comment],
   [Const ("TODO",type Microsoft.FSharp.Core.string)]))])
```

The results of the calls to the active pattern `NonEmpty` are both bound to a variable with the same name: `activePatternResult`. Because of this the variables cannot be distinguished when interpreting the AST.

**Comment by dsyme** [comment]
@alfonsogarciacaro I believe that in general variables in the typed expression tree should be distinguished by object identity rather than purely by string name.  At least, that's the intention. 

Making string names more unique in cases like this is still valuable, but it's not always going to work,... :)

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip, Don! Telling variables apart by object identity rather than by name shouldn't be difficult in Fable. Just because there is the `IsEffectivelySameAs` method I assumed comparing values by identity was not enough and that's why I was using the name instead.

**Comment by dsyme** [comment]
@alfonsogarciacaro That method is there mostly to correlate symbols in signature files with symbols in implementation files.  But yes, we need to check that comparing by object identity is actually working correctly!
