### ISSUE TITLE
Losing operator call when one of operands is application of a partially applied function

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FSharp.Compiler.Service#544]
This code:

```
let f x y = x+y
let g = f 1
let h = (g 2) + 3
```

Produces TAST without the last `(+)` call:

```
    Application
        (Call (null,val g,[],[],[]),[],[Const (2,type Microsoft.FSharp.Core.int)])
```

If I make `g` a normal function (i.e. `let g x = f 1 x`), the problem disappears.

If I make `g` a value (i.e. `let g = 5`), the problem disappears.

**Comment by dsyme** [comment]
It's possible this is the same bug as https://github.com/fsharp/FSharp.Compiler.Service/issues/543

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/FSharp.Compiler.Service/pull/549

**Comment by dsyme** [comment]
Fix is in 2.0.0.7

**Comment by fsoikin** [comment]
Awesome, thank you!

**Comment by fsoikin** [comment]
Hmmm, but now it generates some extraneous lambdas where none are required.

For example:

```
      let f x = x+5
      let g f y = f y
      let h = g f 42
```

2.0.0.7 produces:
```
Call
  (null,val g,[],[type Microsoft.FSharp.Core.int; type Microsoft.FSharp.Core.int],
   [Lambda (val x, Call (null,val f,[],[],[Value val x]));
    Const (42,type Microsoft.FSharp.Core.int)])
```

But 2.0.0.6 produces:
```
Call
  (null,val g,[], [type Microsoft.FSharp.Core.int; type Microsoft.FSharp.Core.int],
   [Value val f; Const (42,type Microsoft.FSharp.Core.int)])
```

**Comment by dsyme** [comment]
This is by design for first-class uses of all members and module-bound functions.  The expansion was always being applied when some arguments were present - it is now applied all the time even when no arguments are given.

**Comment by fsoikin** [comment]
Ok, thanks.
