### ISSUE TITLE
Debug flag not supported?

### ISSUE THREAD

**Issue by GeertVL** [fsharp/FSharp.Compiler.Service#546]
When I run the compile function in Microsoft.FSharp.Compiler.SimpleSourceCodeServices with the legit argument -g+ instead of --debug+ it gives me the following error:

commandLineArgs (0,1)-(0,81) parameter error Unrecognized option: '-g+'

Is it by design not supported or a bug?

**Comment by dsyme** [comment]
It's not a valid flag - e.g.

```
C:\GitHub\dsyme\visualfsharp>fsc -g+
Microsoft (R) F# Compiler version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

error FS0243: Unrecognized option: '-g+'

error FS0207: No inputs specified
```
