### ISSUE TITLE
Nuget for FSharp.Compiler.Interactive.Settings.dll?

### ISSUE THREAD

**Issue by nosami** [fsharp/FSharp.Compiler.Service#552]
Would it be ok to create a Nuget package for this assembly?

It would make things a lot simpler for me if I can directly reference the dll from a known location on all platforms. This would be to workaround the [useFsiAux bug](https://github.com/fsharp/FSharp.Compiler.Service/issues/127#issuecomment-208392104)

**Comment by tpetricek** [comment]
+1

**Comment by dsyme** [comment]
Spring cleaning old feature requests and suggestions in preparation for repo unification
