### ISSUE TITLE
Cannot ParseAndCheck on Windows without Visual Studio installed

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#567]
A user has reported Fable is not working on a Windows machine without Visual Studio installed. You can see the issue [here](https://github.com/fsprojects/Fable/issues/35#issuecomment-220797424). This is also related to #535.

#### Repro steps

Create a `FSharpChecker` with `keepAssemblyContents=true` on a Windows 10 machine with F# 4.0 installed stand-alone (no Visual Studio) and try to parse a script file (`.fsx`).

#### Expected behavior

The script is parsed and it's possible to access the AST for JavaScript compilation.

#### Actual behavior

The following error occurs when running `ParseAndCheckProject`: `Assembly reference 'System.Numerics.dll' was not found or is invalid: L1 (startup)`

#### Known workarounds

I recommended the user to [create a project (`.fsproj`) instead](https://github.com/fsprojects/Fable/issues/35#issuecomment-220817577), but then the following error appeared:

```
> Unable to find the file 'mscorlib.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
> Unable to find the file 'FSharp.Core.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
> Unable to find the file 'mscorlib.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
```

#### Related information 

* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: Windows SDK and Net 4.6 SDK
* Editing Tools (e.g. Visual Studio Version): No Visual Studio installed

**Comment by maun** [comment]
This was caused by missing Microsoft Build Tools 2015
