### ISSUE TITLE
FSCS not incorporating quotation literal type representation introduced in F# 4.0

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/FSharp.Compiler.Service#570]
FSCS seems to not be incorporating there recent [change to quotation literal representation](https://visualfsharp.codeplex.com/SourceControl/network/forks/dsyme/cleanup/contribution/7554) which was introduced in F# 4.0.

This can be seen [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/224132279fa8f215986cddc6225521d805098ae5/src/fsharp/fsi/fsi.fs#L986) and [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/224132279fa8f215986cddc6225521d805098ae5/src/fsharp/vs/SimpleServices.fs#L211).

While this may not produce any observable side-effects to most quotation literal use cases, it is responsible for the [bug described here](https://github.com/mbraceproject/MBrace.StarterKit/issues/18#issuecomment-97486420).

**Comment by dsyme** [comment]
This has been fixed in recent versions, the define has been activated since 3 days after this bug was reported  https://github.com/fsharp/FSharp.Compiler.Service/blob/9b802fa4ee9b3cf70b4e17bb6baa70a878c5c801/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj#L45
