### ISSUE TITLE
Some tests now failing for osx mono:latest only

### ISSUE THREAD

**Issue by ncave** [fsharp/FSharp.Compiler.Service#577]
Tests are now failing on osx mono:latest only (osx mono 4.2.2 is fine, linux mono:latest is fine).
I tried rebuilding the latest commit that passed osx mono:latest and it now fails, so the issue does not seem related to other commits.

**Comment by dsyme** [comment]
OK, we need to get a Mono bug entered ASAP.  Any links to logs for specific test failures?

**Comment by dsyme** [comment]
I started a NOP PR to tet against Mono latest: https://github.com/fsharp/FSharp.Compiler.Service/pull/578

**Comment by ncave** [comment]
@dsyme This is the log from your PR:
https://travis-ci.org/fsharp/FSharp.Compiler.Service/jobs/136778483

All 5 errors are the same:
`Verification of 'some_assembly_path' failed with code 134, message <<<* Assertion at ../../mono/utils/mono-os-mutex.h:71, condition `res != EINVAL' not met >>>`

**Comment by dsyme** [comment]
@ncave Could you add a bug about that to the Xamarin bugzilla bug tracker please, and post a link back here?

**Comment by ncave** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=41725

**Comment by dsyme** [comment]
OK, they say resolved fixed on Mono 4.5.1.  The "latest" seems to be giving Mono 4.4.0

**Comment by ncave** [comment]
I have reopened the issue in their tracker under 4.4.0.

**Comment by ncave** [comment]
@dsyme Mono release [timeline](http://www.mono-project.com/docs/about-mono/releases/) shows 4.4.0 was released on June 8th, which is when the issue started. Until that is fixed or a new version is released, I have updated the TravisCI matrix in  [#576](https://github.com/fsharp/FSharp.Compiler.Service/pull/576) to allow osx mono:latest to fail.
