### ISSUE TITLE
Create only one package with multiple framework

### ISSUE THREAD

**Issue by enricosada** [fsharp/FSharp.Compiler.Service#584]
Create only one package with multiple framework, not two distinct packages (net45 and netcore)

That's better because client can reference just one package, and the correct framework is resolved.
No problem about backward compatibility, because net45 it's going to be the fallback framework

Assign that to me, i am doing that it's fast todo with `dotnet-mergenupkg`

That mean packages:

- [ ] `FSC` (net45 and netcore) 
- [ ] 'ProjectCracker` (net45 and netcore)

**Comment by dsyme** [comment]
It would be great to do this please
