### ISSUE TITLE
Discussion about creating a friendly compiler API

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#604]
I think most people that have used the F# compiler API agree that is needs updating to make tooling easier to build.   This is a collection of the ramblings I had today on slack:

Roslyns symbol lookup/completion is fairly sane:
https://github.com/dotnet/roslyn/blob/master/src/Samples/CSharp/APISampleUnitTests/FAQ.cs#L218-

e.g.

``` csharp
var symbols = model.LookupSymbols(position)
```

The F# compiler doesn’t use offsets so we would just have `model.LookupSymbols(line,col)`

The nearest equivalent to model in F# would be the tast structure and the symbol api could be exposed from there.

So then theres no need for a file or source, its just using the current version of the Tast which would have to be kept up to date via the editor sending updates for FCS to apply.  **I don't think there is any reason for ident islands to be known by the caller of the API, these should be internalised via an internal parser.**

The symbol API could then be extended so there is more types described, rather than just `memberfunctionorvalue` 

e.g. `member|function|value|operator|ap|union|record|` etc

Also remove all the conflicting properties and the ones that throw exceptions which really slows things down especially during debugging.

**Comment by nosami** [comment]
I have to agree with Dave. For me, starting at Xamarin on F# tooling was quite a shock after getting used to the Roslyn APIs.

Needing to implement a lexer/parser in order to use FCS seems a little odd to say the least. All of Roslyn APIs need just a file location.

**Comment by cloudRoutine** [comment]
Getting the documentation comments as part of the UAST would be a welcome addition

**Comment by cloudRoutine** [comment]
Extending the API to take a provided TAST and compile it would also be useful

**Comment by 7sharp9** [comment]
You can only currently do this with the ParseTree API in simplesourcecode services but not the full blown sourcecodeservices which in another API hole that should be filled.
