### ISSUE TITLE
Discussion for: When can we have an alpha release of FCS for dot net core?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#605]
When and how can we get this?

Building and referencing locally is time consuming too.

**Comment by dsyme** [comment]
@7sharp9 We're waiting on a PR from @enricosada to get .NET Core AppVeyor build green and merge the nuget packages

**Comment by ncave** [comment]
@enricosada Is there other pending work after [#616](https://github.com/fsharp/FSharp.Compiler.Service/pull/616) was merged? Does the FCS/ProjectCracker/Tool version need to be incremented before it's released?
Not sure how FCS version jumped from 3.0 to 6.0.1 (already released on NuGet on July 22).

**Comment by dsyme** [comment]
@ncave We're using SemVer now, or attempting to. Each major integration from Microsoft\visualfsharp is likely to cause a bump in the major version number, particularly because changes to the "AST" data structure might cause binary incompatibilites.  So it's safest to just bump the major version number quite often.  I wouldn't be surprised to be at 50.0.0.0 or 100.0.0.0 fairly quickly...

**Comment by enricosada** [comment]
@ncave nothing i know about, but after fable work i think you know better than anyone else :D

**Comment by ncave** [comment]
@enricosada I'm sure there are upstream changes that need to make their way from ms/visualfsharp, but perhaps we can get another alpha release before that if somebody increments the version numbers (not sure who makes the decision on releases, perhaps the maintainers).

**Comment by dsyme** [comment]
Yes - @rneatherway, @forki and myself can make releases.  

I believe most recent changes from Microsoft\visualfsharp have been integrated in 6.0.2

**Comment by ncave** [comment]
@dsyme There may be some upstream commits that are not in FCS yet, like these (and maybe more):

https://github.com/fsharp/fsharp/commit/c5445a48d72704313e90dbba6dd9832355aafb56
https://github.com/fsharp/fsharp/commit/be8b1e238aa6db9443bdd038de6510444de473ab

**Comment by 7sharp9** [comment]
Any news on this?

**Comment by dsyme** [comment]
The latest changes from fsharp/fsharp are merged (https://github.com/fsharp/FSharp.Compiler.Service/pull/635/). The nuget package hasn't yet been updated.

Would be great to have a finalized release.  What's needed to do that now? thanks

**Comment by 7sharp9** [comment]
fslex,fsyacc dnc versions so it builds locally?

**Comment by dsyme** [comment]
That would be great, though I don't really understand why it's not possible for fslex.exe and fsyacc.exe to be cross-platform executables - perhaps they can be if they target .NET Standard 1.x 

Here's a work in progress PR that's relevant https://github.com/fsprojects/FsLexYacc/pull/44.  Perhaps finishing that off?

**Comment by ncave** [comment]
@dsyme #636 updates the netcore project versions to match, seems to help with the AppVeyor build.

**Comment by 7sharp9** [comment]
done, closing
