### ISSUE TITLE
Discussion: use of paket files dependencies?

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/FSharp.Compiler.Service#607]
Paket has a feature which allows to pull individual files from a github repository (http://fsprojects.github.io/Paket/github-dependencies.html).

Would that be useful to replace many of the files in this repository with known version of same file in visualfsharp repository?

For files which have delta with original compiler codebase, what is the drawback of having `#ifdef` put in visualfsharp repository? even if from time to time the build with those FCS defines could break, it would be easier to manage than a whole copy of the compiler codebase.

**Comment by dsyme** [comment]
@smoothdeveloper  The integrations are relatively easy. I'd appreciate help with them and would be happy to show you the ropes.  I recently integrated across all the F# 4.1 work and it seems to have gone OK (the main issue is the MSBuild dependencies).

The main reason we have a different fork now is that there are bouts of feature development, bug fixing and releasing of FCS and it feels easier to do that in a separate repo.  Using links (even paket git links) sounds like a bit of a nightmare compared to a get merge, but maybe I'm just used to it.
