### ISSUE TITLE
Question: NoComparison attribute on pos and Range

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/FSharp.Compiler.Service#612]
I was looking to use `pos` and `Range` data structures in a DU and I get a warning because structural comparison can't apply to those. It forces me to propagate `NoComparison` on my own datastructure.

Is there a reason this is disabled with `NoComparison` and why we wouldn't want structural comparison?

https://github.com/fsharp/FSharp.Compiler.Service/commit/6521f05b868a67a0ea984a76a4b872545e9c2ced#L30

**Comment by dsyme** [comment]
@smoothdeveloper I think there's no real reason it's disabled

**Comment by dsyme** [comment]
Closing old question
