### ISSUE TITLE
Breaking change in extension member priority

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#618]
If you compile this:

```fsharp
[<Extension>]
type Ext1 =
    [<Extension>]
    static member Apply (this: string, f) = f this

[<Extension>]
type Ext2 =
    [<Extension>]
    static member Apply (this: string, f: System.Func<string, string>) = this.Apply(f.Invoke)
```

* Previously with **F# 4.0** or **FCS 3.0.0**, the second method body contained a call to the first extension member
* Compiling with **FCS 6.0.1**, the second method calls itself (tailcall optimized away to an infinite loop in IL). The Expression API reports the method call to itself too.

This is currently a breaking change. But another possible fix would be to give an error on the ambiguous call so there is no silent semantics change.

**Comment by matthid** [comment]
Possibly related to https://github.com/Microsoft/visualfsharp/issues/1296

**Comment by Jand42** [comment]
@matthid Thanks, it is indeed the same change.
