### ISSUE TITLE
Proper Tagged Github Releases with Binaries 

### ISSUE THREAD

**Issue by cloudRoutine** [fsharp/FSharp.Compiler.Service#623]
the last release on this repo was 

![](http://i.imgur.com/3TYpWgE.png)

Could this repo start tracking releases again and at the very least include the zipped `.nupkg` for both the Compiler Service and Project Cracker?

**Comment by dsyme** [comment]
@cloudRoutine Yes it should, though it seems to complicate the release process - I think we were getting failures in the github release creation. Perhaps we should just delete the github releases and use only nuget.org for now

**Comment by cloudRoutine** [comment]
Really? We do it all the time with most of the F# OSS projects I work on with essentially the same `GithubRelease` Target as this repo's `build.fsx`, the main difference being 
```fsharp
createClient user pw
|> createDraft gitOwner gitName release.NugetVersion (release.SemVer.PreRelease <> None) release.Notes
|> uploadFile "temp/forge.zip"
|> releaseDraft
|> Async.RunSynchronously
```
the file upload.

The nupkgs are already being built so all it takes it pointing `uploadFile` to the `buildDir` for each pkg. The only thing that would make it a bit more complex is each pkg should get an additional tag (FCS & Project Cracker) in addition to the version number.

If @rneatherway  was doing the releases was it some mono issue?

**Comment by rneatherway** [comment]
It worked infrequently, but some people preferred to upload the nuget packages manually I think. I use this all the time for FsAutoComplete on mono.

**Comment by dsyme** [comment]
OK, let's aim to get it working again

**Comment by dsyme** [comment]
6.0.2 released on nuget and github.  Main thing is you need to do ``set nugetkey=...`` before ``build Release``
