### ISSUE TITLE
Project Cracker directly from NuGet directories

### ISSUE THREAD

**Issue by cgravill** [fsharp/FSharp.Compiler.Service#629]
Trying to use the project cracker directly from the NuGet packages directories errors. Internally it has an out-of-process tool “FSharp.Compiler.Service.ProjectCrackerTool.exe” which is relied on being in the directory as “FSharp.Compiler.Service.ProjectCracker.dll”
#### Repro steps

``` fsharp
#r "../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll"
#r "../packages/FSharp.Compiler.Service.ProjectCracker/lib/net45/FSharp.Compiler.Service.ProjectCracker.dll"
open Microsoft.FSharp.Compiler.SourceCodeServices
let projectFile = __SOURCE_DIRECTORY__ + @"/ProjectX.fsproj"
printfn "Project file exists: %A" (System.IO.File.Exists projectFile)
let projectOptions = ProjectCracker.GetProjectOptionsFromProjectFile(projectFile)
```

will result in:

```
Project file exists: true
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
>    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 57
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFile(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 66
   at <StartupCode$FSI_0013>.$FSI_0013.main@() in E:\dev\ProjectX\ProjectX\Script.fsx:line 10
Stopped due to error
```

What’s happening in ProjectCracker.fs is 

``` fsharp
let codebase = Path.GetDirectoryName(Uri(typeof<ProjectCracker>.Assembly.CodeBase).LocalPath)

let p = new System.Diagnostics.Process()
p.StartInfo.FileName <- Path.Combine(codebase,"FSharp.Compiler.Service.ProjectCrackerTool.exe")
```

which for the NuGet deployment fails as <ProjectCracker> is in the .dll in:

```
...\lib\net45\FSharp.Compiler.Service.ProjectCracker.dll
...\utilities\net45\FSharp.Compiler.Service.ProjectCrackerTool.exe
```
#### Known workarounds

For some uses you can rely on building the project then both .exe and .dll will be in the projects output directory. I’m using FCS before build so that's not an option unfortunately.

What I’m doing currently is modifying the NuGet directory:

``` fsharp
//Patch FCS deployment... see "codebase" in
//https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/FSharp.Compiler.Service.ProjectCracker/ProjectCracker.fs
let copyit filename =
    System.IO.File.Copy(
        System.IO.Path.GetFullPath( __SOURCE_DIRECTORY__ + @"/../../../../packages/FSharp.Compiler.Service.ProjectCracker/utilities/net45/" + filename),
        System.IO.Path.GetFullPath(__SOURCE_DIRECTORY__ + @"/../../../../packages/FSharp.Compiler.Service.ProjectCracker/lib/net45/" + filename),
        overwrite = true)

copyit "FSharp.Compiler.Service.ProjectCrackerTool.exe"
copyit "FSharp.Compiler.Service.ProjectCrackerTool.exe.config"
copyit "FSharp.Compiler.Service.ProjectCrackerTool.pdb"
```
#### Possible fixes

The simplest fix would be to distribute the .exe in the /lib folder, I don't know if that's permitted by NuGet conventions. Is the exe intended to be called at all separately?

Another approach would be to move the code contents of the .dll into the .exe then make the reference to the .exe which shells to itself. I haven’t tested this fix and it would be disruptive.

The error makes it hard to tell what’s going on, so an incremental improvement would be to explicitly error that it can’t find the .exe rather than something the user specified. At first I thought I was getting the wrong path to my .fsproj.
#### Related information

Provide any related information 
F# Compiler Services 6.0.2
Visual Studio 2015
.NET 4.5.1 (same on 4.6.1)

**Comment by rneatherway** [comment]
> The simplest fix would be to distribute the .exe in the /lib folder, I don't know if that's permitted by NuGet conventions. Is the exe intended to be called at all separately?

I originally put it in the same folder, but then found that Paket automatically adds a reference to the `.exe` to your fsproj in that case. There was some confusion early on with people calling the functions in the exe directly and I wanted to avoid that. The extra reference is also confusing.

> Another approach would be to move the code contents of the .dll into the .exe then make the reference to the .exe which shells to itself. I haven’t tested this fix and it would be disruptive.

This is a pretty neat idea and might be the best way to go, as long as it was well commented.

> The error makes it hard to tell what’s going on, so an incremental improvement would be to explicitly error that it can’t find the .exe rather than something the user specified. At first I thought I was getting the wrong path to my .fsproj.

Yes, this is a good idea. The current interface doesn't have a good way to return errors though.

**Comment by dsyme** [comment]
With the advent of the new .NET SDK 2.0 prject file format the use of the project cracker is gradually declining.  It's good for what it is and has served us well, but I'm closing out old project cracker bugs as won't fix.  We can reactivate if really urgent.

**Comment by georgewfraser** [comment]
For anyone who stumbles across this issue who is trying to do project-cracker-like-things, I found this project to be very useful and reliable for analyzing .fsproj and .csproj files: https://github.com/daveaglick/Buildalyzer
