### ISSUE TITLE
Add possibility to pass compilation constants to GetProjectOptionsFromScript

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#634]
Related to https://github.com/fable-compiler/Fable/issues/416

Apparently if you have an fsx script with a #load directive surrounded by #if directives like:

```
#if DEV
#load "./MyModule.fs"
#endif
```

`MyModule.fs` file never becomes a project file. This is probably because it's not possible to pass the `DEV` constant to `GetProjectOptionsFromScript`. Would it be possible to add compile constants as an argument to this function?

@mastoj can provide more details about the issue if needed.

**Comment by mastoj** [comment]
The reason why want to have this, in the fable world, is to be able to have separate production and dev builds to have a lower footprint in production. I explained a little bit more in this SO post: http://stackoverflow.com/questions/39478703/should-it-be-possible-to-put-the-load-directive-inside-if-directive-in-f-fsx

**Comment by 7sharp9** [comment]
Should be easy to implement, there are a few compile and related options missing from the API's

**Comment by 7sharp9** [comment]
Let me see if I can implement this while Im looking at another issue.

**Comment by 7sharp9** [comment]
There is no need for this request as the feature is already available.  I have made a PR to fable to address this:

https://github.com/fable-compiler/Fable/pull/429

Please close.

**Comment by alfonsogarciacaro** [comment]
Ups, I'm absolutely sorry! I don't know how I could skip that, I wrote the issue too fast. Thanks a lot for your help, Dave!
