### ISSUE TITLE
ProjectCracker doesn't process valid fsproj files

### ISSUE THREAD

**Issue by cloudRoutine** [fsharp/FSharp.Compiler.Service#642]
The file in question is [Ionide.FSharp.fsproj](https://github.com/ionide/ionide-vscode-fsharp/blob/a81d3465150ad776da7f3d78c67c17330bf66451/src/Ionide.FSharp.fsproj)

when the fsharp targets path is resolved via 

``` xml
  <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
  <Import Project="$(FSharpTargetsPath)" />
```

everything works fine, but change it to 

``` xml
  <Choose>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.0.0 AND $(TargetFSharpCoreVersion) &lt; 4.3.1.0 ">
      <PropertyGroup>
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.1.0 AND $(TargetFSharpCoreVersion) &lt; 4.4.0.0 ">
      <PropertyGroup>
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>    
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" Condition="Exists('$(FSharpTargetsPath)')" />
```

it can no longer parse and resolve references correctly. 
MSBuild can evaluate this `<Choose>` branch properly in Visual Studio

**Related**  
- https://github.com/Microsoft/visualfsharp/issues/1435
- https://github.com/fsharp/FSharp.Compiler.Service/issues/624
- https://github.com/fsprojects/Fable/issues/346

**Comment by dsyme** [comment]
@cloudRoutine Could you use the template and add repro steps, expected, actual etc.  Thanks

**Comment by dsyme** [comment]
With the advent of the new .NET SDK 2.0 prject file format the use of the project cracker is gradually declining.  It's good for what it is and has served us well, but I'm closing out old project cracker bugs as won't fix.  We can reactivate if really urgent.
