### ISSUE TITLE
Use Nuget packages for MSBuild Dependencies

### ISSUE THREAD

**Issue by cloudRoutine** [fsharp/FSharp.Compiler.Service#656]
These nuget packages all support .netstandard 1.3 or 1.5, so shouldn't they give a consistent xplat dependency without the need for any msbuild tools installations?

https://www.nuget.org/packages/Microsoft.Build/15.1.262-preview5
https://www.nuget.org/packages/Microsoft.Build.Framework/15.1.262-preview5
https://www.nuget.org/packages/Microsoft.Build.Runtime/15.1.262-preview5
https://www.nuget.org/packages/Microsoft.Build.Tasks.Core/15.1.262-preview5
https://www.nuget.org/packages/Microsoft.Build.Utilities.Core/15.1.262-preview5

**Comment by dsyme** [comment]
We've dealt with the MSBuild problem by removing the dependency into the separate DLL
