### ISSUE TITLE
FSharpSymbol do not carry information about enum fields

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#658]
For example, for `System.System.Text.RegularExpressions.RegexOptions`:

![image](https://cloud.githubusercontent.com/assets/873919/19619965/6872cd60-987b-11e6-9a16-fcfa627a0de8.png)

![image](https://cloud.githubusercontent.com/assets/873919/19619971/a073467c-987b-11e6-8eaa-1a2c10eeed31.png)

`FSharpFields` is used to create custom tooltips in MonoDevelop (and I'm trying to port it to VS Code at the moment) https://github.com/mono/monodevelop/blob/8b17d75ff2dc26c5aa1a6246f6a2ce7d4f65e3be/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs#L681-L689

As `FSharpFields` are empty, both MonoDevelop and Code show the following tooltip:

![image](https://cloud.githubusercontent.com/assets/873919/19620006/50fc6ff0-987c-11e6-9eea-435827fd98d9.png)

![image](https://cloud.githubusercontent.com/assets/873919/19620008/66cc6e20-987c-11e6-90a1-da008e9ba864.png)

Currently we use `FSharpCheckFileResults.GetToolTipTextAlternate` https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L1909 and it does show enum fields properly:

![image](https://cloud.githubusercontent.com/assets/873919/19620017/8afb8664-987c-11e6-92ec-1cd77636a523.png)

**Comment by dsyme** [comment]
Thanks, you're right this information should be provided

**Comment by 7sharp9** [comment]
This is specific to non F# enums is works fine for those defined in F#

![screen shot 2017-03-31 at 3 56 32 pm](https://cloud.githubusercontent.com/assets/588746/24555907/a5ffea8c-162a-11e7-9b31-8284150284fc.png)

**Comment by 7sharp9** [comment]
![screen shot 2017-04-03 at 2 45 10 pm](https://cloud.githubusercontent.com/assets/588746/24612179/66e4ce04-187c-11e7-885d-90aafc119ea2.png)

Found them.

**Comment by 7sharp9** [comment]
`ILTycon.Fields` also has them, I'll see if I can patch this up.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce in current VFT master:

![image](https://cloud.githubusercontent.com/assets/873919/25556582/a4dee90c-2d07-11e7-8656-2e4fd6eb3e73.png)

![image](https://cloud.githubusercontent.com/assets/873919/25556583/b18647fe-2d07-11e7-9750-7123c29555b8.png)

**Comment by 7sharp9** [comment]
I think I fixed this a few weeks back, perhaps I forgot to tag it in the PR.
