### ISSUE TITLE
checkPathForIllegalChars contains a grow only cache that will likely scale poorly with solution / project size

### ISSUE THREAD

**Issue by KevinRansom** [fsharp/FSharp.Compiler.Service#661]
In this commit:
https://github.com/fsharp/FSharp.Compiler.Service/commit/427a0b663bf995d158189028763c86a3e443112a

checkPathForIllegalChars now has a grow only cache, for very large solutions and for the use of FCS as a separate stand alone compiler server, this cache will eventually contain the path of very single file in the solution seen by the fsharp compiler.  And so will be pretty humongous I should imagine.

I suggest that: 
   we do some analysis to identify a less memory intensive solution, for example.
   remove checkPathForIllegalChars from the very lowlevel pathname apis and then directly call 
   checkPathForIllegalChars where it makes sense.

or some other clever solution that will scale better with project and solution size.

We have received the same PR in the Visual FSharp repo and for that we will certainly search for a more scalable solution.

Kevin

**Comment by dsyme** [comment]
This was fixed in visualfsharp tools I believe
