### ISSUE TITLE
Question: How to apply non-targetted Range value?

### ISSUE THREAD

**Issue by kekyo** [fsharp/FSharp.Compiler.Service#663]
- I'm arranging untyped AST from F# source code by visitor pattern. How to apply non-targetted Range value for new inserted expressions?
- If range value came from "Range.range0", debugger cause request "unknown" named file path when step over execution...
  - I want to no contains any sequence point for custom inserted AST nodes.
- Visited:

``` fsharp
// System.String.Format("ABC", 123, 456)
SynExpr.App(
  Atomic,
  false,
  SynExpr.LongIdent(...),
  SynExpr.Paren(SynExpr.Tuple(...)),
  appRange)
```
- Arranged by visitor:

``` fsharp
// "context.Leave" are inserted fragments by visitor.
// context.Leave(System.String.Format("ABC", 123, 456))
SynExpr.App(
  Atomic,
  false,
  SynExpr.LongIdent(...), // <-- contains Range, how to apply dummy range value?
  SynExpr.Paren(
    SynExpr.App(
      Atomic,
      false,
      SynExpr.LongIdent(...),
      SynExpr.Paren(SynExpr.Tuple(...)),
      appRange)),
    leaveParenRange), // <-- range?
  leavleAppRange) // <-- range?
```

Thanks!

**Comment by kekyo** [comment]
And try to "Range.range.MakeSynthetic", debugger cause request "unknown" too.

**Comment by dsyme** [comment]
Closing old question
