### ISSUE TITLE
Feature: API to ask for #r list

### ISSUE THREAD

**Issue by sylvanc** [fsharp/FSharp.Compiler.Service#664]
A useful API for various dynamic compilation services, including Azure Functions, would be the ability to ask FCS for all references assemblies.

For example, for an fsx project where the entry script does `#load` on some set of other fsx scripts, a single call to get referenced assemblies from all loaded scripts would eliminate the need to calculate that transitive closure by hand.

**Comment by 7sharp9** [comment]
I had to do something recently to get referenced assemblies via a fsproj
input.   It would be great to have a more efficient encompassing API.

**Comment by dsyme** [comment]
@7sharp9 The specific request here is for the transitive collection of assembly "references" (e.g. textual syntax) rather their "resolutions" (bindings).  This is because in some hosting scenarios you want an external resolver to look after the meaning of assembly references

**Comment by 7sharp9** [comment]
Oh I know, the addin I'm live coding for vocoder uses a fsproj to gather
dependencies but another feature I have in mind will do the same for fsx
files.  There seems to be a nice hole in FCSs API for things like this.

**Comment by enricosada** [comment]
@7sharp9 for fsproj that's related to #707 , the parte about `dotnet msbuild /t:ResolveReferences`

**Comment by 7sharp9** [comment]
Yeah I know you can see an MSBuild command with a grep for the refs.  In
soothsayer.
