### ISSUE TITLE
Cannot build Build.NetCore

### ISSUE THREAD

**Issue by destroyhimmyrobots** [fsharp/FSharp.Compiler.Service#670]
Running `.\build.cmd` fails on the current master. The target `build.netcore` generates errors related to reflection. There are a variety of failures in `src\absil\ilreflect.fs`, `src\fsharp\IlxGen.fs`, `src\fsharp\fsi\fsi.fs`), for example:

```
error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
```

Here is the log of the `CodeGen.NetCore` and `Build.NetCore` stages: [fcs-log.txt](https://github.com/fsharp/FSharp.Compiler.Service/files/588348/fcs-log.txt). This revision (70cbf35) is green in CI, so there must be something amiss with my local build setup.

#### Repro steps

1. Clone FCS
2. Install VS vNext, .NET Core SDK Preview 2
3. Run `.\build.cmd`

#### Expected behavior

The target builds successfully.

#### Actual behavior

Please see the [partial build log](https://github.com/fsharp/FSharp.Compiler.Service/files/588348/fcs-log.txt).

**Comment by destroyhimmyrobots** [comment]
Appears to be a windows duplicate of https://github.com/fsharp/FSharp.Compiler.Service/issues/637

**Comment by destroyhimmyrobots** [comment]
After uninstalling and reinstalling the .NET Core Preview 2 SDK and runtime, and rebooting the machine, I get a little further in the build. Many new errors that are generated seem to be related to reflection, e.g.

```
error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
```
[fcs-log.txt](https://github.com/fsharp/FSharp.Compiler.Service/files/588348/fcs-log.txt)

**Comment by ncave** [comment]
#668 was merged in recently, hopefully it helps.

**Comment by destroyhimmyrobots** [comment]
@ncave this moved me past the tests and as far as MSBuild, so it looks like the dependency updates resolved this particular issue. Thanks for the fix!
