### ISSUE TITLE
The target "Build" does not exist in the project

### ISSUE THREAD

**Issue by destroyhimmyrobots** [fsharp/FSharp.Compiler.Service#671]
The latest master fails at the `Build.NetFx` stage.

#### Repro steps

1. Clone FCS
2. Install VS vNext and dotnet SDK+cli tools.
3. .\build.cmd

#### Expected behavior

The build succeeds.

#### Actual behavior

The build succeeds until the `RunTests.NetCore` stage. 

On the `Build.NetFx` stage, the following appears: `error MSB4057: The target "Build" does not exist in the project`. 

Here is a [partial build log](https://github.com/fsharp/FSharp.Compiler.Service/files/593836/fcs-log.txt).

**Comment by dsyme** [comment]
The fix for this has been integrated
