### ISSUE TITLE
Discussion: Compiling FCS to JavaScript

### ISSUE THREAD

**Issue by ncave** [fsharp/FSharp.Compiler.Service#679]
@7sharp9 @dsyme 

Continuing the discussion from [this thread](https://github.com/fable-compiler/Fable/issues/381), I'm looking for an advice on what would be a good replacement for BCL and FSharp.Core assembly metadata (types) in a JavaScript context.

Should we try to somehow export all the type metadata in some file format and use that instead of reading from assemblies? Can we generate F# type signatures from BCL and use that? If this misses the point entirely, any other ideas for a way forward? Essentially the missing piece is the TcGlobals.

Here is the current status:

- **Untyped AST parsing works**
- Typed AST is WIP, most of the files required for type checking already compile but still needs work as it's unclear (to me) atm what can we replace the BCL and FSharp.Core assembly metadata with.

You can take a look at the progress [in this PR](https://github.com/ncave/FSharp.Compiler.Service/pull/3).

**Comment by dsyme** [comment]
@ncave Tricky but central issue.  I've always thought we would use .NET metadata format but haven't thought beyond that. 

The F# signature metadata format (see the signature resource) is a possible format since it can be turned into TAST nodes (that's what it's for).  However it has all the elegance of a car crash.  It doesn't cover .NET DLLs but maybe that's not such a problem as long as the stuff in TcGlobals is covered.

BTW there are some big cleanup PRs to integrate over from visualfsharp which may make some things simpler. Basically 
1. less things in ILGlobals - just the very basics 
2. more things in TcGlobals 
3. better logic to search all referenced assemblies for system types

**Comment by dsyme** [comment]
@ncave Very exciting to see you work on this as it would unblock many scenarios if the full F# compiler service (and thus compiler) worked as JS

**Comment by 7sharp9** [comment]
Yeah this is very exciting, its something Ive been meaning to look at just not had any time for ages!

My idea was to extract the AST for FSharp.Core and work on transpiling the typed ast, one of the big problems with that is still all the bcl mapping and the inline IL and static optimisation literals.

I did start to look at this before fable appeared using the mozilla spidermonkey AST but as usual real life got in the way.

**Comment by 7sharp9** [comment]
Also, the soothsayer assembly visualiser thing I was working in gets the F# signatures from dlls and exports as json so that part is fairly easy to do.

Ive just deleted all my pretty screen shots so this one will have to do:

<img width="745" alt="screen shot 2016-11-22 at 23 21 37" src="https://cloud.githubusercontent.com/assets/588746/21007343/6a5b6e88-bd34-11e6-9a33-bd084699333c.png">

Not sure if that shows it off as it lacks constraint relaxing on the graph nodes but all nodes are shown for an assembly and the signature for the functions etc

**Comment by 7sharp9** [comment]
@dsyme and I have talked about a skinny mscorlib and FSharp.Core to make this an easier job not sure on the way forward on stripping those assemblies down though.

**Comment by ncave** [comment]
Thank you for your input, looks like the closest options are to export/import already processed metadata:

1) Export/import to binary with TastPickle.
FSharp.Core is already exported, need to export mscorlib's FSharpViewOfMetadata if possible. 

2) Export/import to JSON.
Need to see if export/import works for all types properly.

**Comment by ncave** [comment]
Had to redo the PR to merge latest FCS.

Notes on BCL metadata serialization:
- JSON serialization is a no-go as not everything can deserialize properly.
- TastPickle works (when extended with TILObjectRepr serialization) but it results in big binaries as it does not optimize for space (no deduplication through tables).
- Reading metadata directly from assemblies works, also code/resources can be stripped out from the assembly to cut down on the blob size. It's also better as other binary dependencies can be added.

Here is the current status:
- **Untyped AST parsing works**
- **Typed AST parsing also works**
- Next step: Compiling Fable with Fable - WIP

**Comment by 7sharp9** [comment]
Sounds like great progress, thanks for looking at this stuff.

**Comment by alfonsogarciacaro** [comment]
First of all, I've to say @ncave's job is really impressive! I thought that compiling 

Not sure if this is completely related to this thread, but I think it's very important to find a JS-compatible portable format for F# type metadata if we're going to have a JS-only F# compiler. Right now, F# packages compiled with Fable are distributed with the `.dll` and the generated JS (plus a `.fablemap` file to link the F# source files with the corresponding JS ones), but the assembly is there just to hold the type metadata. The other option would be to distribute the F# source files but we decide this would slow down tooling (Discussion https://github.com/fable-compiler/Fable/issues/498).

It'd be great if we have a specific format to hold the type metadata that can be read from a JS app (node, browser, Github Electron, VS Code extension...) and ideally that's a bit open, so we could add right there the information currently in the separated `.fablemap` file.

**Comment by ncave** [comment]
@alfonsogarciacaro As long as that custom format does not produce huge files it may make sense for some scenarios, but it will be yet another format for all consumers/producers to support.

As mentioned above and after trying some alternative formats, sticking to what we already have out of the box and keeping things simple makes a lot of sense to me, i.e. the assembly metadata is an [open format](http://www.ecma-international.org/publications/standards/Ecma-335.htm) and JavaScript is perfectly capable of reading it (and producing it if needed, I'm sure, but for now reading is all that's needed), and also the file size is smaller as it's already optimized for space.

That also solves the problem with other binary references.

**Comment by alfonsogarciacaro** [comment]
Thanks for your reply @ncave! I'm completely fine with the assembly format if it can be handled from JS. My actual knowledge of .NET IL is very limited so this may look as a dumb question but, currently when you compile a Fable package, [a `.dll` is generated](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/fable/Fable.Client.Node/Main.fs#L479) with the only purpose to hold the metadata (but it also contains the compiled IL); in the case of a JS-only Fable, would it possible to produce an _empty_  `.dll` with only the type metada so it can be read from other Fable projects referencing it?

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, it should be possible in a Node setting (not sure if it makes a lot of sense in a browser setting), if the full FCS is compiled with Fable. As of right now, only the Typed AST parsing is compiled (which is about 80% of FCS), as that's all the Fable compiler needs. Compiling binaries by the node client is a different scenario that will require the full FCS.

**Comment by matthid** [comment]
@alfonsogarciacaro
Sorry if this is nonesense but I think empty assemblies are actually already used in the .net ecosystem and called reference assemblies.

The F# compiler already has code to parse the IL. It's just not exposed nicely, so a combination of those two might help?

**Comment by ncave** [comment]
@matthid @alfonsogarciacaro Yes, as mentioned above you can definitely use it to export assemblies without code/resources to cut on the blob file size (but that's using the full FCS on dotnet).

**Comment by alfonsogarciacaro** [comment]
In case it helps, I'm providing a couple of links to Fable code for reference:

- [This is where Fable checks if there's a `.fablemap` file next to the referenced `.dll`](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/fable/Fable.Compiler/FSharp2Fable.fs#L1193-L1197) (so it's considered a Fable package)
- Then, when there's a reference to an `FSharpEntity` in the Typed AST, Fable will try to [get the _internal_ file containing it](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/fable/Fable.Compiler/FSharp2Fable.fs#L1136-L1139). Fable considers _internal_ files those in the current project and those in referenced assemblies with a `.fablemap`.

> Non-internal `FSharpEntity`s must be replaced (either by a plugin or the `Replacements` module) or Fable will throw an error.

**Comment by alfonsogarciacaro** [comment]
Ok, so now thanks to the amazing work of @ncave we already have an F# compiler running on JS :tada: I gave it a quick try and it works! As far as I could see the only thing that remains to make it fully independent are the core assembly references.

The JS-based F# compiler can read the type metada of `.dll` assemblies without problem, so the best thing will be to have a lightweight `.dll` representing the types from the BCL and FSharp.Core currently compatible with Fable which can be easily embedded with Fable.

What would the best/easiest way to create this `.dll`? Just by manually writing a project with all the necessary interfaces?

**Comment by smoothdeveloper** [comment]
@alfonsogarciacaro I'm in no way informed but maybe look at

* https://github.com/jbevain/cecil fast and established IL reader
* https://github.com/mono/CppSharp they generate lots of C# bindings for CPP dynamically (backed by LLVM)

I'm sure other will provide more appropriate ideas.

**Comment by ncave** [comment]
@alfonsogarciacaro If you just want smaller assembly size right away, you can build and run [this project](https://github.com/ncave/FSharp.Compiler.Service/tree/fable/src/fsharp/Export.FCS) to export referenced binaries with code and resources removed.

Notes:
- uncomment this portion of [FCS project](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj#L52) first
- output goes to /temp/metadata/, can be changed [here](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/CompileOps.fs#L4668)
- if you need additional binaries, just add "-r somebinary" [here](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/Export.FCS/Program.fs#L35)
- the produced binaries are unsigned, so I'm not sure if distributing them like that is ok (signing can be added, but somehow it needs to be stated that those are not the original binaries so people are not confused, and there is the legal aspect of modifying them to think about too).
- dotnetcore output also works, but I have not tested the produced binaries (they look way too small).

**Comment by alfonsogarciacaro** [comment]
Fantastic, I was wondering what did you put in that `/temp/metada` directory ;)

It's working. Thanks a lot for the info :+1:

**Comment by alfonsogarciacaro** [comment]
Hi @dsyme and others with good knowledge of the `.dll` binary format. I'd really appreciate if you could have a look at [this issue](https://github.com/fable-compiler/Fable/commit/b6c28f6f0ed843a8fc49d7604c80fc6e343a45dc#commitcomment-21012762) that's affecting the JS-compiled FCS in Fable's REPL. Thanks a lot in advance!

**Comment by dsyme** [comment]
@alfonsogarciacaro ok I commented on that thread.

**Comment by dsyme** [comment]
Spring cleaning old feature requests and suggestions in preparation for repo unification  

The cross-compiple to JS is maintained in a branch and active PR (which is great! :) )
