### ISSUE TITLE
IL Assembly Parsing fails for ReflectedDefinitions

### ISSUE THREAD

**Issue by haraldsteinlechner** [fsharp/FSharp.Compiler.Service#691]
ILTypeSigParser in il.fs fails to parse assemblies containing reflectedDefinitions.  This issue arises, for example when using FSFormatting to create literate scripts using libraries with reflected definitions.

This is a replication of an old issue, merged into starterpack, see:
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/94

i have copied my old fix to both, FSharp.Compiler.Service and of course the fsharp compiler itself.
https://github.com/haraldsteinlechner/fsharp/commit/47b66b3c5f9ab4998a0537333e7eafd4bcc39c3a
and 
https://github.com/haraldsteinlechner/FSharp.Compiler.Service/commit/20e7cbd563cc0e27dd862174fa788e4ac0a82e2c

Since we have duplications of the same bug it is unclear to me where to put the fix the test etc.

**Comment by dsyme** [comment]
@haraldsteinlechner For now you can submit the fix to this repo along with a test.  We will find a way to integrate the fix to the other repos (though my understanding is that this only affects the use of FCS, and not the F# command-line compiler itself? I'll understand more when I see the test case)

**Comment by dsyme** [comment]
@haraldsteinlechner Do you have plans to submit the fix here?  It would be great if you could.  Thanks!

**Comment by haraldsteinlechner** [comment]
oh yes. i'm gonna submit a PR soon.

**Comment by dsyme** [comment]
@haraldsteinlechner super. thanks

**Comment by dsyme** [comment]
@haraldsteinlechner Did you manage to get a PR together for this?  Thanks!
