### ISSUE TITLE
Cannot pass a custom fsi object to a script

### ISSUE THREAD

**Issue by asmichi** [fsharp/FSharp.Compiler.Service#692]
http://fsharp.github.io/FSharp.Compiler.Service/interactive.html#The-fsi-object

> If you want your scripting code to be able to access the 'fsi' object, you should pass in an implementation of this object explicitly. Normally the one fromm FSharp.Compiler.Interactive.Settings.dll is used.

The API and the document implies we can pass a custom 'fsi' object (`myFsi` hereafter) to the script by creating an fsiConfig with `FsiEvaluationSession.GetDefaultConfiguration(myFsi)`. Even when I do so, the script still sees the default 'fsi' object from FSharp.Compiler.Interactive.Settings.dll.

Though I am reporting this as an issue on the behavior, I am not sure. This may be an issue on the API and the documentation.

#### Repro steps

Complete patch: [PassingCustomFsiObjectTest.patch.txt](https://github.com/fsharp/FSharp.Compiler.Service/files/761054/PassingCustomFsiObjectTest.patch.txt)

1. Modify FsiTests.fs as follows:

    - Modify `fsiConfig` and the `EvalExpression fsi test` test as follows:

    ```fs
    // The `fsi` object defined in FSharp.Compiler.Service.dll, not in FSharp.Compiler.Interactive.Settings.dll.
    let myFsi = Settings.fsi
    let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration(myFsi)
    ```

    ```fs
    let ``EvalExpression fsi test``() = 
        evalExpression "fsi" |> shouldEqual (sprintf "%A" myFsi)
    ```

2. Execute the `EvalExpression fsi test` test and see it fail.

    ```
    Expected: "Microsoft.FSharp.Compiler.Interactive.Shell+Settings+InteractiveSettings"
    Actual: "Microsoft.FSharp.Compiler.Interactive.InteractiveSession"
      Expected string length 72 but was 56. Strings differ at index 38.
      Expected: "...Sharp.Compiler.Interactive.Shell+Settings+InteractiveSettings"
      But was:  "...Sharp.Compiler.Interactive.InteractiveSession"
    ```

#### Expected behavior

- The `myFsi` object is bound to the `fsi` identifier.

- Or, the correct procedure to pass a custom 'fsi' object to the script is documented.

#### Actual behavior

- The default 'fsi' object from FSharp.Compiler.Interactive.Settings.dll is bound to the `fsi` identifier.

#### Known workarounds

- Create fsiConfig with `FsiEvaluationSession.GetDefaultConfiguration(myFsi, false)` to prevent FSI from referencing FSharp.Compiler.Interactive.Settings.dll and thus introducing the default 'fsi' object incompatible with `myFsi` via AutoOpen.
- Bind an object equivalent to `myFsi` to the `fsi` identifier in some way, for example, by AutoOpen'ing a module defining `fsi` as [FSharp.Compiler.Interactive.Settings.dll does](https://github.com/Microsoft/visualfsharp/blob/vs2015/src/fsharp/fsiaux.fs#L116).

IMO this may be the correct procedure, considering that we cannot (currently?) inject an object directly into a script context.

#### Related information 

* Tag 9.0.0
* .NET 4.5
* Visual Studio 2015
* Windows 10

**Comment by matthid** [comment]
First: Yes this looks like a bug. For some reason though it was never fixed, while definitely discussed several times before (try to search in the (closed) issues list).

> IMO this may be the correct procedure, considering that we cannot (currently?) inject an object directly into a script context.

You can, though with a "workaround"/hack:
https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L718-L723
If you want to "bring your own instance" you can use the workaround here:
https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L1323-L1412

**Comment by asmichi** [comment]
Thanks @matthid! I found related discussion in #127.

Also thanks for the workaround! I will first give your library a try; it looks really fantastic.

**Comment by tymokvo** [comment]
So did the PR above close this? Is there an accepted method to bind identifiers to arbitrary `obj`s when using an embedded FSI instance?
