### ISSUE TITLE
FCS 11.0.1 - unwanted Console.WriteLine in service.fs

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#706]
Starting from FCS 11.0.1, calls to `ParseAndCheckFileInProject` cause some
unwanted information printed to the console.

Presumably, the culprit is the line 2541 in *service.fs*

    Console.WriteLine(sprintf "parseAndCheckFileInProjectCache SET key = %+A" (filename,source,options))

introduced by the recent commit 167b508091e74a1a1bc9cb768ecac237ea1fa640.

**Comment by dsyme** [comment]
Fixed in 11.0.2, now released
