### ISSUE TITLE
Constructor with self alias dropping outer `let` expressions

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#713]
From this code:

```fsharp
type Test (x: int) =
    new () as this =
        let x = 42
        new Test(x)
```

FCS AssemblyContents API sees the extra constructor as:

```
member .ctor(unitVar0) = ((Test..ctor (x); this.contents <- [I_ldarg 0us]()); [I_ldarg 0us]().init@7-13 <- 1)
```

The outer `let` expression is missing, so variable `x` is unbound.

If the `as this` is removed, the `let` is exposed properly:

```
member .ctor(unitVar0) = let x: Microsoft.FSharp.Core.int = 42 in Test..ctor (x)
```

Tested with `FSharp.Compiler.Service 11.0.4`

**Comment by dsyme** [comment]
@Jand42 Thanks for the bug report
