### ISSUE TITLE
NuGet Package should reference FSharp.Core package

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#715]
Currently the NuGet Package references 
`Microsoft.FSharp.Core.netcore (>= 1.0.0-alpha-161205)` for netcore, but it should use https://www.nuget.org/packages/FSharp.Core/ to be consistent across the ecosystem...

#### Repro steps

In FAKE vNext I use a complete paket group to compile the FAKE script. Therefore I get (when FSharp.Compiler.Service is a dependency of the group, in addition to FSharp.Core):

`error FS0215: Multiple references to 'FSharp.Core.dll' are not permitted`

#### Provide the steps required to reproduce the problem

1. Clone my FAKE coreclr branch
2. ./build.sh
3. run the `use external paket.dependencies` integration test by hand

(let me know if someone actually wants to do it and needs help)

#### Known workarounds

Maybe I should manually blacklist `Microsoft.FSharp.Core.netcore` in Fake.vnext.

**Comment by dsyme** [comment]
@matthid Could you send a PR for this? thanks

**Comment by matthid** [comment]
@dsyme done
