### ISSUE TITLE
Could not find file default.win32manifest

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#755]
I'm using FCS to compile something on the dotnetcore runtime for dotnetcore and get 
`unknown (1,1)-(1,1) parse error Could not find file 'C:\PROJ\FAKE\nuget\dotnetcore\Fake.netcore\current\default.win32manifest'.`

#### Repro steps

```
let fsc = FSharpChecker.Create()
let errors, returnCode = fsc.Compile (args |> List.toArray) |> Async.RunSynchronously
```

#### Expected behavior

The compilation works

#### Actual behavior

`unknown (1,1)-(1,1) parse error Could not find file 'C:\PROJ\FAKE\nuget\dotnetcore\Fake.netcore\current\default.win32manifest'.`

#### Known workarounds

Copy the file from the `FSharp.Compiler.Tools` package to the location indicated by the error.

#### Question

- [ ] Why is that file needed? Can someone give a brief explanation what that is about?
- [ ] Is the FCS package missing a dependency on the `FSharp.Compiler.Tools` package (@cloudroutine noticed it in the `paket.dependencies` of this repository)? 
- [ ] Should `FSharp.Compiler.Service` distribute the `default.win32manifest` file / Is it an error in the current package?

**Comment by dsyme** [comment]
It looks like this file should be made available as part of the FSharp.Compiler.Service nuget package - though I'm not sure in which directory - and also bundled as part of the final application.  On .NET Core (``FX_NO_RUNTIMEENVIRONMENT``) the code currently expects to find it as part of the final application.  With Mono and .NET Framework the file is always part of the .NET installation itself.

``
#if FX_NO_RUNTIMEENVIRONMENT
                // On coreclr default manifest is alongside the compiler
                Path.Combine(System.AppContext.BaseDirectory, @"default.win32manifest")
#else
                // On the desktop default manifest is alongside the clr
                Path.Combine(System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory(), @"default.win32manifest")
#endif
```
There is no problem with just taking a copy of the file and including it in your application - it's never going to change.  However it would be better to submit a PR to add it to the FCS package as an extra file, and then include it as a file in your application from there

It looks like these flags are also relevant for workarounds - you can specify the location directly, or say you don't want the manifest embedded
```
        CompilerOption("win32manifest", tagFile, OptionString (fun s -> tcConfigB.win32manifest <- s), None,
                           Some (FSComp.SR.optsWin32manifest()))
        
        CompilerOption("nowin32manifest", tagNone, OptionUnit (fun () -> tcConfigB.includewin32manifest <- false), None,
                           Some (FSComp.SR.optsNowin32manifest()))
```

I don't really know what the manifest resource is or does

**Comment by matthid** [comment]
Just to let others know: Slack helped me out quite a bit there.

- There is apparently the `--nowin32manifest` compiler option (as Don already noted) which is exactly what I need in my situation (as I only load the compiled library dynamically later)
- There is a bug open by @enricosada https://github.com/Microsoft/visualfsharp/issues/1024

> @baronfel (in Slack)
> the file is an application manifest required to run a win32 executable. there’s one packaged by the compiler in fsc.fs, line 1035:
> there’s a compiler flag to use the embedded one, or an application can provide its own (for example to opt into the HDPI-aware behavior in windows 10)

From my side the issue can be closed (if the bug from @enricosada is enough to track this) as I have a workaround for now...

**Comment by dsyme** [comment]
@matthid Thanks
