### ISSUE TITLE
`non-IL or abstract method with non-zero RVA` printed on standard out

### ISSUE THREAD

**Issue by rneatherway** [fsharp/FSharp.Compiler.Service#780]
Please provide a succinct description of the issue.

#### Repro steps

Use FCS in many settings with Mono 5. Example is FSAC regression tests, e.g. https://travis-ci.org/fsharp/FsAutoComplete/jobs/243195680#L2206, or with emacs: https://github.com/fsharp/emacs-fsharp-mode/issues/130

#### Expected behavior

No debug output on standard output.

#### Actual behavior

`non-IL or abstract method with non-zero RVA` printed

#### Known workarounds

Emacs and VIM now currently discard this spurious output, but the FSAC regression tests will be a bit more awkward.

#### Related information 

Mono 5, Linux.

Should this be considered a Mono bug, as it doesn't happen under Mono 4.8? Everything still seems to work fine, so I wonder why it is a warning. Either way, stdout doesn't feel like the right place for this.

**Comment by nosami** [comment]
Different versions of Mono ship different versions of the compiler. The warning comes from the compiler, so I don't think that this should be considered a Mono issue.

**Comment by enricosada** [comment]
ah sorry, didnt find it in fsharp repo.

maybe is https://github.com/Microsoft/visualfsharp/blob/458e6c29d7e059a5a8a7b4cd7858c7d633fb5906/src/absil/ilread.fs#L2358

So is a packaging issue for `fsharp/fsharp`?

**Comment by nosami** [comment]
The code is still in `fsharp/fsharp` - https://github.com/fsharp/fsharp/blob/5a942daf930d7023c78f578ec6876b86a6f13f1e/src/absil/ilread.fs#L2358

**Comment by rneatherway** [comment]
By using FCS, aren't we insulated from the version of F# installed on the machine? I thought this was coming from the FCS bundled with FSAC.

**Comment by nosami** [comment]
Ah, yes you are.... the bug is in FCS too - https://github.com/fsharp/FSharp.Compiler.Service/blob/9b802fa4ee9b3cf70b4e17bb6baa70a878c5c801/src/absil/ilread.fs#L2358 

As far as I know, this repo will be redundant soon and FCS will be built from the VisualFSharp repo.

**Comment by enricosada** [comment]
we are, bug is here too :D https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/absil/ilread.fs#L2358

**Comment by enricosada** [comment]
well, let's remove it there, and `fsharp/fsharp` later

**Comment by enricosada** [comment]
that said, what that error mean (@dsyme may help maybe) dunno. 
So this code (https://github.com/fsharp/FSharp.Compiler.Service/blob/24d671c74a49b1e300f87850ec698a74eb3a6423/src/absil/ilread.fs#L2352-L2361 ) 

```fsharp
       mdBody=
         if (codetype = 0x01) && pinvoke then 
           mkMethBodyLazyAux (notlazy MethodBody.Native)
         elif pinvoke then 
           seekReadImplMap ctxt nm  idx
         elif internalcall || abstr || unmanaged || (codetype <> 0x00) then 
           if codeRVA <> 0x0 then dprintn "non-IL or abstract method with non-zero RVA"
           mkMethBodyLazyAux (notlazy MethodBody.Abstract)  
         else 
           seekReadMethodRVA ctxt (idx,nm,internalcall,noinline,numtypars) codeRVA   
```

the error is printen on mono 4.8 but not on 5.0. that's strange but maybe is not a bug ( /cc @dsyme @KevinRansom  )

**Comment by dsyme** [comment]
> ... this repo will be redundant soon and FCS will be built from the VisualFSharp repo.

I'm still in two minds about doing that.  This repo is an important symbol of the independence of F#, and the packages is generates are used by other editor tooling that is an alternative to Visual Studio (Jet Brains Ryder, Ionide etc)

So we may keep building FCS from this repo until the IDE tools are split out of the visulfsharp repo (e.g. visualfsharp splits into "fsharp" and "visualfsharp-ide-tools"), whenever that happens

**Comment by enricosada** [comment]
> So we may keep building FCS from this repo until the IDE tools are split out of the visulfsharp repo (e.g. visualfsharp splits into "fsharp" and "visualfsharp-ide-tools"), whenever that happens

👍  💯  about that. it's really important to first have a clean and smooth workflow for community improvements/fix there or on `fsharp/fsharp` (or `visualfsharp` if governance on that is ok, but can be tricky because need tagging etc), and only after that to migrate repo.

Is really important to have continuos releases of this repo, so fsac and others can fix/ehcance faster.
