### ISSUE TITLE
Some info is missing in PartialAssemblySignature when signature file exists

### ISSUE THREAD

**Issue by auduchinok** [fsharp/FSharp.Compiler.Service#784]
Here're several cases which may be connected:
* Consider a type with attributes declared in `*.fs` and `*.fsi` files. After type-checking the `*.fs` file and getting its partial assembly signature, the type contains attributes from the signature file only. When getting the same type via `GetAllUsesOfAllSymbolsInFile`, all attributes are shown.
* When type-checking a signature file, its partial assembly signature doesn't contain types defined in this file (but contains files defined in previous files in the project).
* When symbols are hidden by a signature file they do not appear in `PartialAssemblySignature`.

**Comment by dsyme** [comment]
Hi @auduchinok 

This is a bit tricky to fix - as you can imagine the way the compiler is set up the information is truly hidden.

What IDE features are you using PartialAssemblySignature for?

thanks

**Comment by auduchinok** [comment]
Hi @dsyme, thank you for the reply!

We're mapping FCS symbols to ReSharper ones during ReSharper cache population and resolve process. If a PartialAssemblySignature contains symbols from all files prior to the checked one, we're able to create proper ReSharper cache symbols to resolve to without additional checks of prior files in the project.
Currently we type-check the prior files to create ReSharper symbols when they are needed in resolve and using `GetSymbolUseAtLocation` (or `GetAllUsesOfAllSymbolsInFile` in some cases). It looks like caching the biggest available assembly signature and getting another if a bigger part of the project is needed may be a better strategy.
