### ISSUE TITLE
Smallish typo in the Interactive Service Embedding page

### ISSUE THREAD

**Issue by mrakgr** [fsharp/FSharp.Compiler.Service#788]
>Normally the one fromm FSharp.Compiler.Interactive.Settings.dll is used.

[The `fromm`](http://fsharp.github.io/FSharp.Compiler.Service/interactive.html#The-fsi-object) should be `from`.

Maybe it would be good to rewrite it as:

>Normally, the one from `FSharp.Compiler.Interactive.Settings.dll` is used.

Also...

> However, the F# interactive service is still useful, because you might want to wrap it in your own executable that is then executed (and communicates with the rest of your application), or if you only need to execute limited subset of F# code (e.g. generated by your own DSL).

The way the above sentence is phrased seems out of place. It feels like it is referring to something that is missing. Ordinarily, I'd fix the typo myself, but I am not sure what to do with the sentence above. Remove it?

**Comment by dsyme** [comment]
Please propose a PR and we can discuss wording, thanks!

**Comment by enricosada** [comment]
closing, fixed
