### ISSUE TITLE
--nowarn is not working in FSharpChecker.Compile()

### ISSUE THREAD

**Issue by amieres** [fsharp/FSharp.Compiler.Service#790]
Using the `--nowarn:` option still shows the warnings when calling FSharpChecker.Compile.

#### Repro steps
To reproduce just invoke this using fsi:
```
#r @"FSharp.Compiler.Service.dll"
System.IO.File.WriteAllText("test.fs", "module test\r\nlet a unused = 1")
[| "" ; "test.fs" ; "--nowarn:1182,988" |] 
|> Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.Create().Compile
|> Async.RunSynchronously;;
```

#### Expected behavior
Should return zero warnings:
`val it : Compiler.FSharpErrorInfo [] * int = ([||], 0)` 

#### Actual behavior
```
val it : Compiler.FSharpErrorInfo [] * int =
  ([|test.fs (2,7)-(2,13) typecheck warning The value 'unused' is unused;
     test.fs (2,17)-(2,17) ilxgen warning Main module of program is empty: nothing will happen when it is run|],
   0)
```
#### Known workarounds

using #nowarn works as expected:

```
#r @"FSharp.Compiler.Service.dll"
System.IO.File.WriteAllText("test.fs", "module test\r\n#nowarn \"1182\" \"988\"\r\nlet a unused = 1")
[| "" ; "test.fs" |] 
|> Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.Create().Compile
|> Async.RunSynchronously;;

--> Referenced 'FSharp.Compiler.Service.dll'

val it : Compiler.FSharpErrorInfo [] * int = ([||], 0)
```

#### Related information 

* Windows 10
* .NET Runtime 4.6.1
* F# 4.1

**Comment by vasily-kirichenko** [comment]
1. Looks like `tcConfig` got proper `specificWarnOff` list:

![image](https://user-images.githubusercontent.com/873919/31046129-f37d0d56-a5fb-11e7-8d2a-3288d561598f.png)

2. `FSharpChecker.Compile` uses `IErrorLogger` which does not filter warnings in any way https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2067-L2070
```fsharp
let errorLogger = 
            { new ErrorLogger("CompileAPI") with 
                member x.DiagnosticSink(exn, isError) = errorSink isError exn
                member x.ErrorCount = errors |> Seq.filter (fun e -> e.Severity = FSharpErrorSeverity.Error) |> Seq.length }
```
it just collect all warnings and errors into a `List` and then return it.

3. A derived type that provides an error logger which does the filtering is `InProcErrorLoggerProvider` https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsc.fs#L130-L144 (`CollectDiagnostic` type does the actual filtering). We could use it, but I cannot find a way to obtain `TcConfig` being inside `FSharpChecker` here https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2890.

@dsyme any hints about:

* should FCS filter warnings based on `--nowarn:xx`?
* if so, how to get the proper `TcConfig` at #3?
