### ISSUE TITLE
Remove .NET Core version of Project Cracker

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Compiler.Service#791]
The ProjectCracker.dll and ProjectCrackerTool.exe currently have .NET Core versions.

These are for supporting "old" F# project formats, pre .NET SDK 2.0.  I don't see the ned to continue to maintain and deliver .NET Core versions of these, since .NET Core tooling normally only understands "new" F# project file formats for .NET SDK 2.0

@ncave @Krzysztof-Cieslak @rneatherway @matthid Can you chime in with your thoughts on this?  thanks

**Comment by ncave** [comment]
@dsyme +1 for using the new project file format.
On a related note, are upstream changes planned to come into FCS? Is there a plan to fold FCS back into upstream? I know, so many questions...

**Comment by dsyme** [comment]
> On a related note, are upstream changes planned to come into FCS? Is there a plan to fold FCS back into upstream? I know, so many questions...

I'm trying to work this out now.  

We integrated very large chunks of fcs back to Microsoft\visualfsharp, all the core code and enough to enable a CI build of the .NET Framework version of FSharp.Compiler.Service.dll.  That's good. In https://github.com/Microsoft/visualfsharp/pull/3480  I've done the same for the .NET Framework versons of the other tools (ProjectCracker, FSharp.Compiler.Service.MSBuild.v12.0.dll). However the  .NET Core/Standard build of FSharp.Compiler.Service.dll was not included in that, nor were the docs, nor .NET Core testing and so on.

The .NET Core/Standard build of FSharp.Compiler.Service is a bit of a pain to build, because of the manual codegen done in ``build.fsx`` etc.  I don't yet fully understand why all that is needed but there must be rationales for it.

Anyway, even after https://github.com/Microsoft/visualfsharp/pull/3480  this has left us in a messy situation where we have one build of FSharp.Compiler.Service.dll that uses on build system (the one from Microsoft/visualfsharp), and one here that uses another (Paket, FAKE etc.).  I really want to just have one build system with ultra-simple integrations.

**Comment by enricosada** [comment]
> The ProjectCracker.dll and ProjectCrackerTool.exe currently have .NET Core versions.
> 
> These are for supporting "old" F# project formats, pre .NET SDK 2.0

the .net core version doesnt make sense, should be removed.

### Is useless to parse old fsproj

Projectcracker use msbuild autiomation, so as library.
The old fsproj/csproj expect full .net msbuild, the .net core version of msbuild is more restricted.
An example: some target file can embeed c# code, this is not supported by .net core msbuild, so will not work correctly

### doesnt work with new sdk fsproj

why new project can be msbuild 15 without sdk style, these are .net full, so anyway, useless
