### ISSUE TITLE
Most performant way of getting typed AST of single file edited after full parsing

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#796]
One of the selling points of Fable is it works very well in watch mode as frontend developers are used to work. However, I still don't know what's the best way to get the typed AST of a single file edited after fully parsing a project. Right now I'm using `ParseAndCheckProject` for both cases (first project load and file edits after that), the only difference is [I reuse the ProjectOptions for watch compilations](https://github.com/fable-compiler/Fable/blob/24b9cb37f54cdf3e909037f443293f95e6773a24/src/dotnet/dotnet-fable/StateUtil.fs#L58-L75).

Is there a better way to do this? I've seen there're some methods like `ParseFileInProject` but it doesn't give the `FSharpImplementationFileContents`. Also, should I set `LoadTime` in ProjectOptions to any specific value?

Thanks! (Pinging @dsyme for help 😄 )

**Comment by dsyme** [comment]
@alfonsogarciacaro If you want ``FSharpImplementationFileContents`` then ``ParseAndCheckProject`` is correct right now

If you want a single file - I suppose we could add FSharpImplementationFileContents to the results from ParseFileInProject

**Comment by alfonsogarciacaro** [comment]
Probably being able to parse a single file would be useful though some cases may be a bit complicated (for example, the edited file may have to access the AST of another file to inline a method, which may or may have not have changed as well).

My question is mainly if there's any performance trick I may be overlooking as I don't know well how the cache works. Does it depend on the `LastWriteTime` of the source files? Does the `LoadTime` property of `ProjectOptions` affect the cache somehow? If so, what's the proper way to set it?

**Comment by alfonsogarciacaro** [comment]
@dsyme How difficult would it be to add `FSharpImplementationFileContents` to `ParseFileInProject`? Would it be able to also detect changes in dependent files?

**Comment by dsyme** [comment]
> @dsyme How difficult would it be to add FSharpImplementationFileContents to `ParseFileInProject`? 

I _think_ it would be easy to add it to `CheckFileInProject`

> Would it be able to also detect changes in dependent files?

Yes, if they have been saved to disk

**Comment by alfonsogarciacaro** [comment]
That's great news! It's not urgent but probably parsing a single file will bring a big performance gain, as currently Fable merges sources of all dependencies in a single file so parsing the whole project on every file save can get a bit slow.

I'll try to have a look at it myself after FableConf and will ask for pointers if necessary :smile:

**Comment by vasily-kirichenko** [comment]
Wow, it should be fixed.

**Comment by forki** [comment]
@vasily-kirichenko go for it!

**Comment by forki** [comment]
I personally think this would be super valuable for Fable.
In our usual projects we have many "fable base libraries" that we import via nuget source code packages. These libs never change during watch mode and are always imported at the top. So even if I change the very first line of my own code these libs are not touched. So a version of the FCS which only starts reching from that line already will be a big perf win.

**Comment by vasily-kirichenko** [comment]
Changing single file results with the following output:
```
webpack: Compiling...
Parsing ./EsExplorer.fsproj...
fable: Compiled src\App.fs
Hash: 37c448bdf0c57a51d758
Version: webpack 3.6.0
Time: 6317ms
        Asset     Size  Chunks                    Chunk Names
    bundle.js  2.31 MB       0  [emitted]  [big]  main
bundle.js.map  2.32 MB       0  [emitted]         main
 [250] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [255] ./src/App.fs 4.05 kB {0} [built]
    + 464 hidden modules
webpack: Compiled successfully.
```
Does it mean a single file has been type checked? Or it still checked the entire project?

**Comment by alfonsogarciacaro** [comment]
Every time you see the `Parsing XXX.fsproj...` it means [the whole project is being checked](https://github.com/fable-compiler/Fable/blob/02872dbdcab27867f4d51783d67015a9f3600a99/src/dotnet/dotnet-fable/StateUtil.fs#L72-L76). I didn't find another way to get the `FSharpImplementationFileContents` which contains the AST :/

**Comment by vasily-kirichenko** [comment]
How to debug the compiler? So I have Fable.sln open in Rider. It builds successfully. How can I replace the compiler which is used in a project with the one just built and attach with the debugger to it? Or the dev flow is completely different?

**Comment by alfonsogarciacaro** [comment]
I don't use the debugger, because when I compile Fable with Debug config I get _ehem_ SO exceptions more often than not (it works if I target .NET Framework, I removed the .fsproj files for that recently but I can add them again).

My workflow with FAKE is usually to make the modifications in the code and then run `QuickFableCompilerTest` which compiles Fable and then uses it to compile `src/tools/QuickTest.fs` so I can check the output (`src/tools/temp/QuickTest.js`) or use printfn statements were necessary. With VS for Mac I have this `dotnet-fable.fsproj.user` file so I just need to press F5:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Default' ">
    <StartAction>Project</StartAction>
    <StartArguments>npm-run rollup --port free</StartArguments>
    <StartWorkingDirectory>..\..\tools</StartWorkingDirectory>
    <ExternalConsole>true</ExternalConsole>
  </PropertyGroup>
</Project>
```

**Comment by vasily-kirichenko** [comment]
After some thinking about it I've come to conclusion that it's impossible to speed up this. This is how I see the current implementation:

1. A *.fs file changed and saved to disk.
2. The mailbox processor got a message which `path` field is set to the file https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/StateUtil.fs#L199
3. The MB calls `StateUtil.updateState`, which calls `ParseAndCheckProject` and pass the result to `transformFile` along with the file name https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/StateUtil.fs#L153 https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/StateUtil.fs#L75 
4. It finds the related `FSharpImplementationFileContents` in `checkedProject.AssemblyContents.ImplementationFiles` and uses it to generate JavaScript from it https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1328

Why the optimization won't work:

1. Instead of calling `ParseAndCheckProject` we call `ParseAndCheckFileInProject`, which _does not_ compile files _below_ this one.
2. We store `FSharpImplementationFileContents` (which is not a part of `FSharpFileCheckResults` yet) somewhere in a map by file name.
3. We transform the file impl content to js.
3. Now we have a broken project: if *.fs files below the current one are now non-compilable due to changes made in the current file (i.e. it's API has changed), then `ParseAndCheckFileInProject` _won't fail_ like `ParseAndCheckProject` would, and we have inconsistent JavaScript code.

Does it make sense or I don't understand something? 

/cc @dsyme

**Comment by vasily-kirichenko** [comment]
(AFAIK `ParseAndCheckProject` is smart and rechecks files starting and below the top changed file only)

**Comment by alfonsogarciacaro** [comment]
Your concerns are right but I think we could force recompilation of dependent files (not all the files below the edited one, only those accessing any of its public members). Before Fable kept a dependency map for this reason, I removed it after the Webpack integration but we could bring it back.

> (AFAIK ParseAndCheckProject is smart and rechecks files starting and below the top changed file only)

I was hoping the same, but when compiling a project with many files, like the Fulma docs, parsing the project takes more or less same (around 8s) either when I edit the last file (App.fs) or one in the top (Global.fs) 😕

**Comment by vasily-kirichenko** [comment]
> I was hoping the same, but when compiling a project with many files, like the Fulma docs, parsing the project takes more or less same (around 8s) either when I edit the last file (App.fs) or one in the top (Global.fs)

@dsyme I think it's a bug in FCS?

**Comment by vasily-kirichenko** [comment]
> I think we could force recompilation of dependent files (not all the files below the edited one, only those accessing any of its public members

If so, the optimization may work. 

However, we should fix the ^^^ bug (if it's a bug) first and see what a perf improvement it gives us.

**Comment by vasily-kirichenko** [comment]
We have a nice tool in VFT repo for testing FCS in console. This is what it shows for FCS project itself.
First run
```
ParseAndCheckProject(FSharp.Compiler.Private.fsproj)...
Finished successfully in 00:00:58.8495450 
```
Second run, no changes anywhere
```
cParseAndCheckProject(FSharp.Compiler.Private.fsproj)...
Finished successfully in 00:00:05.8005010
```
Third run, no changes anywhere (@dsyme it takes 5 seconds for nothing?..)
cParseAndCheckProject(FSharp.Compiler.Private.fsproj)...
Finished successfully in 00:00:05.4934968
```
Run after `service.fs` was changed (it's one of the last files in the proj file)
```
cParseAndCheckProject(FSharp.Compiler.Private.fsproj)...
Finished successfully in 00:00:11.1900123
```
So the caching seems to work.

**Comment by vasily-kirichenko** [comment]
Ah, FCS has a lot of errors, so the symbol suggester takes all the CPU time:

![image](https://user-images.githubusercontent.com/873919/30936058-4f9353c0-a3db-11e7-80b9-d0c8acb3444c.png)

/cc @forki

**Comment by forki** [comment]
* why does it have "a lot of errors"?

**Comment by vasily-kirichenko** [comment]
@forki I think it's because the perf tool has outdated project option hardcoded into it.

**Comment by forki** [comment]
> AFAIK ParseAndCheckProject is smart and rechecks files starting and below the top changed file only

pure speculation following: I think @auduchinok said that FCS is adding a `\n` or something at the end of the parsed files. Maybe just maybe all out-of-date checks evaluate to false because of this!? can we somehow trace where it starts to compute?

**Comment by auduchinok** [comment]
@forki it doesn't add it to actual files, only to buffers being parsed, changing AST ranges. It checks timestamps of files to find a file to start.

**Comment by forki** [comment]
so there must be something else going on.

**Comment by vasily-kirichenko** [comment]
@forki I don't think FCS behavior is wrong at all. It rechecks only the most upper changed file and all files below it. If we switch to `ParseAndCheckFileInProject`, it may not give us any perf improvements because we often change view or state of a Fable page, which are referenced in top level files like `App.fs`, which are at the bottom in fsproj, so we decide to recheck those top level files as well and call `ParseAndCheckFileInProject` for them, which looks good until we realize that FCS _will check all the files above them_. So, effectively, all the files starting from the changed one and down to the top level files will be rechecked anyway.

**Comment by forki** [comment]
As I said above: many of my files are "fable base library" files. If it would never recheck these then it's already a great thing

**Comment by alfonsogarciacaro** [comment]
> It checks timestamps of files to find a file to start.

Against what? Against the `LoadTime` of `FSharpProjectOptions`? I didn't notice any difference by trying different values for it 😕 Or is the time when the Checker is created what is taken into account?

**Comment by vasily-kirichenko** [comment]
It keeps last write time for each checked file and compare it with the actual one to decide if a file should be rechecked.

**Comment by forki** [comment]
@alfonsogarciacaro another question: does fable watch cache parsed fsproj? When I save fs file in watch mode it always prints "Parsing ./myProj.fsproj..." - even when I didn't touch that file

**Comment by alfonsogarciacaro** [comment]
Thanks for the confirmation @vasily-kirichenko! I've always wondered how costly is checking the timestamp of files, specially for a big project, but I guess this is not the bottleneck. I'll try to run a profiling session in VS with Fulma docs to see if I find something.

@forki `Parsing ./myProj.fsproj...` is just the way Fable has to say it's running `ParseAndCheckProject` and thus parsing the whole project (even if the .fsproj remains untouched). Also, there's no actual Fable watch now, each JS client must take responsibility of watching the files and send requests to Fable. I don't recall the details right now but Webpack watcher is more advanced in the sense it can detect when multiple files have been saved at the same time and send less requests so `ParseAndCheckProject` is only called once. However, the watcher in fable-splitter is less sophisticated and you need to parse the whole project for every tiny change. This can certainly be improved.

**Comment by forki** [comment]
> This can certainly be improved.

![image](https://user-images.githubusercontent.com/57396/30966288-b5d3a1a8-a458-11e7-9d81-5601d065799c.png)

**Comment by vasily-kirichenko** [comment]
https://github.com/fsharp/FSharp.Compiler.Service/pull/810 

@dsyme could you please take a look?

**Comment by vasily-kirichenko** [comment]
#810 seems to work OK. I cherry picked the changes to VFT and look at `FSharpCheckFileResults.ImplementationFiles` in the debugger:

![image](https://user-images.githubusercontent.com/873919/30984530-41e3386a-a496-11e7-921e-3f95c85acb4b.png)

> Before Fable kept a dependency map for this reason, I removed it after the Webpack integration but we could bring it back.

@alfonsogarciacaro could you bring this back and try to use `ParseAndCheckFileInProject` with FCS from #810?

**Comment by alfonsogarciacaro** [comment]
I'll do! Thanks a lot for this @vasily-kirichenko!

**Comment by forki** [comment]
Does it make watch mode faster?

**Comment by vasily-kirichenko** [comment]
@forki I don't know :) It _may_.

**Comment by alfonsogarciacaro** [comment]
Well, after deciphering the needed commands to build FCS for netstandard, [I created a Fable build to test @vasily-kirichenko PR](https://github.com/fable-compiler/Fable/commit/9e6a49a4e1eeb9d5f63e6bfdb38f639826046bce), tested with a project with many files like Fulma docs and watch compilations went from 8 seconds to less than 1 sec (the Fable part) so, yeah, it's _kind of_ an improvement :wink: :clap: :tada: :clap: ❤️ (ping @mangelmaxime).

In my quick test I didn't see any problem, but I think @vasily-kirichenko's concerns are right (and probably I also need to tweak another part of the code) so for now I'll try to release it as an opt-in.

Thanks again for this @vasily-kirichenko! Just one quick question: what's the best way to deal with the `version` parameter in `ParseAndCheckFileInProject`? For now [I'm just using always 0](https://github.com/fable-compiler/Fable/blob/9e6a49a4e1eeb9d5f63e6bfdb38f639826046bce/src/dotnet/dotnet-fable/StateUtil.fs#L78) and seems to work well.

**Comment by forki** [comment]
so what do I need to do to get it?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro That's a good news :)
If I can help to test or something feel free to ping me.

**Comment by vasily-kirichenko** [comment]
@alfonsogarciacaro the version is an `int` value that represents a "version" of file. In VFT we pass hash code of Roslyn's `Document.GetTextVersion() : VersionStamp` https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Workspace/Solution/VersionStamp.cs. AFAIK it's just a fast unique "identifier" or version of a file content (it's fast compared to, say, calculating SHA-1). 

However, as far as I can see, this version thing is not used in `ParseAndCheckFileInProject` (which uses `parseAndCheckFileInProjectCache` only https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2312). It's used in a couple of other caches though. So, I think we are safe for now just passing zero to it. However, if it's easy to do, we can pass something like `int <file_last_wirte_time>.Ticks`.

**Comment by vasily-kirichenko** [comment]
However, 

* Ionide uses something `TextDocument.version: float` (which comes from VS Code itself?)
* Other editors, like Emacs, use `0`, see https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/FsAutoComplete.Stdio.fs#L18

So, we are fine :)

**Comment by vbfox** [comment]
@vasily-kirichenko `TextDocument.version` in VSCode is a version of an open document. VSCode increment it each time a "TextDocument" is edited (Documents not opened in the UI have no version and closing then re-opening a document reset the version)

**Comment by alfonsogarciacaro** [comment]
Great, thanks for the confirmation! Ok, I've pushed Fable 1.3.0-beta-001 which includes @vasily-kirichenko's custom FCS build and _seems_ to work. Please give it a try. Being at opt-in you'll have to set `extra.optimizeWatch` in the Fable JS client options. For example, for Webpack:

```js
            {
                test: /\.fs(x|proj)?$/,
                use: {
                    loader: "fable-loader",
                    options: {
                        define: isProduction ? [] : ["DEBUG"],
                        extra: { optimizeWatch: true }
                    }
                }
            },
```

Incidentally, with this version if you don't set `optimizeWatch`, watch compilations are **slower** than before. I tried to keep the non-optimized code the same, so I'm not sure what's the issue. Maybe because the custom FCS build?

**Comment by vasily-kirichenko** [comment]
Have you built it in release mode?

**Comment by vasily-kirichenko** [comment]
Hmm. It works the same for me with and without the flag - about 8 seconds from editing a file to refresh the page.

**Comment by alfonsogarciacaro** [comment]
Ok, that's interesting, the trick seems to be resetting `LoadTime` in the FSharpProjectOptions to `DateTime.Now` or not.

- `ParseAndCheckProject` best results by setting  `LoadTime` to `DateTime.Now` everytime
- `ParseAndCheckFileInProject` best results by **NOT** setting  `LoadTime` to `DateTime.Now` everytime

**Comment by alfonsogarciacaro** [comment]
Yes, I built FCS with release mode :+1:

**Comment by forki** [comment]
like https://github.com/SAFE-Stack/SAFE-BookStore/pull/185? Do not notice improvements with it

**Comment by alfonsogarciacaro** [comment]
> Hmm. It works the same for me with and without the flag - about 8 seconds from editing a file to refresh the page.

Weird, what do you see? `Parsing XXX.fsproj` or `Parsing XXX.fs`? (should be the second when using the `extra.optimizeWatch` flag) Has anyone else tried too? @forki @MangelMaxime

**Comment by forki** [comment]
@alfonsogarciacaro 

![image](https://user-images.githubusercontent.com/57396/31017139-d6167560-a527-11e7-8fa8-42e7b56fcb3c.png)

**Comment by forki** [comment]
so it's parsing full project

**Comment by vasily-kirichenko** [comment]
yes, I see `Parsing XXX.fsproj`

About `LoadTime`, yes you should change it _only if the project file itself has been changed_.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry, I forgot to tell you! 🤦‍♂️  There was an issue with latest Fable and fable-loader, so you need to update fable-loader too to 1.1.3, see https://github.com/SAFE-Stack/SAFE-BookStore/pull/186

**Comment by vasily-kirichenko** [comment]
```cmd
λ yarn upgrade fable-loader
yarn upgrade v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ fable-loader@1.1.3
Done in 6.44s.
```

```
webpack: Compiling...
Parsing ./EsExplorer.fsproj...
fable: Compiled src\Errors\View.fs
Hash: fb5708a4bcf814162a18
Version: webpack 3.6.0
Time: 3868ms
                                   Asset      Size  Chunks                    Chunk Names
                               bundle.js   2.56 MB       0  [emitted]  [big]  main
    0.1755e05c83db05bb6189.hot-update.js   25.4 kB       0  [emitted]         main
    1755e05c83db05bb6189.hot-update.json  43 bytes          [emitted]
                           bundle.js.map   2.37 MB       0  [emitted]         main
0.1755e05c83db05bb6189.hot-update.js.map   7.46 kB       0  [emitted]         main
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
[./src/Errors/View.fs] ./src/Errors/View.fs 6.85 kB {0} [built]
    + 471 hidden modules
webpack: Compiled successfully.
```

**Comment by MangelMaxime** [comment]
I get this result:

```shell
webpack: Compiling...
Parsing ./src/Fulma/Elements/Button/View.fs...
fable: Compiled src\Fulma\Elements\Button\View.fs
Hash: 5d1e08c584c2fdd92895
Version: webpack 3.6.0
Time: 7248ms
        Asset       Size  Chunks                    Chunk Names
    bundle.js    3.19 MB       0  [emitted]  [big]  main
bundle.js.map    2.26 MB       0  [emitted]         main
   index.html  913 bytes          [emitted]
 [272] ../node_modules/webpack/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [334] ./src/Fulma/Elements/Button/View.fs 6.93 kB {0} [built]
    + 489 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
       4 modules
webpack: Compiled successfully.
```

**Comment by forki** [comment]
it works on https://github.com/SAFE-Stack/SAFE-BookStore/pull/185!!!!

![fasthmr](https://user-images.githubusercontent.com/57396/31018317-e82742e4-a52b-11e7-852c-ab6430060888.gif)

**Comment by vasily-kirichenko** [comment]
@forki how have you got it working?

**Comment by forki** [comment]
you need latest fable loader + fable.compiler beta + dotnet-fable beta - then it works

**Comment by MangelMaxime** [comment]
@forki What do you mean by it works ? 

I mean, I am doing the watch too but the compile time is still of 7-8 sec. Even, if we see `Parsing ./src/Fulma/Elements/Button/View.fs...`

Is it intended or I missed something about what we are testing here ?

**Comment by forki** [comment]
it works means that refresh time for that login thing in bookstore was 6s and now is 2s

**Comment by vasily-kirichenko** [comment]
@forki I don't see any `prerelease` in https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/paket.dependencies

**Comment by forki** [comment]
https://github.com/SAFE-Stack/SAFE-BookStore/pull/185 <- it's not merged

**Comment by vasily-kirichenko** [comment]
```
source https://nuget.org/api/v2

storage:none

nuget Fable.PowerPack prerlease
nuget FSharp.Core
nuget Fulma prerelease
nuget Fable.Core prerelease
nuget Fable.Compiler prerelease
nuget Fable.Elmish.Browser  prerelease
nuget Fable.Elmish.Debugger prerelease
nuget Fable.Elmish.React prerelease
nuget Fable.Elmish.HMR prerelease

clitool dotnet-fable prelease
```
```
STORAGE: NONE
NUGET
  remote: https://www.nuget.org/api/v2
    dotnet-fable (1.2.4) - clitool: true
      Dotnet.ProjInfo (>= 0.7.4) - restriction: >= netcoreapp2.0
      Fable.Compiler (>= 1.2.4) - restriction: >= netcoreapp2.0
      Fable.Core (>= 1.2.4) - restriction: >= netcoreapp2.0
      FSharp.Core (>= 4.2.3) - restriction: >= netcoreapp2.0
      Microsoft.NETCore.App (>= 2.0) - restriction: >= netcoreapp2.0
    Dotnet.ProjInfo (0.7.4) - restriction: >= netcoreapp2.0
      FSharp.Core (>= 4.1.17) - restriction: >= netstandard1.6
      NETStandard.Library (>= 1.6.1) - restriction: >= netstandard1.6
    Fable.Compiler (1.2.4)
      Fable.Core (>= 1.2.4) - restriction: >= netstandard1.6
      FSharp.Compiler.Service (>= 14.0.2) - restriction: >= netstandard1.6
      FSharp.Core (>= 4.2.3) - restriction: >= netstandard1.6
      NETStandard.Library (>= 1.6.1) - restriction: >= netstandard1.6
      Newtonsoft.Json (>= 10.0.3) - restriction: >= netstandard1.6
      System.Collections.Immutable (>= 1.4) - restriction: >= netstandard1.6
      System.Reflection.Metadata (>= 1.5) - restriction: >= netstandard1.6
      System.Runtime.Loader (>= 4.3) - restriction: >= netstandard1.6
      System.ValueTuple (>= 4.4) - restriction: >= netstandard1.6
    Fable.Core (1.2.4)
      FSharp.Core (>= 4.2.3) - restriction: >= netstandard1.6
      NETStandard.Library (>= 1.6.1) - restriction: >= netstandard1.6
      System.ValueTuple (>= 4.4) - restriction: >= netstandard1.6
    Fable.Elmish (1.0.0-beta-1) - restriction: >= netstandard1.6
...
```
:(

**Comment by vasily-kirichenko** [comment]
```
λ .paket\paket update --force
Paket version 5.100.3
Resolving packages for group Main:
 - Fable.PowerPack 1.2.0
 - dotnet-fable 1.2.4
 - Fable.Compiler 1.2.4
 - Fable.Core 1.2.4
...
```

**Comment by forki** [comment]
wtf?! why is it a paket issue now. arggghhhhhh

**Comment by forki** [comment]
`prerlease` 
`prelease` 

typos - @vasily-kirichenko you are killing me

**Comment by vasily-kirichenko** [comment]
wow. paket should fail with a good error.

**Comment by forki** [comment]
We can't. It's a feature. It's allowed to use custom prerelease tags. If
it's not exactly "prerelease" it will filter for that tag.

I admit it can be usability issue

Am 29.09.2017 17:43 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
I think it's a rather big issue. We should think about it more.

**Comment by vasily-kirichenko** [comment]
Ah, forget to say, it finally works and very nicely :)

![1](https://user-images.githubusercontent.com/873919/31032775-1766cdba-a566-11e7-8c81-f0b793f3395a.gif)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ok I tested it on my personal laptop.

With the new optimization it take between 3 and 3,5 seconds versus 8-9 seconds before. I think 80% of the time is due to webpack doing some stuff. I will try to see if I can reduce webpack time too (it's probably related to the assets and plugins used).

Great job :clap:

**Comment by forki** [comment]
@alfonsogarciacaro what about fable-splitter? Can we get that to work as well?

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks everybody for checking. I will close this issue now as it should be fixed by #810, hopefully the PR is merged soon :) If you find any issue with the beta please report it to the Fable repo. But note the dependency tree is not implemented, so when `optimizeWach` is set and you change something that causes an error in another file, probably Webpack will just compile happily.

@forki The change is done in Fable daemon, so it should apply to any JS client, including fable-splitter (just make sure you pass the `extra.optimizeWatch` in the Fable options). When we add the dependency tree I'll guess it will require some works, as Webpack manages dependencies automatically but we'll have to do it for the fable-splitter by ourselves.

**Comment by vasily-kirichenko** [comment]
@alfonsogarciacaro Don just merged my PR and published FCS 15.0.1 https://github.com/Microsoft/visualfsharp/pull/3659#issuecomment-333613347, so you can try to update to it.

About dependency tree, it does make life a bit hard because outdated js code throws cryptic exceptions at runtime :(

**Comment by alfonsogarciacaro** [comment]
Ah, great! Much better to use the package reference than a custom build :) I will push a new version and try to add the dependency tree too :+1:

**Comment by vasily-kirichenko** [comment]
Thank you :)
