### ISSUE TITLE
The FSharp.Compiler.Service.Interactive can interpret a script or just compile and execute 

### ISSUE THREAD

**Issue by shengfeng** [fsharp/FSharp.Compiler.Service#802]
I am learning the F#, and very interested in hosting F# interactive. However, I have no idea whether this interactive can interpret a script language. Because I want to use the F# in a IOS app, and ios can not support jit, I want to know whether the FSharp.Compiler.Service.Interactive can interpret the .fsx file in IOS.

**Comment by forki** [comment]
there seems to be a way. somehow. 
see http://continuous.codes/ and ask @praeclarum how he did that magic ;-)

**Comment by nosami** [comment]
F# Interactive uses Reflection.Emit which is definitely a no-go in iOS.

@praeclarum wrote an IL Interpreter :)

I prototyped [this](https://twitter.com/JasonImison/status/798981483583176705) some time ago. Mine did the compilation on the PC then sent the compilations over to the device (simulator only though)

**Comment by shengfeng** [comment]
@nosami So the f # interpreter firstly compiles and then interprets through the reflection? Can this language can be a script language?

**Comment by nosami** [comment]
You can't use Reflection.Emit on an iOS device. This means that you will not be able to use F# interactive on a device either (fsharpi / fsi compiles F# to Reflection.Emit calls. See [here](https://gist.github.com/nosami/f777919512012d0892c4882f54743038) how it looks)

@praeclarum worked around this limitation by writing his own IL interpreter. His interpreter doesn't rely on Reflection.Emit - it reads IL from an assembly (compiled by fsharpc or Roslyn) directly. 

However, it isn't open source, so you would need to write your own (a huge task). You might be able to use [DotNetAnywhere](https://github.com/chrisdunelm/DotNetAnywhere)

**Comment by dsyme** [comment]
Closing old question/discussion
