### ISSUE TITLE
project cracker source files should contains .fsi

### ISSUE THREAD

**Issue by enricosada** [fsharp/FSharp.Compiler.Service#803]
using project cracker on a project with .fsi files, these are not returned in `FSharpProjectOptions.Sourcefiles`

this mean the need of ugly hack like https://github.com/fsharp/FsAutoComplete/blob/e5095da2b18da6fb6eb2fe7a9355d36e2fae9bf7/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L359-L369 to put the .fsi files BEFORE the .fs files

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsharp/FSharp.Compiler.Service/pull/812

**Comment by dsyme** [comment]
Now in master, thanks
