### ISSUE TITLE
project cracker should throw if invalid project file (xml invalid for example)

### ISSUE THREAD

**Issue by enricosada** [fsharp/FSharp.Compiler.Service#804]
project cracker should throw if invalid project file (xml invalid for example)

now the `ProjectCracker.GetProjectOptionsFromProjectFileLogged` just an empty `FsharpProjectOptions` (zero refs, zero source files) and the error (exception info) in the log

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsharp/FSharp.Compiler.Service/pull/812

**Comment by dsyme** [comment]
Fixed in master, will release in 16.0.2 eventually
