### ISSUE TITLE
missing tags for v14.x

### ISSUE THREAD

**Issue by enricosada** [fsharp/FSharp.Compiler.Service#805]
latest tag is `13.0.0`, while latest [released nuget package](https://www.nuget.org/packages/FSharp.Compiler.service/) is `14.0.2`

/cc @dsyme

**Comment by dsyme** [comment]
I did the 14.0.2 release from Microsoft/visualfsharp.  I integrated all the code here, I believe the head of master is the same ass the 14.0.2 tag, unless I'm mistaken and have missed something
