### ISSUE TITLE
Replace ParseFileInProject with ParseFile

### ISSUE THREAD

**Issue by auduchinok** [fsharp/FSharp.Compiler.Service#806]
When https://github.com/Microsoft/visualfsharp/pull/3601 is merged, `ParseFileInProject` will fallback to `ParseFile` and generate parsing options on each call.
If `ParseFileInProject` is going to become deprecated, docs should be updated accordingly.

**Comment by dsyme** [comment]
This has been done

**Comment by goswinr** [comment]
@dsyme thanks for all these improvements. The Docs are still out of date no?
http://fsharp.github.io/FSharp.Compiler.Service/editor.html
Shall I open a separate issue for that?

**Comment by forki** [comment]
Even better: try to directly write something down in PR. ;-)

But yes new docs issue is probably good idea

Am 04.10.2017 07:30 schrieb "Goswin" <notifications@github.com>:

**Comment by goswinr** [comment]
@forki I first have to correctly understand the FCS API .  Some interesting information seems to be hidden in the open and closed Github issues here.

**Comment by forki** [comment]
Yes absolutely. And I think we should require docs changes when we accept
pull requests that open APIs or change them in the future.

Am 04.10.2017 08:24 schrieb "Goswin" <notifications@github.com>:

**Comment by dsyme** [comment]
We just need to republish the docs.  I'll do that
