### ISSUE TITLE
The summary in NuGet is strangely formatted, breaks unevenly

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/FSharp.Compiler.Service#808]
I think this picture explains what I mean by this:

![image](https://user-images.githubusercontent.com/16015770/30835597-37ee983e-a259-11e7-99b2-ceafe96fe482.png)

This is how it is shown when you browse for `FSharp.Compiler.Service` in NuGet Package Manager in Vsiaul Studio. Not sure where that text comes from, but removing the newlines and indentation should render it more humanly readable ;).

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsharp/FSharp.Compiler.Service/pull/811 :)

**Comment by dsyme** [comment]
Fixed in master
