### ISSUE TITLE
Build on Master failing for Mac/Linux builds

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/FSharp.Compiler.Service#813]
Something's amiss with master:

![image](https://user-images.githubusercontent.com/16015770/31048182-724f50c8-a618-11e7-92d7-1be62d86c6a1.png)

I did a quick look through #811, it looks like NuGet has trouble finding a certain local path, but I know too little of the build system on Linux to be of much help here.

(edit) And another quick look, it seems to have been broken for about a month now:

![image](https://user-images.githubusercontent.com/16015770/31069393-9667a63c-a75c-11e7-8e55-9b9cc4ead3a2.png)

The difference between then and now is that it seems that earlier Mac/Linux build do not try to call NuGet.exe. That command seems to be introduced through the merge of #793. That issue contains 250 updates, so it may be hard to find the culprit.

**Comment by dsyme** [comment]
This now appears fixed (doing final full CI matrix now)

**Comment by abelbraaksma** [comment]
@dsyme, only for a moment it worked (and indeed, [history shows that was around the time you closed this](https://travis-ci.org/fsharp/FSharp.Compiler.Service/builds)), but the next non-canceled run was failing again. Reopen?

**Comment by abelbraaksma** [comment]
Now it seems to [work again on master](https://travis-ci.org/fsharp/FSharp.Compiler.Service/builds/283143396). Tx! (and ignore my previous comment)
