### ISSUE TITLE
GetDeclarationLocation returns NoSourceCode if file does not exist.

### ISSUE THREAD

**Issue by amieres** [fsharp/FSharp.Compiler.Service#821]
Right before finishing, GetDeclarationLocation checks to see if the file exists and if it does not then fails returning  DeclNotFound  NoSourceCode.
#### Repro steps

```
fsautocomplete
parse "test.fsx"
let abc = 1
let xyz = abc
<<EOF>>
{"Kind":"info","Data":"Background parsing started"}
{"Kind":"errors","Data":{"File":"<path>\\test.fsx","Errors":[]}}
finddecl "test.fsx" "let xyz = abc" 2 11
```

#### Expected behavior

```
Find declaration: ({Line = 2;
  Col = 11;}, 13, "let xyz = abc", ["abc"])
DeclFound
  <path>\test.fsx (1,4--1,7) IsSynthetic=false
{"Kind":"finddecl","Data":{"File":"<path>\\test.fsx","Line":1,"Column":5}}
```

#### Actual behavior

```
Find declaration: ({Line = 2;
  Col = 11;}, 13, "let xyz = abc", ["abc"])
DeclNotFound NoSourceCode
{"Kind":"error","Data":{"Code":1,"Message":"Could not find declaration","AdditionalData":{}}}
```
#### Known workarounds

Create an empty file "test.fsx"

#### Related information 

I understand this is on purpose, but is it necessary?
None of the other functionality like tooltips, complete, etc require the file to actually exist, 
why should this one?

While the workaroung is simple enough, it is a bit messy. 
Even worse though, is the process of finding out why it failed. Since FsAutoComplete does not return the reason "NoSourceCode" the only way to discover it is by debugging FsAutoComplete and then checking the source code for FSharpCompilerService to see why it didn't like it. 
NoSourceCode is a bit of a misnomer because the source code was already provided, it is the file that is missing not the source code.

**Comment by dsyme** [comment]
@amieres I agree, please send a PR

**Comment by amieres** [comment]
PR #822
