### ISSUE TITLE
Provide FSharpEntity.EnclosingEntity

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FSharp.Compiler.Service#830]
In https://github.com/Microsoft/visualfsharp/pull/3803 I do the following:

* get an open declaration (which is now available as a property in `FSharpFileCheckResults` and presented as `FSharpEntity []`)
* check if any of symbols defined in each of the modules / namespaces above is used in the scope this particular open declaration is open

Currently I call `FSharpEntity.MembersFunctionsAndValues` for each namespace/module and it's the bottleneck - on middle sized files the analyzer takes several seconds to finish, on `TypeChecker.fs` it takes ~2 minutes, which is too slow.

So I'm trying to use different approach: get _enclosing entity_ of each symbol uses and check if it corresponds to a module/ns from open declarations, which eliminates calling `MembersFunctionsAndValues` entirely. Unfortunately, only values, functions and members have `EnclosingEntity` (that is, modules for my purpose). I need this property for `FSharpEntity` too.

This approach is indeed a lot faster. Ignoring `FSharpEntity` and checking only vals and functions via `EnclosingEntity` processes `TypeChecker.fs` in 4 seconds, smaller files in tens of milliseconds.

I tried to add this here https://github.com/vasily-kirichenko/visualfsharp/commit/39173f6d2844175277e675b5e8f9a4ca804fa342, but I've completely lost. 

`EnclosingEntity` should contain proper value for both F# and IL types and modules and namespaces (`None` - for root namespaces).

@dsyme could you please suggest a proper way to add this functionality?

**Comment by dsyme** [comment]
Yes, it's not there because of a bit of a flaw in the TAST.  I've put it on my TODO list to try to root this problem out.  We will need it for other reasons too

**Comment by vasily-kirichenko** [comment]
Thanks a lot!

**Comment by dsyme** [comment]
@auduchinok I managed to improve the performance of unused opens https://github.com/Microsoft/visualfsharp/pull/4497/ without implementing this.  I'd still like to get it implemented though, it would make things simpler and faster

**Comment by auduchinok** [comment]
@dsyme I've checked the new unused opens implementation and it's indeed works much faster on an average solution/files, however getting children of something like `JetBrains.Util` still takes several seconds on a small file and works longer than the file type check. The good news is tweaking unused imports to use the new `DeclaredEntity` made performance great on this file.

I'm looking into opening a PR with usage of DeclaredEntity, but will try to fix https://github.com/Microsoft/visualfsharp/issues/4658 before.
