### ISSUE TITLE
QuickParse does not get partial name for "x.ToString().Co"

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#837]
I am using FCS 17.0.1 and trying to apply `QuickParse.GetPartialLongNameEx`
to a string "x.ToString().Co". I expect it to get `Co` as the partial name
so that I can use this info on code completion, this is the part to be
replaced in the editor with one of the completion candidates.

But the actual returned partial name is empty. I have to check for this
and do own poor man parsing for finding `Co` for replacement.

Is this result of `QuickParse` expected?

**Case1.fsx**

```fsharp
#r @"..\packages\FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.dll"
open Microsoft.FSharp.Compiler

let lineStr = "x.ToString().Co"

let partialName = QuickParse.GetPartialLongNameEx(lineStr, 14)
partialName
|> printfn "%A"
```

**Result, note empty PartialIdent**

```
[Loading C:\ROM\FarDev\Code\FSharpFar\z.new\Case1.fsx]
{QualifyingIdents = [];
 PartialIdent = "";
 EndColumn = 14;
 LastDotPos = None;}
namespace FSI_0005
  val lineStr : string
  val partialName : Compiler.PartialLongName
```

**Comment by nightroman** [comment]
Is it something to be addressed or am I just wishing too much?

**Comment by dsyme** [comment]
@nightroman I think we would accept this as a fix - can you submit a PR for your poor man parsing fix, or submit a failing test?  Preferably submit to http://github.com/Microsoft/visulfsharp

**Comment by nightroman** [comment]
I noticed that the similar `QuickParse.GetPartialLongName` gets the expected result.

So my current workaround is to call it in addition to `QuickParse.GetPartialLongNameEx` in order to get the correct `PartialIdent`:

```fsharp
let ident = QuickParse.GetPartialLongNameEx(lineStr, caret.X - 1)
let partialIdent =
    if ident.PartialIdent.Length > 0 then
        ident.PartialIdent
    else
        // correct PartialIdent
        QuickParse.GetPartialLongName(lineStr, caret.X - 1) |> snd
```

@dsyme , sorry that I cannot contribute more than this report and analysis.
