### ISSUE TITLE
The AST for functions differs if they're declared with point-free style 

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#838]
Consider the following two ways of declaring an operator:

```fsharp
let (<!>) mapping option = Option.map mapping option

let (<!>) = Option.map // point-free, arguments are omitted
```

In both cases the signature is the same `(('a->'b) option) -> 'a option -> 'b option` and conceptually it shouldn't matter whether the function is declared using point-free style. However, the AST provided when parsing the file is different for each case. With the pointful style you get the one you would expect of any other function declaration:

```
METHOD: op_LessBangGreater ["owner: QuickTest"; "val"; "static"; "OptionalInline"]
type: type ('a -> 'b) -> 'a Microsoft.FSharp.Core.option -> 'b Microsoft.FSharp.Core.option
args: [[val mapping]; [val option]]
body: Call (None,val map,[],[type 'a; type 'b],[Value val mapping; Value val option])
```

However in the second case (point-free style) we get an argument-less method returning a lambda:

```
METHOD: op_LessBangGreater ["owner: QuickTest"; "val"; "static"; "OptionalInline"]
type: type ('a -> 'b) -> 'a Microsoft.FSharp.Core.option -> 'b Microsoft.FSharp.Core.option
args: []
body: Lambda
(val mapping,
  Lambda
(val option,
  Call (None,val map,[],[type 'a; type 'b],[Value val mapping; Value val option])))
```

Calling each version is also different, with pointful style:

```
Call(None,val op_LessBangGreater,[ ... ; ... ])
```

Again, a normal call to a method with two parameters, but in the case of point-free style:

```
Application(Application(Call(None,val op_LessBangGreater,[]), [...]), [...])
```

So the method call has no arguments and it's surrounded by two applications. This causes Fable to generate less optimized code. And more seriously sometimes this clashes with Fable optimization to flatten lambdas and causes errors, see https://github.com/fable-compiler/Fable/issues/1199

At the moment I included a warning so Fable users avoid point-free style but, would it be possible to have the same AST no matter which style is used (both for declaration and calls) to improve the user experience?

[Example in Fable REPL](http://fable.io/repl/#?code=let%20add%20a%20b%20%3D%20a%20%2B%20b%0Alet%20add3%20a%20b%20c%20%3D%20a%20%2B%20b%20%2B%20c%0A%0Alet%20apply%20f%20x%20%3D%0A%20%20%20%20match%20f%2C%20x%20with%0A%20%20%20%20%7C%20Some%20f%2C%20Some%20x%20-%3E%20Some%20(f%20x)%0A%20%20%20%20%7C%20_%20-%3E%20None%0A%0Alet%20(%3C!%3E)%20mapping%20option%20%3D%20Option.map%20mapping%20option%0Alet%20(%3C*%3E)%20f%20x%20%3D%20apply%20f%20x%0A%0Alet%20test1()%20%3D%0A%20%20try%0A%20%20%20%20%20%20let%20(Some%20x)%20%3D%20add%20%3C!%3E%20Some%201%20%3C*%3E%20Some%202%0A%20%20%20%20%20%20printfn%20%22test1%3A%20OK%20(%25i)%22%20x%0A%20%20with%0A%20%20%7C%20_%20-%3E%20printfn%20%22test1%3A%20Error%22%0A%20%20%0A%0Alet%20(%3C!!%3E)%20%3D%20Option.map%0Alet%20(%3C**%3E)%20%3D%20apply%0A%0Alet%20test2()%20%3D%0A%20%20try%0A%20%20%20%20%20%20let%20(Some%20x)%20%3D%20add%20%3C!!%3E%20Some%201%20%3C**%3E%20Some%202%0A%20%20%20%20%20%20printfn%20%22test2%3A%20OK%20(%25i)%22%20x%0A%20%20with%0A%20%20%7C%20_%20-%3E%20printfn%20%22test2%3A%20Error%22%0A%20%20%0A%20%20%0A%0Atest1()%0Atest2()%0A&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2)

FCS 17.0.1

**Comment by sandeepc24** [comment]
Hi @alfonsogarciacaro , Not sure if this is a valid test case but following didn't work in REPL. Please delete it if you think it is no valid test case.

```
let add a b = a + b
let add3 a b c = a + b + c
let add4 a b c d = a + b + c + d

let apply f x =
    match f, x with
    | Some f, Some x -> Some (f x)
    | _ -> None

let (<!>) mapping option = Option.map mapping option
let (<*>) f x = apply f x

let test1() =
  try
      let (Some x) = add4 <!> Some 1 <*> Some 2 <*> Some 3 <*> Some 4
      printfn "test1: OK (%i)" x
  with
  | _ -> printfn "test1: Error"
  

let (<!!>) = Option.map
let (<**>) = apply

let test2() =
  try
      let (Some x) = add <!!> Some 1 <**> Some 2
      printfn "test2: OK (%i)" x
  with
  | _ -> printfn "test2: Error"
  
  

test1()
test2()

```

**Comment by dsyme** [comment]
@alfonsogarciacaro The ASTs are different by design I'm afraid. In F# there can be a detectable difference between declaring a function-valued value/property and a function/method taking explicit arguments

You can detect this difference e.g. when using FCS ASTs, or when using reflection in .NET

**Comment by dsyme** [comment]
I'll close as this is by design for F#

**Comment by alfonsogarciacaro** [comment]
Thanks for the explanation @dsyme. It's a pity because users expect both styles to be equivalent but the AST generated with point-free is less optimized than a normal method, but I understand the reasoning.

**Comment by kjnilsson** [comment]
Is the .NET compiler able to optimise these cases or does it also generate different IL for these?
