### ISSUE TITLE
Build.cmd file is in the wrong folder, and the debug switch is not supported

### ISSUE THREAD

**Issue by ScottHutchinson** [fsharp/FSharp.Compiler.Service#845]
On Windows, in a Dev Cmd prompt (as Admin), when I cd to the fcs folder where the build.cmd file is located and run build.cmd debug, there are two errors:

Error 1: The system cannot find the path specified. This is apparently caused by the line "cd fcs" in build.cmd. Copying the build.cmd file from the fcs folder to the root (one level higher) fixes this error. See https://gist.github.com/ScottHutchinson/19a7fcdc945e538e22069d3c88658d29#file-fsharp-compiler-service-build-cmd-error-txt-L95

Also, I noticed that in the https://github.com/Microsoft/visualfsharp repo, there is a build.cmd in both the root and fcs folders.

And the DEVGUIDE.md file does not say where to find the build.cmd file, so I had to search for it. Same for the .sln file, which the DEVGUIDE.md file says is named ".\FSharp.sln", but is actually "fcs\FSharp.Compiler.Service.sln".

Error 2: Target "debug" is not defined. Not sure just what to do about this error. See https://gist.github.com/ScottHutchinson/19a7fcdc945e538e22069d3c88658d29#file-fsharp-compiler-service-build-cmd-error-txt-L224

**Comment by dsyme** [comment]
@ScottHutchinson The README.md in this repo says to use

    fcs\build.cmd

without the cd.  Also the same in the visualfsharp repo (which is why we ask you to do this)

If you want debug code just build in debug configuration from the IDE or:

    msbuild  fcs\FSharp.Compiler.Service\FSharp.Compiler.Service.fsproj /p:Configuration=Debug

(just cloning the repo to make sure I haven't made a mistake in these things)
