### ISSUE TITLE
`GetProjectOptionsFromScript` on dotnet core missing references

### ISSUE THREAD

**Issue by duckmatt** [fsharp/FSharp.Compiler.Service#847]
`GetProjectOptionsFromScript("test.fsx", source)` on dotnet core is returning the following `FSharpProjectOptions.OtherOptions`:

```
"--noframework"
"--warn:3"
"-r:C:\\Users\\xxxxx\\.nuget\\packages\\fsharp.core\\4.3.2\\lib\\netstandard1.6\\FSharp.Core.dll"
```

With `GetProjectOptionsFromScript("test.fsx", source, assumeDotNetFramework = false)`. (p.s. is this an intended use case for `assumeDotNetFramework`?)

I get better results of:

```
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\mscorlib.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Console.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Private.CoreLib.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.ObjectModel.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Runtime.Extensions.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Linq.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Net.Requests.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Runtime.Numerics.dll"
"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.5\\System.Private.CoreLib.dll"
"C:\\Users\\xxxxx\\.nuget\\packages\\fsharp.core\\4.3.2\\lib\\netstandard1.6\\FSharp.Core.dll"
```

It looks like the relevant line of code is the following:

https://github.com/fsharp/FSharp.Compiler.Service/blob/30127fa32cb0306cb81d95836cfee4ea5c116297/src/fsharp/CompileOps.fs#L1837-L1849

However `System.ComponentModel.DefaultValueAttribute` is under `System.Private.CoreLib` on dotnet core, so we're not getting `System.Runtime` as a reference

#### Repro steps

`let (options, _diagnostics) = checker.GetProjectOptionsFromScript("test.fsx", source) |> Async.RunSynchronously`

`options.OtherOptions` is missing references such as `System.Runtime`

#### Expected behavior

`GetProjectOptionsFromScript` to return `FSharpProjectOptions` with list of references that will allow a script file to be type checked.

#### Actual behavior

`FSharpProjectOptions` missing references such as `System.Runtime`

#### Known workarounds

Client of API to populate list of references themselves

#### Related information 

* Operating system: Windows 10
* Version: 17.0.1
* NET Core 2.0.5 and .NET Core SDK 2.1.4.

**Comment by alfonsogarciacaro** [comment]
I faced the same issue and I'm just going through `OtherOptions` and replace "System.Private.CoreLib" with "System.Runtime". Parse and checking seem to work after that but `FSharpCheckProjectResults.AssemblyContents.ImplementationFiles` just return an empty list :/

**Comment by fangyi-zhou** [comment]
Same problem here

After `assumeDotNetFramework = false`, I'm getting things like
"""
The type referenced through 'System.SByte' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'
"""
