### ISSUE TITLE
Is it possible to get the Range associated with FSharpMemberOrFunctionOrValue?

### ISSUE THREAD

**Issue by stersay** [fsharp/FSharp.Compiler.Service#850]
The following relates to Microsoft.FSharp.Compiler.SourceCodeServices:

In some FSharpExpr cases there is a FSharpMemberOrFunctionOrValue component, such as the second component of BasicPatterns.Call.  

Is it possible to get the Range associated with this FSharpMemberOrFunctionOrValue?  Can it be derived from the Range of the Call expression in general?

**Comment by dsyme** [comment]
Do you mean 
* the range of the identifier, e.g. the range of ``abc`` in ``let abc () = ....``
* the range of the full definition
* the scope over which ``abc`` is accessible?

**Comment by stersay** [comment]
Thanks for the quick reply!

I'd like to know the range of the identifier, as in the specific occurrence of `abc` in a call `abc def ghi` or a let `let abc = ...` or similar.

The reason is that I want to report the results of an analysis at the level of particular occurrences of identifiers, for example that this occurrence of `abc` in `abc def ghi` is being used at a particular type (according to this analysis).

**Comment by dsyme** [comment]
The DefinitionLocation (or ImplementationLocation or something) on the FSharpSymbol should do the trick?

**Comment by stersay** [comment]
That is probably ok for the let example, but I am more interested in the call.  For example, suppose the input is a file containing:

`module Lib`
`let f xs = (List.map  (fun x -> x+1)) xs`

It's possible to determine from the `FSharpExpr` for the call `(List.map  (fun x -> x+1)) xs` that it occupies the range (2,11--2,40) and by decomposing it using `BasicPatterns.Call(None, mfv, [], [int; int], [arg1; arg2])` the ranges of `arg1` and `arg2`, which are also `FSharpExpr`, can be determined as (2,25--2,35) and (2,38--2,40).  

However, it's not clear to me how to determine that this occurrence of `List.map`, which is represented as `mfv : FSharpMemberOrFunctionOrValue` in the BasicPatterns.Call above, occupies the range (2,12--2,20).  

I don't know the design of the FCS interface well, so it's possible I am missing something obvious...

**Comment by dsyme** [comment]
@stersay I believe you are correct - that information is in a SymbolUse, not a Symbol. If you parse/check the document and call GetAllUsesOfAllSymbols then you may be able to look up the range of that symbol use.

**Comment by stersay** [comment]
Ok, that's helpful, thanks!
