### ISSUE TITLE
running ./build.sh results in error

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#851]
#### Repro steps

Provide the steps required to reproduce the problem

1. from folder fas run ./build.sh

#### Expected behavior

No error

#### Actual behavior

: line 7: cd: fcs: No such file or directory

#### Related information 

osx netstandard2 and mono installed

**Comment by dsyme** [comment]
Run it from the top level

    fcs/build.sh

would be good to submit the little fix for that
