### ISSUE TITLE
Problem: Compile to DLL in NetCore2.0

### ISSUE THREAD

**Issue by CoFlows** [fsharp/FSharp.Compiler.Service#857]
Compiling to a DLL doesn't work consistently in NetCoreApp 2.0

I have a attached a zipped project as an example.

Please note:
1) The dll is created when compiling.
2) The dll appears to be corrupted. If you look at the Dll contents, it doesn't show proper primitive types as per example given
3) when compiling to dynamic it works
4) NetFramework also works to create a dll that can be loaded

I am using NetCore SDK 2.1.101

[CompileTest.zip](https://github.com/fsharp/FSharp.Compiler.Service/files/1866034/CompileTest.zip)

Thank you so much for you help!

**Comment by dsyme** [comment]
@QuantApp I'll be looking into this, likely on Monday next week (I'm at the F# Exchange conference for the next two days, and was preparing my talk for it today)

**Comment by dsyme** [comment]
Yes, there is a mistake in your flags. You have to use the .NET CoreApp 2.0 reference assemblies, not the implementation assemblies.  Using this:

        let sysDir_base = @"C:\Users\dsyme\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0"

and this:

            yield "--targetprofile:netcore";

worked for me

Thanks!
Don

**Comment by jaccarmac** [comment]
Is there any way to set the `targetprofile` when using the multiargument form of `Compile` on an AST instead of a file?

**Comment by dsyme** [comment]
> Is there any way to set the targetprofile when using the multiargument form of Compile on an AST instead of a file?

Hmm, it looks like there isn't .  You may need to send a PR to add a that to this repo?
