### ISSUE TITLE
Build warning: FSC : warning FS0203: Invalid warning number 'CS1591'

### ISSUE THREAD

**Issue by ivog** [fsharp/FSharp.Compiler.Service#866]
I'm seeing these warning in the build log of Akka.Net

FSC : warning FS0203: Invalid warning number 'CS1591' [D:\work\e5ed5ddbe4b3a95f\src\core\Akka.FSharp\Akka.FSharp.fsproj]

I've searched the code base for FS0203 but couldn't find anything. Not sure what is causing these warning.

**Comment by dsyme** [comment]
Something in your project files is setting CS1591 as a warning to suppress, even in F# projects.  The F# compiler is complaing that it doesn't know about that kind of warning number
