### ISSUE TITLE
Did the  License of  FSharp Interactive change?

### ISSUE THREAD

**Issue by goswinr** [fsharp/FSharp.Compiler.Service#869]
What is the License of FSharp Interactive?

When I start an FSI session via FCS it prints 
```
Microsoft (R) F# Interactive version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
```
previously this was was (e.g version 13.0.0)  :
```
F# Interactive for F# 4.1
Freely distributed under the Apache 2.0 Open Source License
```
The [README.md ](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/README.md)says the licence is MIT.
The [LICENCE](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/LICENSE) says Apache 2.0.

**Comment by dsyme** [comment]
It is MIT as the code comes from Microsoft\visualfsharp which uses MIT.  I will propagate the update

**Comment by goswinr** [comment]
@dsyme I closed it since the question is answered. You can reopen it if you want to keep it on the TODO list.
