### ISSUE TITLE
FSharpEntity.IsByRef does not recognize byref`2

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#876]
With FSharp.Core 4.5+, the `byref` type has 2 generic arguments internally. This is breaking the behavior of `.IsByRef` property.

#### Repro steps

Use `ParseAndCheckProject` on a project containing `byref` type usage, and use `.IsByRef` on an `FSharpEntity` for it.

#### Expected behavior

Returns `true`.

#### Actual behavior

Returns `false`.

#### Known workarounds

Use ```x.IsByRef || x.CompiledName = "byref`2"```.

#### Related information 

Using `FSharp.Compiler.Service` nuget version `25.0.1`.

**Comment by dsyme** [comment]
@Jand42 Proposed fix is here, please take a look https://github.com/Microsoft/visualfsharp/pull/5635

**Comment by Jand42** [comment]
@dsyme Sorry, I haven't tested right now, but my guess would be that
https://github.com/fsharp/FSharp.Compiler.Service/blob/e082581b1a4a6b71d4f55c3741679320bba3cfaf/src/fsharp/symbols/Symbols.fs#L476-L478
also needs to be changed to have 
```fsharp
    (tyconRefEq cenv.g cenv.g.byref_tcr entity || tyconRefEq cenv.g cenv.g.v_byref2_tcr entity)
````
because ```byref`2``` is the underlying type for 4.5. Thanks.

**Comment by dsyme** [comment]
isByrefTyconRef covers that, though admittedly it also covers other cases: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/TastOps.fs#L2938
