### ISSUE TITLE
NuGet package for 26.0.1 is broken

### ISSUE THREAD

**Issue by mcliment** [fsharp/FSharp.Compiler.Service#887]
The package ZIP is broken and can't be used.

The location of the package is this:
https://api.nuget.org/v3-flatcontainer/fsharp.compiler.service/26.0.1/fsharp.compiler.service.26.0.1.nupkg

Using Nuget Package Explorer raises error as well, "End of Central Directory record could not be found" unzipping the file.

**Comment by Jand42** [comment]
I can open it fine, but calling `FSharpChecker.Create` fails, needing reference for `Microsoft.Build.Framework` and also `FSharp.Compiler.Service.MSBuild.v12` of which there no `26.0.1` version on nuget.

**Comment by baronfel** [comment]
My apologies, all. There's one more package that needs to be uploaded and I'm waiting on the appropriate permissions to do so. I'll post back here when it's up.

**Comment by baronfel** [comment]
![image](https://user-images.githubusercontent.com/573979/52720843-0814ce00-2f6e-11e9-88f2-782dff8a9238.png)

I've just pushed the corrected version and Nuget is indexing/validating it. You can check the status at the [nuget page for the package](https://www.nuget.org/packages/FSharp.Compiler.Service.MSBuild.v12/), and once it's done indexing you should be good to go!

Thanks for reporting and reminding me to get on this 👍
