### ISSUE TITLE
Redefine the (|>) operator in a way to reveal passed types

### ISSUE THREAD

**Issue by pkese** [fsharp/FSharp.Compiler.Service#897]
When hovering over an `|>` operator with mouse cursor, I see the following information (in VSCode)

![image](https://user-images.githubusercontent.com/278492/54031163-42a90980-41ae-11e9-90a1-30116a19467a.png)

Notice that there is no information about the generic types that are involved.

If i redefine the `|>` operator as just
```fsharp
let (|>) arg func = func arg
```
..then when hovering over the opearator the same way, I get to see also the types that are involved

![image](https://user-images.githubusercontent.com/278492/54031262-94ea2a80-41ae-11e9-9f7c-37df5bcd36e3.png)

In terms of usability, seeing type information is an improvement, because in longer chains of |> workflows, it is sometimes hard to know what type is being passed around in each step. It would be nice if this was the default.

Please make the compiler service reveal inferred type wherever possible.

A starter solution would be to just replace the definition of operator definitions in the way as described above.

**Comment by Krzysztof-Cieslak** [comment]
Hey @7sharp9, is it connected to #896 ?

**Comment by 7sharp9** [comment]
Yes I think its connected @Krzysztof-Cieslak the types are not calculated for all operators properly.

**Comment by pkese** [comment]
Apparent'y this had been fixed in FCS in the meanwhile.
