### ISSUE TITLE
[Infrastructure] Update readme with information about VF# vs FCS status

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsharp/FSharp.Compiler.Service#898]
I think we should add information to the readme that this is downstream, read-only repository that exists only to have separate documentation and NuGet package. And that all bug reports, feature requests, and pull requests should be done to VF# repo.

**Comment by dsyme** [comment]
Yes please do

This repo also has "the Fable cross-compile PR", which should likely be a fork.

**Comment by Krzysztof-Cieslak** [comment]
I'll leave the PR to @baronfel - it will be easier to write it once, nicely by the native speaker then fixing all my language mistakes ;-) 

Just to sum up what should be there more or less:
* Downstream from MSFT/VF#
* Read-only 
* Hosting documentation
* Publishing NuGet package
* Base for Fable PR
* All development happening in MSFT/VF#
* You can build latest FCS from MSFT/VF#
* All issues and feature request should be reported in MSFT/VF#

**Comment by baronfel** [comment]
Closing as we did this a while back.
