### ISSUE TITLE
[GitHub pages] Release notes link broken

### ISSUE THREAD

**Issue by milbrandt** [fsharp/FSharp.Compiler.Service#904]
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

Go to http://fsharp.github.io/FSharp.Compiler.Service/index.html
In the left column the link "Release Notes" to https://github.com/fsharp/FSharp.Compiler.Service/blob/master/RELEASE_NOTES.md leads to HTTP Status Code 404

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

Either remove the link to release notes or include the relase notes at the target

**Actual behavior**

GitHub error page for HTTP Status Code 404

**Known workarounds**

Go here to the release tab https://github.com/fsharp/FSharp.Compiler.Service/releases

**Related information**

page visited today May 30th, 2019

**Comment by baronfel** [comment]
Thanks for this, looks like we're missing the `/fcs/` portion of the path there. I'll try to get that patched up soon.

**Comment by baronfel** [comment]
Having trouble building the docs locally recently. I'll try to tackle this  failure along with build failures after the next integration point (this week expected).

**Comment by milbrandt** [comment]
Still 404 on release notes

**Comment by baronfel** [comment]
I haven't yet fixed the underlying documentation generation (which was broken quite a while ago) but it is on my radar.
