### ISSUE TITLE
29.0.0 has AssemblyVersion 22.0.3

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#906]
**Repro steps**

download https://www.nuget.org/packages/FSharp.Compiler.Service/29.0.0

watch with dotpeek:

![image](https://user-images.githubusercontent.com/1866463/59200722-2182fb00-8b99-11e9-9d48-6aa1f72cd367.png)

/cc @baronfel 

**Expected behavior**

Higher version than `28.0.0`

**Actual behavior**

`22.0.3`

To cite [this comment](https://github.com/dotnet/fsharp/issues/3408#issuecomment-319529182):

> Versions go up, not down.

Sadly another instance of this error now on an even more 'critical' package... 

This lead to a different hard to debug issue similar to the linked one with suave...

**Known workarounds**

None

**Comment by baronfel** [comment]
Good eye, this is probably related to building with the net sdk and the assemblyinfo getting overridden. We should probably check the build to make sure we're setting msbuild parameters correctly...

**Comment by matthid** [comment]
Thanks!

I'd suggest updating to `29.0.1` and unlisting `29.0.0`. In the end, it didn't even matter in my scenario as `29` was too breaking for assemblies compiled against `28`.
(Well it did matter because without this I would have saved time coming to that conclusion ;))

**Comment by baronfel** [comment]
29.0.1 has been published and 29.0.0 has been unlisted.  I verified the assembly versions on these dlls was correct, so we should be good to go.  Thanks for catching this!
