### ISSUE TITLE
Unable to debug output - ISymUnmanagedBinder2.GetReaderForFile2 fails

### ISSUE THREAD

**Issue by albahari** [fsharp/FSharp.Compiler.Service#909]
I'm working on supporting F# in the upcoming LINQPad 6 release for .NET Core and am running into a tricky problem: I'm unable to get LINQPad's debugger working with the output of FSharp.Compiler.Service.

The issue is that the .pdb file that FSharp.Compiler.Service produces seems to be rejected when I call ISymUnmanagedBinder2.GetReaderForFile2 (it returns E_PDB_NOT_FOUND, when the PDB is  clearly present in the same folder as the DLL).

I'm using the following compilation options:
--debug:full
--targetprofile:netcore
--optimize-
--simpleresolution
--noframework

I'm referencing all of the .NET Core reference assemblies from the Microsoft.NETCore.app.ref NuGet package.

Has anything changed about the way FSharp.Compiler.Service emits PDBs (or is anything different with .NET Core vs .NET Framework?) It's working OK for me in LINQPad 5 with .NET Framework (and an earlier version of FSharp.Compiler.Service).

**Comment by baronfel** [comment]
Can you provide which versions of FCS you are using in v5 and the upcoming v6? That might help narrow down which set of changes introduced this.

**Comment by albahari** [comment]
After further testing, it appears that the problem is unrelated to the FCS version. 

The problem occurs when the project that calls FCS is itself .NET Core, and so binds to the following DLL:
lib\netstandard2.0\FSharp.Compiler.Service.dll

The problem doesn't occur when the project that calls FCS is .NET Framework, and binds to the following:
lib\net461\FSharp.Compiler.Service.dll

Looking at the output in each case, the .pdb file looks very different. In the first case, the .pdb file for a simple query is around 600 bytes, whereas in the second case, it's around 12KB.

Could the netstandard FCS be generating a different kind of pdb (the new portable pdb, perhaps?) And if so, is there a way to tell it to generate the old kind of pdb?

**Comment by albahari** [comment]
OK, so it looks like I need to support portable PDBs in LINQPad's debugger.
