### ISSUE TITLE
Expose unused symbols for open statements

### ISSUE THREAD

**Issue by dungpa** [fsharp/FSharp.Compiler.Service#91]
Symbol resolution for open statements would help in finding redundant open statements.

This feature could not be done properly without symbol information from FCS.

Related discussion https://github.com/fsprojects/VisualFSharpPowerTools/issues/179

**Comment by CraigStuntz** [comment]
This is apparently also necessary to fix [this refactoring bug](https://github.com/fsprojects/VisualFSharpPowerTools/issues/968#issuecomment-104786692).

**Comment by dsyme** [comment]
Closing old feature reuest
