### ISSUE TITLE
FSharpCompiler.SourceCodeServices.FSharpChecker.ParseFile is slow due to trace

### ISSUE THREAD

**Issue by chinwobble** [fsharp/FSharp.Compiler.Service#911]
Upon doing a performance investigation of Fantomas I found that `FSharpCompiler.SourceCodeServices.FSharpChecker.ParseFile` tracing takes a long time on net framework targets. 

**Repro steps**
run the following code in a console app
Get the source file 
https://raw.githubusercontent.com/fable-compiler/fable-recharts/master/sample2/src/Charts.fs

```fsharp
async {
  let parsingOptions = 
  {{ SourceFiles = [|"/tmp.fsx"|]
    ConditionalCompilationDefines = []
    ErrorSeverityOptions = 
                         { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
    IsInteractive = false
    LightSyntax = None
    CompilingFsLib = false
    IsExe = false }}
    CompilingFsLib: false
    ConditionalCompilationDefines: Length = 0
    ErrorSeverityOptions: {{ WarnLevel = 3
    GlobalWarnAsError = false
    WarnOff = []
    WarnOn = []
    WarnAsError = []
    WarnAsWarn = [] }}
    IsExe: false
    IsInteractive: false
    LightSyntax: null
    SourceFiles: {string[1]}
  let sourceText = FSharp.Compiler.Text.SourceText.ofString source
  let! untypedRes = checker.ParseFile("/tmp.fsx", sourceText, parsingOptions)
}
```
**Expected behavior**

Trace logging / diagnostics should not take much time (<10 ms)

**Actual behavior**
Notice that tracing in jetbrains dotTrace shows that TraceEvent method takes a lot of time.
![image](https://user-images.githubusercontent.com/18226001/65810785-7acb7480-e1f2-11e9-95a4-0b61617957eb.png)

**Related information**

* Win 10 x64
* dotnet framework 4.6.1
* FSharp.Compiler.Services 31.0.0

**Comment by baronfel** [comment]
Can you replicate and report on the upstream repo, dotnet/fsharp? This repo doesn't get new features/fixes directly, it absorbs them from that repository.

**Comment by chinwobble** [comment]
@baronfel thanks for letting me know. I was a bit confused about the purpose of this repo

**Comment by chinwobble** [comment]
Ive created 
https://github.com/dotnet/fsharp/issues/7669
