### ISSUE TITLE
Wrong "version" of FSharp.Compiler.Service.dll - 22.0.3.0

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#922]
As far as I remember, there are some known issues with "normal" assembly/file version.
For example:

(1) In Windows Explorer, RMB \ Properties \ Details
-- all version data are empty.

(2) Or, in PowerShell,

    (Get-Item FSharp.Compiler.Service.dll).VersionInfo | Format-List

-- all version data are default/empty

But there are other ways to exhume the version, at least some version.
For example:

In PowerShell,

    [System.Reflection.Assembly]::ReflectionOnlyLoadFrom("FSharp.Compiler.Service.dll").GetName()

-- it shows that Version is "22.0.3.0" which is slightly out of date, the expected is "34.0.0.0".

Where does it come from? Probably from *fcs\Directory.Build.props*

    <VersionPrefix Condition="'$(VersionPrefix)' == ''">22.0.3</VersionPrefix>

**Suggestion**: If the "normal" version cannot be sorted out, it would be nice to keep at least this one up to date. (Or maybe it should be removed, maybe it just "hides" the correct version? I do not know what VersionPrefix is, TBH)

P.S. Interestingly, ILSpy somehow can see both versions, namely:

    // FSharp.Compiler.Service, Version=22.0.3.0, Culture=neutral, PublicKeyToken=null
    [assembly: AssemblyVersion("22.0.3.0")]
    [assembly: AssemblyFileVersion("34.0.0.0")]
    [assembly: AssemblyInformationalVersion("34.0.0")]

**Comment by baronfel** [comment]
Thanks for the heads-up, I think we can knock this out pretty quickly.

**Comment by baronfel** [comment]
The next version that's released (which will likely be in less than a week given some of the changes I see merged into dotnet/fsharp) will have unified versions.
