### ISSUE TITLE
Package manager key 'nuget' was not registered

### ISSUE THREAD

**Issue by goswinr** [fsharp/FSharp.Compiler.Service#924]
I tried the new   `#r "nuget: FSharp.Data"`  but got this from the error checker:
`error FS3216: Package manager key 'nuget' was not registered`
I use the latest FCS 34.0.0. and this code
```
let checker= FSharpChecker.Create(suggestNamesForErrors=true)
checker.GetProjectOptionsFromScript(fileFsx, sourceText, otherFlags = [| "--langversion:preview" |] )
```
Do I need to register nuget first?

**Comment by smoothdeveloper** [comment]
@goswinr can you try putting a copy to the FSharp.DependencyManager.dll (built from https://github.com/dotnet/fsharp/blob/70883fb00a867f6e81aa9c7cecdd9212c4e78d93/src/fsharp/FSharp.DependencyManager/FSharp.DependencyManager.fsproj) next to the running process or location of the FCS assembly?

the handling of package manager registration is done via reflection and scanning assemblies named that way:

```fsharp
let dependencyManagerPattern = "*DependencyManager*.dll"
```

https://github.com/dotnet/fsharp/blob/70883fb00a867f6e81aa9c7cecdd9212c4e78d93/src/fsharp/DependencyManager.Integration.fs#L14

You can probably build the project from dotnet/fsharp standalone on your own without building the whole repository.

**Comment by baronfel** [comment]
I pulled FCS 34 for regression-related reasons (https://github.com/dotnet/fsharp/issues/8355) but my undedtanding is yes you'd need to register a 'package management handler'. We probably should publish that as a nuget from this repository as well. To be honest I have not thought much about it yet because I haven't fiddled with the package management subsystem yet.

**Comment by goswinr** [comment]
thanks, 
@smoothdeveloper I couldn't build your branch, but the fsharp5 branch, I used the file from 
`\fsharp\artifacts\bin\fsc\Proto\net472\publish\FSharp.DependencyManager.dll`
Now I dont have an error on `#r "nuget: FSharp.Data"` anymore
but  `JsonValue` of `FSharp.Data` is not definied or found. I will do more tests tomorrow...
@baronfel Yes it would be great to have the DependencyManager as part of the fcs nuget.

**Comment by smoothdeveloper** [comment]
@goswinr you can give a shot at those (use at your own risk), hopefully it just works from the compiled FCS you are using

[FSharp.DependencyManager.zip](https://github.com/fsharp/FSharp.Compiler.Service/files/4118121/FSharp.DependencyManager.zip)
[FSharp.DependencyManager.Paket.zip](https://github.com/fsharp/FSharp.Compiler.Service/files/4118122/FSharp.DependencyManager.Paket.zip)

![image](https://user-images.githubusercontent.com/87944/73193286-9dcb4e00-412a-11ea-82c1-7332385f55ad.png)

**Comment by goswinr** [comment]
@smoothdeveloper thanks for the files. no luck yet.  On your branch I get an error about fsharp.core 5.0.0
With your files and FCS 34.0 and with building from fharp5 branch i get this.
is the syntax 
`#r "paket: nuget FSharp.Data"` or 
`#r "nuget: FSharp.Data"` ?
![image](https://user-images.githubusercontent.com/884885/73213945-79369c80-4151-11ea-985d-626d9c63a124.png)

**Comment by smoothdeveloper** [comment]
@goswinr good news, I just tried with master build of FCS but I assume it should work with the nuget:

```fsharp
#r "artifacts/bin/fcs/Release/net461/FSharp.Compiler.Service.dll"
open FSharp.Compiler.SourceCodeServices
open FSharp.Compiler.Text
let checker = FSharpChecker.Create(suggestNamesForErrors=true, keepAssemblyContents=true)
let sourceText = """
#r @"C:\dev\src\github.com\fsprojects\FSharp.Compiler.Service\artifacts\bin\fcs\Release\net461\FSharp.DependencyManager.Paket.dll"
#r "paket: nuget FSharp.Data"
let v = FSharp.Data.JsonValue.Boolean true
"""
let projectOptions = 
  checker.GetProjectOptionsFromScript("test.fsx", SourceText.ofString sourceText, otherFlags = [| "--langversion:preview" |] )
  |> Async.RunSynchronously
  |> fst

let wholeProjectResults = checker.ParseAndCheckFileInProject("test.fsx", 0, SourceText.ofString sourceText, projectOptions) |> Async.RunSynchronously
(fst wholeProjectResults).ParseTree
```

this seems to type check, with a valid parse tree.

**Comment by matthid** [comment]
> can you try putting a copy to the FSharp.DependencyManager.dll (built from 

Is there any reason there is not a proper API for this in FCS? I'm not sure if this is actually a working option for all the deployment options we have in FAKE. I will certainly try but I'm definitely a bit skeptical. I'm not too keen copying stuff around and having a "non-standard" deployment because of this. Additionally, I don't like magic scanning of dll files at locations I don't know.

With proper API I mean one of those:
- Having a compiler flag to provide a folder to search for or direct file path
- Give it the "System.Type" directly (preferred)
- (Turn off the autosearch feature)

**Comment by smoothdeveloper** [comment]
@matthid

> Additionally, I don't like magic scanning of dll files at locations I don't know.

Regarding the deployment of the extension assembly, there is supposed to be a known list of locations to scan for:

https://github.com/fsharp/fslang-design/blob/a356f700adf1a1323329225104ecc52081220a9b/tooling/FST-1027-fsi-references.md#handler-resolution

If you feel that mechanism is not the right approach, could you bring the points https://github.com/fsharp/fslang-design/issues/167 and/or propose edits to the RFC?

> * Having a compiler flag to provide a folder to search for or direct file path

As of now, the FSI implementation (that FCS relies on) doesn't follow the scanning mechanism.

It seems any assembly which is loaded via `#r` is scanned for those extensions and, possibly, passing the assembly as normal reference will also work.

> * Give it the "System.Type" directly (preferred)
> * (Turn off the autosearch feature)

It may be possible to rely on the fact that this member is checked, and if None, the dynamic resolution takes place:
https://github.com/dotnet/fsharp/blob/95d89777032f8191b1f991f0b33977c5e4ccb5bf/src/fsharp/DependencyManager.Integration.fs#L154

Most of the initial work in the compiler was added in this PR: 

https://github.com/dotnet/fsharp/pull/5850/files

I'm waiting for couple of parameters to be reintroduced in dotnet/fsharp and flow through FCS to start working on adding the tests for this PR.

**Comment by smoothdeveloper** [comment]
@goswinr ok, some more actuals:

1. my code sample is not correct, getting a ParseTree doesn't run any code
2. to use extensions, you need to pass additional `--compilertool:..` arguments with path to folder containing the extensions assemblies
3. none of the Compile* method will actually carry the `TcConfigBuiler` that is first correctly created by call to `GetProjectOptionsFromScript`
4. there are few hardcoded paths that are used by the `DependencyManagerIntegration` infrastructure, it seems like the only way right now that using the dependency managers can be achieved for compile of AST scenario is to put the extension assemblies there (on windows, I get `c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\`)

Reminder: my knowledge of FCS is very bare.

@matthid, there is no autosearch beside the `--compilertool` and what's already in place for type provider tooling, AFAIU.

updated code sample:

```fsharp
#r "artifacts/bin/fcs/Debug/net461/FSharp.Compiler.Service.dll"
open FSharp.Compiler.SourceCodeServices
open FSharp.Compiler.Text
let checker = FSharpChecker.Create(suggestNamesForErrors=true, keepAssemblyContents=true)
let sourceText = """
#r "paket: nuget FSharp.Data"
let v = FSharp.Data.JsonValue.Boolean true
"""
let pathToExtension =  @"C:\dev\src\github.com\fsprojects\paket\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0\"
let projectOptions,errorInfos = 
  checker.GetProjectOptionsFromScript(@"c:\test.fsx", SourceText.ofString sourceText, otherFlags = [| "--langversion:preview"; sprintf "--compilertool:%s" pathToExtension |] )
  |> Async.RunSynchronously

let wholeProjectResults, answer = checker.ParseAndCheckFileInProject(@"c:\test.fsx", 0, SourceText.ofString sourceText, projectOptions) |> Async.RunSynchronously
let errors,a,assembly = checker.CompileToDynamicAssembly([wholeProjectResults.ParseTree.Value], "foo", [], None) |> Async.RunSynchronously
```
