### ISSUE TITLE
FSharp.Compiler.Service 34.0.0 was unlisted

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#925]
Why was FSharp.Compiler.Service 34.0.0 unlisted on NuGet?

I already engaged it in my projects and pushed related packages (with FSharp.Compiler.Service included) for users. Should I perhaps revoke/rollback? Or is it fine to continue using  34.0.0?

**Comment by baronfel** [comment]
There was a critical regression in getting script references for net framework that resulted in crashes. I've opened up an issue upstream: https://github.com/dotnet/fsharp/issues/8355.

**Comment by nightroman** [comment]
@baronfel Thank you, it's very useful to know. Feel free to close, it looks like no extra action is needed for this *question*.

**Comment by baronfel** [comment]
I should probably pull/annotate the GitHub release too, huh? Might make it easier to track this sort of thing.
