### ISSUE TITLE
Public API to Obtain Latest Supported Language Version

### ISSUE THREAD

**Issue by SirBogman** [fsharp/FSharp.Compiler.Service#947]
I'm currently using reflection to obtain the value of the `FSharp.Compiler.Features+LanguageVersion.latestVersion` field to obtain the F# language version provided by the compiler service. I would prefer a public API to return the same information. I use this information to display an accurate language version to users of a website without the maintainer of the site having to have any knowledge about the details of F#. I would prefer if the maintainer didn't have to know that FSharp.Compiler.Service 36.0.1 is F# 4.7.

# Context
For [code golf](https://code.golf/about), we display the version of each supported language.

We would like to have an accurate way of getting the language version supported by a particular version of the compiler service DLL. This allows us to provide users with accurate information about the supported language version without the maintainer who updates the NuGet version in the Dockerfile having to know any details about F#.

For F#, instead of invoking the compiler executable directly, we have a small program that uses the language service. This is required, because using the compiler directly is too slow for our use case, because the startup time causes solutions to time out (they only have 7 seconds to run). The custom wrapper helps, because we can use ready to run, which reduces the start up time, and remove assemblies that we don't need, which reduces it further. The startup time is still significantly longer than any other language on the site at about 2 seconds, compared to about 1 second for the language with the second slowest startup time. This is not directly related to the issue, but gives context for why we specifically need to obtain the language version from the compiler service DLL. If we used the F# compiler executable directly, we could parse the version number that it outputs. This is not suitable for our use case.

**Comment by SirBogman** [comment]
For my use case, I'm only interested in obtaining the version number of the latest supported language version. I assume this is the language version that will be used if I don't specify a language version (I'm not sure if I can do that, but it doesn't matter for this use case. I will always want the latest release version).

**Comment by nightroman** [comment]
A side note on startup performance, not the main issue.

> The startup time is still significantly longer than any other language on the site at about 2 seconds

If it's 2 seconds then I believe the startup time may be reduced if you
generate native images using ngen.exe or its helpers like this PowerShell
script: [Invoke-Ngen.ps1](https://www.powershellgallery.com/packages/Invoke-Ngen)

```powershell
Invoke-Ngen -Directory <your-app-base-dir> [-Recurse]
```

In my case this gives ~2 seconds -> less than 1 second.

**Comment by SirBogman** [comment]
Thanks, @nightroman. Is this relevant for .NET Core on Linux? I'm already using Ready to Run. I think most of the startup time is still spent in JIT though and I"m not sure why.

**Comment by nightroman** [comment]
Oh... I am not sure then. I thought that R2R should do *most of JIT*. Never mind then. My case is .NET Framework, I should have mentioned. Anyway, this trick may be useful for other readers.
