### ISSUE TITLE
[Meta] Can't disable appveyor builds for this repo

### ISSUE THREAD

**Issue by baronfel** [fsharp/FSharp.Compiler.Service#951]
@fsharp/fsharp-compiler-service-maintainers can anyone here disable the appveyor integration with this repo? I've moved it over to github actions, but apparently can't disable the webhook that's causing builds to be triggered.  This means that MRs never show as green, which isn't a good look.

**Comment by enricosada** [comment]
Hi @baronfel i tried but while I can see settings page, I don’t have the permissions to do it (I see only a subset)

Maybe @dsyme

**Comment by baronfel** [comment]
That's the same boat I'm in @enricosada :) I see the main 'options' page and then settings for moderation.

**Comment by dsyme** [comment]
Hmm is it still enabled?
