### ISSUE TITLE
How to use interpolated strings with FSharp.Compiler.Service (37.0)?

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#955]
I use the option `--langversion:preview` on running the following script:

```
// https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1001-StringInterpolation.md

let x = 1
let pi = 3.1414
let text = "cats"

let s = $"I say {x} is one and %0.2f{pi} is pi and %10s{text} are dogs"
printfn "%s" s
// I say 1 is one and 3.14 is pi and       cats are dogs

printfn $"I say again {x} is one and %0.2f{pi} is pi"
// I say again 1 is one and 3.14 is pi
```

and get errors:

```
...(7,9): error FS3353: Feature 'string interpolation' requires the F# library for language version 'preview' or greater.
...(11,9): error FS3353: Feature 'string interpolation' requires the F# library for language version 'preview' or greater.
```

Other (previous) preview features work this way, e.g. open static type, nameof.

What am I missing for using interpolated strings?

**Comment by abelbraaksma** [comment]
The difference is explained here: https://github.com/dotnet/fsharp/issues/9904.

This feature only works if you also link to the preview version of FSharp.Core. By default, projects will link to a non preview version of FSharp.Core, like 4.7. You can either build it, or download it from the Nightlies. There's instruction in that issue on how to configure your project to prevent it from using the default library.

**Comment by nightroman** [comment]
@abelbraaksma Thank you. This answers my question and I close it.
