### ISSUE TITLE
FCS update?

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Compiler.Service#958]
Hi @baronfel just wondering what your thoughts are about the next FCS update?

thanks!
don

**Comment by baronfel** [comment]
FCS is being published on a nightly cadence from MS feeds as of about a month ago, there are 38.x prereleases there currently. I've been blocked due to life stuff on incorporating them into FSAC to prove them out, but they seem to be working fine in initial testing!

**Comment by dsyme** [comment]
Oh that's great to know.  Where are they published to?

**Comment by dsyme** [comment]
If you'd like to give an overview at the next dugnad session that would be cool

**Comment by baronfel** [comment]
I have lost the commit where I was working on that, @cartermp can you give the actual answer here? The address you gave me in slack is lost to the sands of time.

@dsyme we're still missing automated publishing of the nuget dependencymanager as well (see https://github.com/dotnet/fsharp/issues/10133 for that), but once that's done I think we'll be in a really nice place for encouraging more rapid uptake/beta testing of the library across the community, and perhaps even start trying things like integrating different 'channels' of FCS into tools like Sharplab.

**Comment by cartermp** [comment]
The feed should be: `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`

And an example installation:

```
nuget install FSharp.Compiler.Service -Source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json -PreRelease
```

Not sure how to do that with the .NET CLI though

**Comment by baronfel** [comment]
`dotnet add package FSharp.Compiler.Service -s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json -version <blah>`

**Comment by baronfel** [comment]
It's pretty simple from a paket perspective as well: add the new source, enable prerelease, and do an update: https://github.com/fsharp/FsAutoComplete/pull/656
