### ISSUE TITLE
Expression tree with anonymous type created incorrectly

### ISSUE THREAD

**Issue by NetMage** [fsharp/FSharp.Compiler.Service#962]
Please provide a succinct description of the issue.

Consider

    let src = [0..10].Select(fun n -> {| n = n |}).ToList().AsQueryable()

    let q1 = src.Select(fun c -> {| z = c.n; b = c.n |})
    printfn "%A" q1.Expression

    let q2 = src.Select(fun c -> {| b = c.n; z = c.n |})
    printfn "%A" q2.Expression

Provide the steps required to reproduce the problem:

1. Run the program

**Expected behavior**

Both `Expression` trees passed to `Select` should call a two argument constructor for the anonymous type directly.

**Actual behavior**

The first call to `Select` creates a nested lambda function call using `Invoke` instead of just passing the arguments to the constructor.

**Known workarounds**

Changing the order of the fields in the anonymous record sometimes will correct the error.

**Related information**

This makes EF Core difficult to use with anonymous records.

* Windows 10
* .NET Core 5
* LINQPad

**Comment by dsyme** [comment]
Could you re-open this at https://github.com/dotnet/fsharp  please?  thank you
